### PR TITLE
Fix HTTP verbs supported by serviceinstances/status

### PR DESCRIPTION
**Pull request by jboyd01**
Part of fix for #1293, similar to #1294

This PR is also including updating generated files that were missing from some previous PR, only substantive changes here are to pkg/registry/servicecatalog/instance/storage.go

### CODE REVIEW

**Comment by MHBauer** [comment]
Split the generated code into it's own commit, please.

**Comment by MHBauer** [comment]
flake fixed by https://github.com/kubernetes-incubator/service-catalog/pull/1275

**Comment by jboyd01** [comment]
I updated the PR with two commits as suggested by Morgan.

**Comment by pmorie** [comment]
waiting for ci

**Pull request merged**
