### PR TITLE
Fix two previously existing lint errors since make verify was complai…

### PR DESCRIPTION
**Pull request by vaikas-google**
…ning

### CODE REVIEW

**Comment by duglin** [comment]
LGTM
but why doesn't travis see this? I see "verify" in the travis yaml

**Comment by vaikas-google** [comment]
Oh, and can you tag it with LGTM1 also? :)

**Comment by duglin** [comment]
yea I had this fix as part of my existing PR - so I can kill that part of it if this goes in first.

**Comment by vaikas-google** [comment]
ha, actually there's a better fix in 
https://github.com/kubernetes-incubator/service-catalog/pull/768

**Comment by duglin** [comment]
yep- let's get that one merged

**Pull request closed without merging**
