### PR TITLE
Build on Mac OS show stat usage error

### PR DESCRIPTION
**Pull request by hchenxa**
I have create issue #687

And I have signed the SLA

### CODE REVIEW

**Comment by krancour** [comment]
@hchenxa I suspect that maybe you've replaced the bsd implementation of `stat` on your system with the gnu implementation of `stat`? The logic here could/should be improved to fork based on which implementation of `stat` is available _instead_ of which OS you're building on, but removing the conditional as you have here is not the right solution because it will break many other Mac users who are using their system's default bsd implementation of `stat`.

**Comment by krancour** [comment]
Also note that the commit from #691 also seems to be bundled into this PR. These two work items should be PR'ed independently.

**Comment by hchenxa** [comment]
@krancour yes, u are right and my command was implement by gnu.

hchenxa@hchen-mac:~$ stat --version
stat (GNU coreutils) 8.27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by thelinuxfoundation** [comment]
bump for CLA check

**Comment by krancour** [comment]
@hchenxa

> And May be we can use below method to check the platform...

sgtm. I'm going to close this PR, but please feel free to open a new one with that change.

Thanks!

**Pull request closed without merging**
