### PR TITLE
Add homebrew install docs for svcat

### PR DESCRIPTION
**Pull request by carolynvs**
Thanks to @ageekymonk we have a [homebrew formulae](https://github.com/Homebrew/homebrew-core/pull/29646) for svcat!

Preview available at: https://deploy-preview-2273--svc-cat.netlify.com/docs/install/#macos-with-homebrew

### CODE REVIEW

**Comment by MHBauer** [comment]
Are we going to take initiative to maintain the versions as we push them?

**Comment by cjwagner** [comment]
Bump for GitHub search re-index.

**Pull request merged**
