### PR TITLE
Add root CAs

### LINKED ISSUE #1176: No Root Certs in Certificate Manager
Right now when trying to access a broker over HTTPS, we get an error

```
      x509: failed to load system roots and no roots provided'
```

which I assume is because the certificate manager image doesn't have the ca-certificates package installed in it.

Should we be including it in the certificate manager Docker image or is there some other way we are expecting users to get root certificates onto their images?

### PR DESCRIPTION
**Pull request by ash2k**
I'm not sure if they are necessary in both images but I don't see any harm in having them.

Fixes #1176.

### CODE REVIEW

**Comment by nilebox** [comment]
👍 for adding root certificates into API server.

> I'm not sure if they are necessary in both images but I don't see any harm in having them.

1. I don't think we need them for controller-manager, since there is no API.
2. I don't see any benefit of adding extra stuff if we don't need it.

Will LGTM once you leave this change only for API server.

**Comment by nilebox** [comment]
Actually I think we need it for controller-manager since it makes calls to the brokers.
Not sure if we need to tweak the broker config for that though, will check later.

**Comment by nilebox** [comment]
So the code in the broker client registering certificates is there: https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/client.go#L50

```go
	if len(config.CAData) != 0 {
		if transport.TLSClientConfig.RootCAs == nil {
			transport.TLSClientConfig.RootCAs = x509.NewCertPool()
		}
		transport.TLSClientConfig.RootCAs.AppendCertsFromPEM(config.CAData)
	}
	if transport.TLSClientConfig.InsecureSkipVerify && transport.TLSClientConfig.RootCAs != nil {
		return nil, errors.New("Cannot specify root CAs and to skip TLS verification")
	}
```

not sure whether `transport.TLSClientConfig.RootCAs` will be correctly initialized if `ClusterServiceBrokerSpec.CABundle == nil`

**Comment by nilebox** [comment]
@ash2k do you know if we need to explicitly configure root CAs for `net/http/Transport` for using available root CAs that you installed using `apt-get install ca-certificates` (see 
the comment above)?

**Comment by pmorie** [comment]
If cabundoe is nil golang uses the root cas, afaik

**Comment by pmorie** [comment]
I mean, uses the built in cas from the system trust store

**Comment by nilebox** [comment]
@pmorie yeah, sounds like it. Than the PR is good to merge, I think.

**Comment by nilebox** [comment]
LGTM.

**Pull request merged**
