### PR TITLE
Fix boilerplate issues

### PR DESCRIPTION
**Pull request by pmorie**
@kubernetes-incubator/maintainers-service-catalog PTAL

### CODE REVIEW

**Comment by martinmaly** [comment]
Let's remove the *.pyc files. LGTM otherwise.

**Comment by duglin** [comment]
oh man - python!?!?  Any chance we can keep the number of languages people need to learn down to 2? just golang and bash

**Comment by duglin** [comment]
LGTM
my comment about langs is a different issue

**Comment by krancour** [comment]
I agree with getting rid of the .pyc files. I agree with trying to get rid of Python in general. (Nothing against it, but I agree with @duglin that the project benefits if we minimize the number of languages one needs to know).

That said, I recognize that _both_ of those concerns should be separate issues (which I will open) and that _this_ PR is just aimed at making style checks happy.

LGTM

**Pull request merged**
