### PR TITLE
phony output binaries

### PR DESCRIPTION
**Pull request by MHBauer**
I had this written but forgot to push it.

Adapted it with removal of calls to clean-bin. I think this should work on release and avoid arch problems that we had previously.

### CODE REVIEW

**Comment by pmorie** [comment]
@MHBauer this looks good to me as someone who is not a Makefile expert.

Does this retain the semantics that NEWEST_GO_FILE gave, or are those removed?

**Comment by duglin** [comment]
@pmorie I believe it, sort of, does retain it, but let's the go compiler do it for you. What I believe is different here is that before this change "make" would skip the target entirely, but now it'll execute it (meaning the go compile step would be run but have no output if nothing changed) BUT any Makefile target that had this as a dependencies would also now be executed, where before it may have been skipped. I don't think we have this situation right now though.

Additionally, I think the e2e.test would now be executed each time w/o checking to see if something changed. So that's a change.

**Comment by carolynvs** [comment]
I think this is relying on go's built-in compiler smarts around what's changed, what needs to be rebuilt vs. what can be reused from the last build, no? In 1.10 this speeds up compile times quite a bit.

**Comment by MHBauer** [comment]
@carolynvs has the deets. Semantically it should be the same.

Hope for 1.10 soon for multiple reasons.

**Comment by arschles** [comment]
Ref #1734 for the 1.10 work

**Comment by MHBauer** [comment]
The need for this isn't removed by go 1.10.

**Comment by MHBauer** [comment]
#1734 is more of a "let's always be testing against tip for future compatibility" PR, and less specifically about 1.10. I figure we'd either add a 1.10 var explicitly, or in addition to bumping 1.9 everywhere else, bump it there as well. A go canary, and our small contribution to ensuring that 1.10 is as ready for us as we are for it.

Actually moving to 1.10 can happen when 1.10 is released, and we explicitly opt into using it.

**Comment by arschles** [comment]
ah, makes sense @MHBauer - LGTM

**Comment by kibbles-n-bytes** [comment]
Fine, we can add your phony non-phony target. :stuck_out_tongue: I'd like to eventually just remove the `bin/${BLA}` targets, and make the non-bin versions phony.

**Pull request merged**
