### PR TITLE
Fix the build

### PR DESCRIPTION
**Pull request by arschles**
It was broken in https://github.com/kubernetes-incubator/service-catalog/pull/57

### CODE REVIEW

**Comment by arschles** [comment]
@martinmaly fwiw, it "works on my machine" (tm) 😁 

```console
ENG000656:service-catalog aaronschlesinger$ make build
Building github.com/kubernetes-incubator/service-catalog/registry
Building github.com/kubernetes-incubator/service-catalog/contrib/broker/k8s
Building github.com/kubernetes-incubator/service-catalog/contrib/broker/user_provided
Building github.com/kubernetes-incubator/service-catalog/controller
```

**Comment by duglin** [comment]
ok build is fixed with this so I'm merging w/o 3 LGTMs since this is critical to get master back to normal.

LGTM

**Comment by arschles** [comment]
Thanks @duglin. I have a habit of not merging my own PRs

**Comment by duglin** [comment]
@arschles that's a good habit  :-)

**Pull request merged**
