### PR TITLE
Rename generated

### PR DESCRIPTION
**Pull request by MHBauer**
@duglin 

It should be clear that generated code is generated.

I wanted to also camelCase things, or dash-separate them, but golang does not support dashes in file names and client-gen does not support camelCase. 

The camelCase thing is a clear defect as camelCase is a supported go package naming scheme.

Underscores are ugly.

### CODE REVIEW

**Comment by MHBauer** [comment]
@pmorie Yes, result of brainstorming in #418 I can move it to a `generated` folder, but I can't do that for all the generated code, I don't think. I think this is clear and matches the intent shown in the naming of the clientset part.

**Comment by MHBauer** [comment]
In case I need to script this again later

```
go get golang.org/x/tools/cmd/gomvpkg
gomvpkg -from github.com/kubernetes-incubator/service-catalog/pkg/client/listers  -to github.com/kubernetes-incubator/service-catalog/pkg/client/listers_generated
gomvpkg -from github.com/kubernetes-incubator/service-catalog/pkg/client/informers  -to github.com/kubernetes-incubator/service-catalog/pkg/client/informers_generated
```

**Comment by duglin** [comment]
LGTM

**Comment by MHBauer** [comment]
I am completely shocked that this merged cleanly.

**Pull request merged**
