### PR TITLE
Add autonomous bookstore client.

### PR DESCRIPTION
**Pull request by mkibbe1993**
Change-Id: Ic582892c4d23712dd968c4fb555255de05ce6f83

### CODE REVIEW

**Comment by arschles** [comment]
What is this for?

**Comment by mkibbe1993** [comment]
This client allows for an easy and automated way to hit all the endpoints of the demonstration/test bookstore project. It's useful for both simulating traffic to a demo cluster and as a means to test whether the endpoints are acting as expected. It's integrated in a later commit of mine into the Jenkins end-to-end tests and replaces all the current manual curl calls.

**Comment by martinmaly** [comment]
LGTM (`LGTM1` label added)

**Comment by arschles** [comment]
@mkibbe1993 @martinmaly I'm confused why we'd need this in e2e tests for a service broker, and I suspect I'm missing something fundamental to how they work. Can you point me to somewhere that explains what the tests are doing (maybe I missed it in-code somewhere)?

**Comment by martinmaly** [comment]
@arschles @mkibbe1993 We have a documentation gap. Before we fill it ... the goal of the e2e test is to spin up the k8s cluster, start up the catalog in it, and then use the catalog to spin up a service, hook a client to it, and expose it to traffic.

So not only does it test that catalog started and works correctly, but also that the application started (and hooked up) by the catalog works as expected.

I think that this kind of e2e test is within scope of our work (especially as we add support for SIPs etc, we'll need to ensure they work properly). At the same time, it wouldn't be a goal to spin up overly complex applications. This simple bookstore, IMO, strikes the right balance.

**Comment by arschles** [comment]
@martinmaly @mkibbe1993 I see! That answers a lot of my questions. I certainly don't need a full architecture diagram of e2e tests at this point, but I'd love to see some documentation in the next few weeks (maybe after e2e is in and working?). Can you create a GH issue for that?

LGTM (added `LGTM2` label)

**Comment by krancour** [comment]
Veto pending further discussion. Rationale to follow...

**Comment by martinmaly** [comment]
@krancour ... not to bee too strict about this but so far your veto is unqualified and therefore unenforceable.

**Comment by krancour** [comment]
@martinmaly I'm typing up my rationale right now. I wanted to get the veto in before a 3rd LGTM came in.

**Comment by krancour** [comment]
imo, there's one more moving piece here than is necessary. The "client" here is a test program that drives requests to an app, which in turn relies on the service? Why not cut out the (web) app entirely and combine the idea of the client and app into a single, _simpler_ component-- something that is deployed to the cluster (like an app) and makes assertions _itself_ (like the client) about its own ability to communicate with the provisioned service?

**Comment by martinmaly** [comment]
@krancour Thanks for the suggestion. I wonder how the test would drive this self-validating component and get its success status, logs etc.

We considered ideas such as this for, for example, making sure that catalog components were deployed correctly (spinning up watcher container in the cluster). This is similar, but I am not sure how to get the right detail of feedback from this app.

If I understand correctly, you'd propose to turn this application into a k8s app and e2e test would spin it up rather than run locally?

**Comment by arschles** [comment]
I like that idea of combining the client & app, but it feels like an optimization, and not blocking to get e2e tests up and running. @krancour objections?

**Comment by mkibbe1993** [comment]
My thoughts are what we perhaps lose structural simplicity we gain in functionality. Since this is just a simple autonomous user for the bookstore app, it has applicability beyond just the e2e tests; it also allows us to easily automate user traffic and poke at a demo app at will through a simple call to the script. @martinmaly also suggested to me that it would be useful when we expand beyond just running in k8s.

I think the idea of a client/app hybrid is interesting, but it seems like a optimization that'll take time to implement that in turns narrows usability without too much gain, and at the moment, like @arschles said, we have something already working and optimizing on that would block getting e2e tests up.

**Comment by martinmaly** [comment]
To clarify on the 'running beyond k8s' bit ... I can imagine that we'll want a client to our test which doesn't run in k8s cluster (as well as one that does).

**Comment by krancour** [comment]
I'm amenable to the idea of having _something_ sooner than later, so I'll remove my veto, but I'm going to open a separate issue to capture the need for an optimization here.

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
My only comment on this one is that let's try to comments like https://github.com/kubernetes-incubator/service-catalog/pull/110#issuecomment-265000516 in the original comment for the PR rather than a "Change-Id" - which doesn't mean a lot to readers.

**Comment by pmorie** [comment]
Why does this belong in `script?` -- it should go in `hack` or under `contrib`

**Comment by duglin** [comment]
doi - missed that - agreed. @mkibbe1993 can you open an PR to move it to where the samples are?

**Comment by martinmaly** [comment]
I'm fine with putting it in `contrib` although `test` may seem more appropriate since that's what it is - a test.

**Comment by duglin** [comment]
@martinmaly I'm ok with create a "tests" top level dir for non-unit tests - if that's where this belongs.

**Comment by pmorie** [comment]
I'm fine with test/script.  Do not make `test` and `tests`

**Pull request merged**
