### PR TITLE
Default to NodePort for API server service when debug is not set

### LINKED ISSUE #423: wip-catalog chart's apiserver svc type dependent on debug?
The `wip-catalog` Helm chart has the apiserver's `Service` type dependent on whether `debug=1` is set or not.

I can't understand why the type of service we use should be dependent on whether we're debugging or not. Additionally, when debugging, one gets a service of `type: LoadBalancer` and that avoids this error, which arises if _not_ debugging  / using service of default `type: ClusterIP`:

```
$ helm install     --set "registry=${REGISTRY},version=${VERSION}",storageType=etcd,insecure=true     --namespace catalog     ./deploy/wip-catalog
Error: release lumpy-bee failed: Service "apiserver" is invalid: spec.ports[0].nodePort: Invalid value: 30001: may not be used when `type` is 'ClusterIP'
```

https://github.com/kubernetes-incubator/service-catalog/blob/master/deploy/wip-catalog/templates/apiserver.yaml#L59-L61

### PR DESCRIPTION
**Pull request by pmorie**
Fixes #423

### CODE REVIEW

**Comment by pmorie** [comment]
cc @krancour

**Comment by duglin** [comment]
let's add a port for the secure path for consistency and completeness, then LGTM

**Comment by arschles** [comment]
I'm going to defer to @krancour on this, since he created the issue

**Comment by pmorie** [comment]
I think based on #517 that @krancour is going to take care of this himself in his PR.

**Comment by krancour** [comment]
I would be happy to fix this as part of #517, but I'm still very confused as to _why_ we continue to think that debugging vs not debugging has some bearing on which type of service resource we create. I'd like to get a handle on that. @pmorie ?

**Comment by pmorie** [comment]
@krancour originally it was added by @arschles for his debugging purposes

**Comment by krancour** [comment]
If we want this to be a knob that people can turn, that's fine. It's not uncommon in existing charts to see the _type_ of service(s) that is/are created being tunable in this manner. I don't don't think we should make that decision on the basis of debug vs not debug. I will disentangle those two concerns in #517. Going to close this if that's ok.

**Pull request closed without merging**
