### PR TITLE
rebase onto k8s 1.6-candidate

### PR DESCRIPTION
**Pull request by jpeeler**
There are several areas that have been hacked around to get things to compile,
all areas in need of attention have been marked with "JPEELER":

cmd/apiserver/app/server/run_server.go
cmd/apiserver/app/server/util.go
cmd/controller-manager/app/controller_manager.go
pkg/storage/tpr/keyer.go
pkg/storage/etcd/options.go
pkg/apiserver/etcd_config.go
pkg/apiserver/tpr_config.go
pkg/registry/servicecatalog/server/options.go
pkg/registry/servicecatalog/server/options.go

### CODE REVIEW

**Comment by pmorie** [comment]
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/413

**Comment by arschles** [comment]
the rebase needs a rebase

**Comment by pmorie** [comment]
I think it is in our best interest **not to squash** these commits because the PR is so big.  If we find a problem afterward it will be easier to locate if we retain distinct commits.

**Comment by arschles** [comment]
@jpeeler looks like `glog` might be missing from the dependencies: https://travis-ci.org/kubernetes-incubator/service-catalog/builds/218578964#L305

**Comment by jpeeler** [comment]
I've been having difficulties getting the tests to always pass (jenkins is currently stuck). I suspect there is a race issue in TestBasicFlows as that is the test that sometimes times out waiting to connect to the api server:

> I0404 20:54:05.255698   32351 framework.go:118] Waiting for : "https://localhost:35172"
I0404 20:54:05.356680   32351 framework.go:118] Waiting for : "https://localhost:35172"
I0404 20:54:05.457870   32351 framework.go:118] Waiting for : "https://localhost:35172"
--- FAIL: TestBasicFlows (120.86s)
	framework.go:96: waiting for apiserver timed out
FAIL
exit status 1
FAIL	github.com/kubernetes-incubator/service-catalog/test/integration	138.149s
!!! [0404 20:55:48] Call tree:
!!! [0404 20:55:48]  1: test/integration.sh:35 runTests(...)
!!! Error in test/integration.sh:28
  Error in test/integration.sh:28. '((i<3-1))' exited with status 1
Call stack:
  1: test/integration.sh:28 runTests(...)
  2: test/integration.sh:35 main(...)
Exiting with status 1

**Comment by arschles** [comment]
Thanks a ton for this everyone. @pmorie has requested that we merge this with all commits intact -- and not squash or rebase. I will merge after checking with @jpeeler offline whether he wants to manually rebase anything

**Comment by derekwaynecarr** [comment]
awesome!

**Comment by MHBauer** [comment]
yay

**Pull request merged**
