### PR TITLE
Passing a RESTClient through to the TPR storage

### PR DESCRIPTION
**Pull request by arschles**
This prepares for TPR storage integration tests. Ref https://github.com/kubernetes-incubator/service-catalog/issues/407

cc/ @krancour

### CODE REVIEW

**Comment by arschles** [comment]
Yes 👍

**Comment by krancour** [comment]
> The intention here is that the integration tests can pass in a mocked out restclient for the core apiserver?

> Yes 👍

@arschles I may have asked you this earlier offline, but I'm fuzzy on the answer... if we mock out a dependency as critical as the core apiserver (which is what this effectively will permit), isn't that, then, _not_ an integration test? i.e. To know we got TPR storage right, doesn't it have to be validated against a _real_ upstream apiserver?

**Comment by pmorie** [comment]
CI legit broke

**Comment by arschles** [comment]
@krancour you're correct -- this isn't a full integration test like the etcd based ones are, because we are missing the core API server. It's as close as we're going to get right now, until we have the ability to run our API server in a real cluster (something that is coming with our e2e efforts)

**Comment by arschles** [comment]
Given this is critical to make progress on the MVP 2 https://github.com/kubernetes-incubator/service-catalog/issues/407, and to unblocking @krancour's efforts on the same issue, I am merging this now.

**Pull request merged**
