### PR TITLE
Code changes for Open Service Broker API

### PR DESCRIPTION
**Pull request by pmorie**
Renames in code to move to Open Service Broker API.

@kubernetes-incubator/maintainers-service-catalog

### CODE REVIEW

**Comment by vaikas-google** [comment]
LGTM

**Comment by krancour** [comment]
LGTM

**Comment by krancour** [comment]
Sorry about addition and removal of "bug" label above. That was some heinous fat-fingering on my part.

**Comment by MHBauer** [comment]
rename LGTM.

**Comment by duglin** [comment]
waiting for tests to finish before merging....

**Pull request merged**
