### PR TITLE
Set SelfLink and Namespace fields correctly for Instances and Bindings

### PR DESCRIPTION
**Pull request by pmorie**
This was excruciatingly difficult to track down. 😱 

cc @MHBauer @arschles

### CODE REVIEW

**Comment by MHBauer** [comment]
hey, look, two more places we have namespace information! It's almost like the types should have a method where they can be queried for whether they are in a namespace.

The links look good. Any ideas on brokers and serviceclasses?

**Comment by pmorie** [comment]
> The links look good. Any ideas on brokers and serviceclasses?

Broker and ServiceClass are correctly implemented as being non-namespaced.

**Comment by arschles** [comment]
I'm good with this. LGTM and merging now

**Comment by MHBauer** [comment]
```
  selfLink: /apis/servicecatalog.k8s.io/v1alpha1/brokerstest-broker
  selfLink: /apis/servicecatalog.k8s.io/v1alpha1/serviceclassestest-serviceclass
```
That doesn't look right to me.

**Comment by pmorie** [comment]
Yep, those are issues, but not this issue.

**Pull request merged**
