### PR TITLE
use kubectl pluginutils lib to parse config for svcat in plugin mode

### PR DESCRIPTION
**Pull request by jberkhahn**
I had to override the version requirement for client-go as the kuebctl repo is still new and don't have their dependencies pegged to release versions yet.

@carolynvs could you take a look at this?

### CODE REVIEW

**Comment by pmorie** [comment]
@jberkhahn rebase needed

**Comment by MHBauer** [comment]
@carolynvs I wanted to try to rebase this to learn more about dep, but dep just hangs for me when I run `dep ensure`. What's the appropriate way to resolve this to make sure dep is happy.

**Comment by carolynvs** [comment]
This is what I would try:

1. Rebase
2. rm -r $GOPATH/pkg/dep (since you said it was hanging, this clears the cache)
3. `dep ensure -v` and be patient since k8s is big. If it hangs, this will show you where.
4. commit changes to the lock, if any

**Comment by MHBauer** [comment]
@carolynvs like multiple hours? or how long do you think?

**Comment by carolynvs** [comment]
Ah! 😝  I meant like on a fresh dep cache it could take maybe 2 minutes.

**Comment by jberkhahn** [comment]
@pmorie been rebased

**Pull request merged**
