### PR TITLE
statically compile

### PR DESCRIPTION
**Pull request by MHBauer**
Turned some debugger stuff off because I'm not sure anyone in the history of golang has ever tried to attach a debugger more than once.

going to want it for plugins.

### CODE REVIEW

**Comment by n3wscott** [comment]
I use the debugger all the time now that I am using goland. Will this break that workflow?

**Comment by MHBauer** [comment]
@n3wscott no idea. we can leave debugging information on if it helps. I don't see any reason to distribute it. Can you show off gogland in a meeting? Link? I am always looking for new go tools, even bad ones.

**Comment by nilebox** [comment]
@MHBauer @n3wscott have you agreed on what to do with this PR?

**Comment by jboyd01** [comment]
@n3wscott: you mentioned gogland & debugging, do you use it on a running server vs just the tests?  If yes then a huge  +1 to @MHBauer's suggestion to show it off at a meeting.  I poked at gogland 6 months ago but haven't looked again.

**Comment by MHBauer** [comment]
We can leave the debugging in. I'll write up a little table on the results wrt binary sizes and junk.

**Comment by MHBauer** [comment]
A different reason to statically compile is to move to using a scratch or other small image and solve some of the quay vulns from the vuln scanner.

**Comment by carolynvs** [comment]
If all you care about is being able to run on a scratch container this is what you need:

```
CGO_ENABLED=0 go build -tags netgo
```

The other LDFLAGS in this pull request, AFAIK, only affect the size of the final binary (and your ability to debug it).

**Comment by n3wscott** [comment]
I don't attach to running instances, so I am ok with this.

LGTM

**Comment by MHBauer** [comment]
@carolynvs I think this was before we had merged and used hyperkube, so the savings was more than it is now. I think moving to scratch is definitely a goal, but I'm not sure how much that interfaces with multi-arch.

**Comment by MHBauer** [comment]
@carolynvs what's going on here? Does windows not support static building?

**Comment by carolynvs** [comment]
`-d` isn't available on Windows. Yes, it is still statically compiled though. 

Per the doc that flag doesn't change much, I never bother with it:

> Disable generation of dynamic executables.
	The emitted code is the same in either case; the option
	controls only whether a dynamic header is included.
	The dynamic header is on by default, even without any
	references to dynamic libraries, because many common
	system tools now assume the presence of the header.

**Comment by MHBauer** [comment]
I'll give it a shot.

**Comment by carolynvs** [comment]
🍿

**Comment by carolynvs** [comment]
Adding a LGTM label on behalf of @n3wscott since I think it was just forgotten.

**Pull request merged**
