### PR TITLE
Add service resource for the controller manager

### PR DESCRIPTION
**Pull request by sebastien-prudhomme**
This PR is a 
 - [x ] Feature Implementation
 - [ ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:

This PR enables to use Prometheus Operator ServiceMonitor to scrap metrics on the controller manager.

This PR adds a service resource for the controller manager in the Helm chart.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by jboyd01** [comment]
Hey @sebastien-prudhomme, thanks for the PR.   I've got a couple questions/thoughts.

Instead of creating a Service for the Controller, have you tried enabling enablePrometheusScrape in values.yaml?   https://github.com/kubernetes-incubator/service-catalog/blob/58b88f4d33cb708e4b22c39ccbe498b00738488e/charts/catalog/values.yaml#L161-L162

This will cause the the annoation `prometheus.io/scrape` to be added to each pod.  To my knowledge this annotation works with most Prometheus deployments enabling the Controller pods to be scraped.  I have not tried it with the Prometheus Operator myself.

If we create the Service to enable Prometheus scraping, is there additional configuration required in the Prom Operator to cause it to scrape services?

Is the NodePort required for Prometheus?  This has side effects such as exposing the Catalog Controller to external access.

If we do merge this PR I'd like to get some documentation around it including any assumptions with regards to the Operator configuration.  Perhaps update https://github.com/kubernetes-incubator/service-catalog/tree/master/contrib/examples/prometheus ?

**Comment by sebastien-prudhomme** [comment]
Hi @jboyd01 Sure you can have automatic scrape directly on pods by using the right annotations but this is not compatible with the prometheus operator and have some limitations, that's why the prometheus operator dev team introduced the ServiceMonitor resource.

You need the Service resource AND a ServiceMonitor resource that have a selector for the service. The service just need an IP, so ClusterIP service type is enough, no need to expose the service in the external world. My fault as i just copy paste what was done for the other service. Will correct it.

The advantage of the prometheus operator is that you can also declare alert rules in your YAML kubernetes files.

**Comment by jberkhahn** [comment]
/ok-to-test

I'm not certain we need this on by default.

**Pull request merged**
