### PR TITLE
Enable Travis

### PR DESCRIPTION
**Pull request by martinmaly**

### CODE REVIEW

**Comment by duglin** [comment]
shouldn't this do more than just "init" ? why not build & test ?

**Comment by martinmaly** [comment]
Travis does many things automatically. The default test script is "make". That, in turn, is equivalent to 'make build test lint'

Example run: https://travis-ci.org/martinmaly/service-catalog/builds/179931553

**Comment by vaikas-google** [comment]
LGTM

**Comment by duglin** [comment]
ah ok - LGTM to me then

**Comment by arschles** [comment]
LGTM

**Pull request merged**
