### PR TITLE
Checking in vendor directory

### LINKED ISSUE #620: service catalog must check-in its vendored dependencies
The service catalog needs to check in its vendor code into the source tree.

1. we cannot rely on vendored projects we rely on today existing tomorrow
1. we need to be able to build past releases of service catalog in the future in case of security fixes, etc.  not having those dependencies checked into the repository makes us unable to provide that guarantee
1. we need to also ensure that every dependency must have a license per coding convention guidelines https://github.com/kubernetes/community/blob/42ec015a21824ab2698e1f7b9c8bf7bb4df69d49/contributors/devel/coding-conventions.md

While I cannot find it directly stated, I think this should be a requirement for incubation.

For reference on best practice, see examples below:

**Kubernetes**

https://github.com/kubernetes/kubernetes/tree/master/vendor
https://github.com/google/cadvisor/tree/master/vendor
https://github.com/kubernetes/kops/tree/master/vendor
https://github.com/kubernetes/heapster/tree/master/vendor
...

**Kubernetes incubators**
https://github.com/kubernetes-incubator/cri-o/tree/master/vendor
https://github.com/kubernetes-incubator/kube-aws/tree/master/vendor
https://github.com/kubernetes-incubator/kompose/tree/master/vendor
https://github.com/kubernetes-incubator/rktlet/tree/master/vendor
https://github.com/kubernetes-incubator/cluster-capacity/tree/master/vendor

### LINKED ISSUE #649: master builds failing on travis
Last two here https://travis-ci.org/kubernetes-incubator/service-catalog/builds

```
pkg/storage/tpr/keyer_test.go:33: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".NewContext
pkg/storage/tpr/keyer_test.go:34: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".WithNamespace
pkg/storage/tpr/keyer_test.go:40: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".NewContext
pkg/storage/tpr/keyer_test.go:48: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".NewContext
pkg/storage/tpr/keyer_test.go:49: undefined: "github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/kubernetes/pkg/api".WithNamespace
FAIL	github.com/kubernetes-incubator/service-catalog/pkg/storage/tpr [build failed]
```

### PR DESCRIPTION
**Pull request by arschles**
This is one **massive** patch that adds the entire vendor directory

As I've said [here](https://github.com/kubernetes-incubator/service-catalog/issues/620#issuecomment-290404374), I do not like doing this, and I lobbied for not checking in the `vendor` directory to this repository long ago, but I believe I was wrong.

We've spent a lot of time and developer cycles trying to elegantly solve our dependency management challenge, and I don't think we should do so anymore.

This PR also fixes the keyer tests that are broken on master as described in #649

Closes #619 
The above is because this PR also removes the `glide install` pre-requisites for each makefile target.

Fixes #620
Fixes #649

### CODE REVIEW

**Comment by MHBauer** [comment]
Still need to build the the scbuildimage. We may still need the `.init` target, but can block everything that is glide related.

**Comment by MHBauer** [comment]
I don't really have anyway to check this beyond building it, so LGTM when it builds.

**Comment by arschles** [comment]
We should wait for #596 before merging this

**Comment by MHBauer** [comment]
Sure. Maybe fold this into that as well.

**Comment by derekwaynecarr** [comment]
assuming this passes a build after a rebase, i am happy as well.  thanks!

**Comment by arschles** [comment]
Looks like this suffers from the same flake as described in https://github.com/kubernetes-incubator/service-catalog/issues/643

**Comment by MHBauer** [comment]
Travis is good enough for me. LGTM.

**Comment by MHBauer** [comment]
Can we squash into two? One with the code changes and one with all the vendor stuff?

**Comment by arschles** [comment]
@MHBauer I'd like to squash everything into 1 on merge, using the Github "Squash and Merge" button

**Comment by MHBauer** [comment]
yay!

**Pull request merged**
