### PR TITLE
Fix bug in create service binding errors 

### PR DESCRIPTION
**Pull request by viviyww**
Fixes #2513

This PR is a 
 - [ ] Feature Implementation
 - [x] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by jberkhahn** [comment]
There was no need to open a second PR. This looks like it also had additional commits that have nothing to do with the original branch. I'm closing this PR, and please direct future work at the original PR #2513

**Comment by viviyww** [comment]
Ok, thanks.

**Pull request closed without merging**
