### PR TITLE
remove accidental code

### PR DESCRIPTION
**Pull request by MHBauer**
I was inattentive and bit jumpy when I pushed the original version. This should not have been pushed.

check on your local system with `rm -rf pkg/client/ .generate_files && make .generate_files`

### CODE REVIEW

**Comment by duglin** [comment]
I wouldn't mind making our build process erase all generated files and regenerating them to avoid stuff like this slipping into the release.  And, yes, this wouldn't have happened if we didn't check-in generated files :-)  ....but for now...

LGTM

**Comment by krancour** [comment]
Which was the PR that contained the changes that shouldn't have been pushed?

**Comment by MHBauer** [comment]
@krancour #348 is the one that introduced these files.

**Comment by pmorie** [comment]
It looks to me like these were generated from a run with incorrect params
and we just didn't catch it, accurate?

**Comment by MHBauer** [comment]
@pmorie stupider and more insidious than that. I had used incorrect parameters on a previous run, but did not clean my environment in the middle. Now I have a local script to `rm -rf pkg/client` and regenerate.

**Pull request merged**
