### PR TITLE
controller requires permission to update secrets

### LINKED ISSUE #1575: Missing RBAC permissions
`update` verb for `secrets` resource is missing. Not sure which role should have it. The code is here:
https://github.com/kubernetes-incubator/service-catalog/blob/c6e446e504b5f2a96cd50d0d3e0373d173145906/pkg/controller/controller_binding.go#L974

Another thing: in Kubernetes 1.8 a new admission controller called [`OwnerReferencesPermissionEnforcement`](https://kubernetes.io/docs/admin/admission-controllers/#ownerreferencespermissionenforcement) was added. Probably some additional permissions are needed for Service Catalog if it is enabled so might be a good idea to put them into the Helm chart. I haven't tried enabling it yet, but I expect there will be issues.

### PR DESCRIPTION
**Pull request by MHBauer**
resolves #1575

Controller call the 'update' method in the client, so we need the 'update' access.

### CODE REVIEW

**Comment by pmorie** [comment]
I will merge this after master is green in travis again.  Interestingly, this branch didn't flake in travis!

**Comment by MHBauer** [comment]
No rush. I wish there was more information available from travis to try and know what the heck is going on. Why do some succeed? I just don't know what information would help.

**Comment by MHBauer** [comment]
@pmorie You want I should rebase this one or wait for a replay on it's own?

**Comment by pmorie** [comment]
> @pmorie You want I should rebase this one or wait for a replay on it's own?

@MHBauer not necessary - I just found it interesting that this one had passed when others had flaked.  I'm still quite vexxed by this and want to get to the bottom of it.

**Comment by MHBauer** [comment]
@pmorie my best guess is we're on the very edge of some kind of resource exhaustion, but I'm not sure what the limits are on travis or how to measure anything during a run.

**Comment by MHBauer** [comment]
Not sure where to go about debugging it, but during runs, I see very little CPU usage (bursty), but ever increasing memory usage from start to finish. It could be we're hitting swap or something on the travis VMs?

**Comment by pmorie** [comment]
> my best guess is we're on the very edge of some kind of resource exhaustion, but I'm not sure what the limits are on travis or how to measure anything during a run.

Yeah, I have the same suspicion.

> Not sure where to go about debugging it, but during runs, I see very little CPU usage (bursty), but ever increasing memory usage from start to finish. It could be we're hitting swap or something on the travis VMs?

Those are interesting theories.  I have some thoughts on this, will comment on https://github.com/kubernetes-incubator/service-catalog/issues/1660, let's record discussion there.

**Comment by pmorie** [comment]
Not sure why this wasn't merged earlier - apologies

**Pull request merged**
