### PR TITLE
Fix failing test: TestReconcileServiceInstanceWithFailedCondition

### PR DESCRIPTION
**Pull request by luksa**
The controller now exits every time it updates the ServiceInstance, so
the tests must call reconcileServiceInstance multiple times.

### CODE REVIEW

**Comment by pmorie** [comment]
How did a breaking change get merged?

**Comment by kibbles-n-bytes** [comment]
@pmorie The tests ran for #1779 and passed, then something merged that broke it but was not a merge conflict, and then #1779 merged.

**Comment by kibbles-n-bytes** [comment]
Link to Travis discussion: https://github.com/travis-ci/travis-ci/issues/1620

**Comment by luksa** [comment]
This is the commit that was effectively merged "in parallel" with my changes: https://github.com/kubernetes-incubator/service-catalog/commit/bddb9a78eddbb1fb0e578cd2bf907fd072490e0c

**Pull request merged**
