### PR TITLE
Move versioned clientset into correct package

### PR DESCRIPTION
**Pull request by pmorie**
@MHBauer my bad - I missed this during #337.  The `internalclientset` package is for the unversioned client -- you've generated a versioned client here.  I tried to get the internal clientset generating correctly as well but ran into some issues.  So just moving versioned clientset to the right package at this point, since I need that for a new controller skeleton I'm writing.

### CODE REVIEW

**Comment by duglin** [comment]
When do people use the versioned vs unversioned client?

LGTM

**Comment by krancour** [comment]
@pmorie can correct me if I'm wrong, but our controller will use the unversioned client to talk back to its own apiserver. Anyone external talking to us uses a versioned client and the api machinery handles conversion between those versioned types and the unversioned ones we use internally.

**Comment by krancour** [comment]
LGTM

**Comment by duglin** [comment]
@krancour that would make sense - thanks

**Comment by MHBauer** [comment]
So we need both, but we don't know how to generate one.

**Pull request merged**
