### PR TITLE
Flip Chairs (╯°□°）╯︵ ┻━┻

### PR DESCRIPTION
**Pull request by carolynvs**
* Emeritus: Ville 👋 
* Emeritus: Aaron 👋 
* New: Carolyn 🎉 
* New: Michael 🎉 

While I was in there, I switched to displaying our github profile image, instead of hosting it on our site directly.

### CODE REVIEW

**Comment by carolynvs** [comment]
Preview available at: https://deploy-preview-2222--svc-cat.netlify.com/community/#leadership

**Comment by jboyd01** [comment]
Congrats!
/lgtm

**Comment by carolynvs** [comment]
bfast-end

**Pull request merged**
