### PR TITLE
add e2e walkthrough testing in Jenkins

### PR DESCRIPTION
**Pull request by kibbles-n-bytes**
First pass at e2e testing for the new walkthrough. Jenkins will spin up a cluster on GKE and go through every step of the walkthrough, just as an end user would. Uses an etcd-backed API server. Must add the `jenkins` label to your PR in order to have Jenkins run.

Closes: #487
Closes: #456

### CODE REVIEW

**Comment by MHBauer** [comment]
I suppose two helm commands is okay. I'd like to have one that gets it down to zero.

**Comment by pmorie** [comment]
This is fantastic work. Have you verified that you can break it yet? :-) use an API server image from before graceful deletion was implemented. 

I'm going to run this personally tomorrow before I LGTM, but this looks very thorough.

**Comment by kibbles-n-bytes** [comment]
Thanks! Haven't done an exhaustive test yet; there's a couple of Jenkins-related assumptions I have to remove in order to make that a bit easier, but I'm getting that done now. :)

**Comment by arschles** [comment]
I'd like to see these enabled for TPR-based storage as well. @kibbles-n-bytes that can be done by setting `storage.type=tpr` inside the `--set` list in the helm install.

**Comment by pmorie** [comment]
@arschles I would prefer not to block on adding TPR to have this merged.  It will add stability as-is and we can do TPR in a follow-up.

**Comment by arschles** [comment]
Ok, I'd like the addition of TPR e2e tests to be done very soon. @kibbles-n-bytes are you willing to tackle that right after this PR gets merged?

**Comment by kibbles-n-bytes** [comment]
@arschles Yes, I've been working on it this morning, I should be able to get a PR for that out quickly!

**Comment by arschles** [comment]
@kibbles-n-bytes ok, LGTM3 on this then. I'll merge.

Can you either create an issue for the TPR e2e tests or PR it early (as a WIP) so we can keep track of it?

**Pull request merged**
