### PR TITLE
Remove unused function

### PR DESCRIPTION
**Pull request by carolynvs**

### CODE REVIEW

**Comment by duglin** [comment]
if its not used...
LGTM

**Comment by MHBauer** [comment]
how about these?
```console
$ gometalinter.v2 --disable-all --enable=unused ./pkg/controller
pkg/controller/controller_actions_test.go:46:6:warning: func checkUpdateActionType is unused (U1000) (unused)
pkg/controller/controller_actions_test.go:53:6:warning: type catalogClientAction is unused (U1000) (unused)
pkg/controller/controller_actions_test.go:61:6:warning: func getRuntimeObjectFromUpdateAction is unused (U1000) (unused)
pkg/controller/controller_actions_test.go:75:6:warning: func checkServiceInstance is unused (U1000) (unused)
pkg/controller/controller_actions_test.go:108:6:warning: type instanceDescription is unused (U1000) (unused)
pkg/controller/controller_actions_test.go:150:6:warning: func checkCatalogClientActions is unused (U1000) (unused)
pkg/controller/controller_actions_test.go:172:6:warning: type brokerClientAction is unused (U1000) (unused)
pkg/controller/controller_clusterservicebroker_test.go:66:3:warning: field err is unused (U1000) (unused)
pkg/controller/controller_instance.go:65:2:warning: const errorWithOngoingAsyncOperationMessage is unused (U1000) (unused)
pkg/controller/controller_instance.go:71:2:warning: const errorNonexistentServiceClassMessage is unused (U1000) (unused)
pkg/controller/controller_instance.go:75:2:warning: const errorDeletedClusterServiceClassMessage is unused (U1000) (unused)
pkg/controller/controller_instance.go:77:2:warning: const errorDeletedClusterServicePlanMessage is unused (U1000) (unused)
pkg/controller/controller_instance.go:79:2:warning: const errorDeletedServiceClassMessage is unused (U1000) (unused)
pkg/controller/controller_instance.go:81:2:warning: const errorDeletedServicePlanMessage is unused (U1000) (unused)
pkg/controller/controller_instance.go:85:2:warning: const errorInvalidDeprovisionStatusMessage is unused (U1000) (unused)
pkg/controller/controller_instance.go:1579:6:warning: func newServiceInstanceOrphanMitigationCondition is unused (U1000) (unused)
pkg/controller/controller_test.go:88:2:warning: const testServiceInstanceCredentialSecretName is unused (U1000) (unused)
pkg/controller/controller_test.go:2290:6:warning: func assertClassRemovedFromBrokerCatalogTrue is unused (U1000) (unused)
pkg/controller/controller_test.go:2309:6:warning: func assertPlanRemovedFromBrokerCatalogTrue is unused (U1000) (unused)
pkg/controller/controller_test.go:2360:6:warning: func assertServiceInstanceReadyTrue is unused (U1000) (unused)
pkg/controller/controller_test.go:2418:6:warning: func assertServiceInstanceConditionsCount is unused (U1000) (unused)
pkg/controller/controller_test.go:2520:6:warning: func expectServiceInstanceOrphanMitigationInProgressTrue is unused (U1000) (unused)
pkg/controller/controller_test.go:2524:6:warning: func expectServiceInstanceOrphanMitigationInProgressFalse is unused (U1000) (unused)
pkg/controller/controller_test.go:3029:6:warning: func assertServiceBindingReadyTrue is unused (U1000) (unused)
pkg/controller/controller_test.go:3077:6:warning: func assertServiceBindingReconciliationNotComplete is unused (U1000) (unused)
pkg/controller/controller_test.go:3283:6:warning: func assertServiceBindingErrorFetchingBinding is unused (U1000) (unused)
pkg/controller/controller_test.go:3296:6:warning: func assertServiceBindingErrorInjectingCredentials is unused (U1000) (unused)
pkg/controller/controller_test.go:3374:6:warning: func assertServiceBindingOrphanMitigationFailure is unused (U1000) (unused)
pkg/controller/controller_test.go:3409:6:warning: func assertServiceBindingAsyncOpInProgressFalse is unused (U1000) (unused)
pkg/controller/controller_test.go:3438:6:warning: func assertServiceBindingInProgressPropertiesUnchanged is unused (U1000) (unused)
pkg/controller/controller_test.go:3576:6:warning: func expectNumberOfClusterServiceBrokerActions is unused (U1000) (unused)
```

**Comment by duglin** [comment]
nice tool

**Pull request merged**
