### PR TITLE
Send service_id and plan_id correctly for deprovision

### PR DESCRIPTION
**Pull request by staebler**
Closes https://github.com/kubernetes-incubator/service-catalog/issues/1092

Update the github.com/pmorie/go-open-service-broker-client dependency to the latest version.

### CODE REVIEW

**Comment by MHBauer** [comment]
Any changelog for the update? Features? Bugfixes?

**Comment by staebler** [comment]
This bumps to OSB client to version a15af7d9e6c264f61daf883b78ed3f13a0b53de6.

Changes to OSB:
- Support bearer auth token.
- Fix Deprovision requests so that the service ID and plan ID are sent as query parameters.

**Comment by pmorie** [comment]
cc @robertgmoss

**Comment by MHBauer** [comment]
`Fix Deprovision requests so that the service ID and plan ID are sent as query parameters.`
That's pretty big. 

LGTM, thanks

**Pull request merged**
