### PR TITLE
Add .glide into .gitignore file

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by martinmaly** [comment]
LGTM (`LGTM1` tag applied)

although I do have a question -- in my experience, the `.glide` directory tends to go to `~` so it would seem that its presence in `.gitignore` is noop. Under what circumstances will `glide` put `.glide` in the git client root?

**Comment by duglin** [comment]
I have no idea :-)  I just noticed it in my dir so I assumed it was a normal .glide thing.
Perhaps since I only run it under docker that's the diff?? dunno

**Comment by martinmaly** [comment]
I bet it has to do with the docker build, probably because HOME may not be defined, or defaults to `WORKDIR` or somesuch, so the `.glide` ends up polluting the git client. The more interesting question is - how much of the temporary build artifacts should be reused across containerized builds? and where should such temporary artifacts go?

**Comment by duglin** [comment]
if you're right and its due to the docker build and that stuff is used by glide (the build) then I would think we'd want it to live across docker builds to keep things speedy.

But if the Dockerfile should be tweaked such that these files are put some place else, then I'm ok with that too

**Comment by martinmaly** [comment]
It is good to have a viable theory now where this directory comes from. I am agnostic as to perfect location and I favor making progress. Things can be always improved upon when we get better familiarity with the layout/system/code (so I stand by my lgtm :)

**Comment by arschles** [comment]
@duglin @martinmaly you are both correct. The `.glide` directory is a "global" cache that normally goes in `~` on the host.

When you do a container-based build, `~` is set to the current working directory (set with `-w`) iirc. Thus, the `.glide` dir ends up in the same directory as is mounted to cwd on the host.

I'm with @martinmaly that this is a fine solution. From past experience, I recommend against mounting host directories other than cwd into the container.

LGTM (adding `LGTM2` label)

**Pull request merged**
