### PR TITLE
Remove redundant comments

### PR DESCRIPTION
**Pull request by xichengliudui**
**What this PR does / why we need it**:
The redundant comments were removed

**Which issue(s) this PR fixes** 
Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

### CODE REVIEW

**Comment by xichengliudui** [comment]
I did not find the 'ServiceInstance' function, so I removed it，if you don't need to change it, please let me know. thanks

**Comment by luksa** [comment]
@xichengliudui The comment marks the start of the event handlers & supporting functions in the file. I don't think it should be removed.

**Comment by xichengliudui** [comment]
@luksa  thanks，But we don't have the function 'ServiceInstance'.

**Comment by luksa** [comment]
@xichengliudui That's true, but comments aren't used only for documenting functions. In this case, the comment line is used to mark the beginning of a group of functions (those that deal with event handling and the control-loop function). Usually, section headings like this are not just single-line comments, but more like this:
```
///////////////////////////////////////////////////////////////////////
// ServiceInstance handlers and control-loop
///////////////////////////////////////////////////////////////////////
```

**Pull request closed without merging**
