### PR TITLE
WIP: Make fake broker act like an OSB broker

### PR DESCRIPTION
**Pull request by pmorie**
🚧 WIP 🚧 

The OSB fake server should:

1.  Correctly implement the OSB API
2.  Allow you to record a set of reactions for different instances/bindings
3.  Allow you to make assertions on the expected actions that should have happened to the fake

### CODE REVIEW

**Comment by pmorie** [comment]
Still has a ton of work left, keep in mind if doing review.

**Comment by pmorie** [comment]
I doubt that I'm going to get back to this before kubecon.

**Comment by pmorie** [comment]
This will not be done for 0.0.2

**Comment by pmorie** [comment]
Moving to next alpha release.  Someone besides me probably needs to own this.

**Comment by arschles** [comment]
@pmorie what is the status of this PR?

**Comment by pmorie** [comment]
@arschles Someone else needs to adopt it.  It might be a good place for someone new to get started.  I'm going to make an issue for this and probably close this PR.

**Comment by pmorie** [comment]
I'm closing this now.  I will probably spin this into a separate repo.

**Pull request closed without merging**
