### PR TITLE
Add an emptyDir for etcd in the helm chart

### PR DESCRIPTION
**Pull request by jwforres**
so that etcd won't try to mkdir its own data dir

### CODE REVIEW

**Comment by jwforres** [comment]
@pmorie

**Comment by duglin** [comment]
Seems ok - but what's wrong with it creating it owns data dir? Isn't it just as ephemeral in both cases?

**Comment by duglin** [comment]
LGTM

**Comment by jwforres** [comment]
Yeah its still ephemeral. Depending on the user/permissions/capabilities
that container is running under the etcd process may not be able to mkdir,
which is what I hit in my env.

**Comment by duglin** [comment]
Now you got me curious. W/o the mention of "user" in the yaml won't it always run as the same user in all cases (and I presume 'root') ? In what cases was it different for you?

**Comment by jwforres** [comment]
I was running within openshift which does affect what uid the container is
running as.  I didn't dig too far into what the specific problem was
@pmorie might have a better idea.

**Comment by duglin** [comment]
sounds like an openshift issue to me :-) LOL

**Comment by arschles** [comment]
I don't have time to test this right now, so I trust that it has been already (not sure if CI does it for us). LGTM, merging

**Pull request merged**
