### PR TITLE
Extracting common plan spec into embeddable struct

### PR DESCRIPTION
**Pull request by jeremyrickard**
As part of the Prosopal for Namespaced Resources (#1826), this extracts the common elements from the ClusterServicePlanSpec into a SharedServicePlanSpec that can be embedded in both the ClusterServicePlanSpec and a new name-spaced ServicePlan resource (to be created). ~~Additionally, ClusterServicePlanStatus got the same treatment for later re-use in a ServicePlanStatus for namespaced plans.~~

This is limited to just the refactor of the existing ClusterServicePlanSpec ~~and ClusterServicePlanStatus~~ in the two types.go files and the related struct literals in the supporting tests.

### CODE REVIEW

**Comment by jeremyrickard** [comment]
@pmorie and @eriknelson here is a PR to handle the ClusterServicePlanSpec changes.

**Comment by eriknelson** [comment]
Thanks! Will take a look soon.

**Comment by jeremyrickard** [comment]
@eriknelson yeah I think they should! Forgot to update that, thanks for catching that. Updated the PR.

**Comment by jboyd01** [comment]
Changes look good although this is getting travis failures in the same test but different test cases.  The previous travis run failed here

    --- FAIL: TestBasicFlows/**async_instances_and_bindings** (40.34s)
    	framework.go:81: Starting server on port: 16155
    	controller_test.go:730: controller start
    	controller_test.go:742: informers start
    	controller_test.go:989: error waiting for binding condition: timed out waiting for the condition
    		expecting: {Type:Ready Status:True LastTransitionTime:0001-01-01 00:00:00 +0000 UTC Reason: Message:}
    		last seen: &{Type:Ready Status:False LastTransitionTime:2018-03-15 02:31:17 +0000 UTC Reason:Binding Message:The binding is being created asynchronously}
    	framework.go:77: Shutting down server on port: 16155


but now I see its failing here:

  --- FAIL: TestBasicFlows/**async_bindings** (38.50s)
    	framework.go:81: Starting server on port: 1973
    	controller_test.go:730: controller start
    	controller_test.go:742: informers start
    	controller_test.go:989: error waiting for binding condition: timed out waiting for the condition
    		expecting: {Type:Ready Status:True LastTransitionTime:0001-01-01 00:00:00 +0000 UTC Reason: Message:}
    		last seen: &{Type:Ready Status:False LastTransitionTime:2018-03-15 15:26:53 +0000 UTC Reason:Binding Message:The binding is being created asynchronously}
    	framework.go:77: Shutting down server on port: 1973

**Comment by jeremyrickard** [comment]
@jboyd01 yeah I see that :(  

Do you think it's related to this change? The integration tests run locally for me. I'll take a look at this again.

**Comment by jboyd01** [comment]
@jeremyrickard I'll take another look after lunch, but I didn't see the issue with initial review.  I thought it was a flake 'till the second test came up with a failure.

**Comment by n3wscott** [comment]
Same question for this one: 

I understand that you are using the word shared to mean objects shared between ClusterServiceClass and ServiceClass, but I am wondering if in a world where there is a CluserServiceClass and ServiceClass, could there also be something called SharedServiceClass as an object that has a link between the two?

Obvious choices are:

shared
common
base
core

If we are working on this area, perhaps we also consolidate the overlapping Class/Plan spec properties into a class like, CoreServiceSpec (or SharedServiceSpec)

I fear not liking Shared is a bit of a bikeshed but as I read the code I constantly wonder what the CluserServiceClass is being shared with and that is the twitch I am commenting about...

**Comment by jeremyrickard** [comment]
@n3wscott I think I like "Common....." or more than "Shared....." if we're going to change. Common.... conveys the meaning of what they are (common attributes). This and the other PR used the names from the proposal (#1826), so that's why it's "Shared"  right now. I can go either way, but if we change I'd vote for common.

**Comment by n3wscott** [comment]
> so that's why it's "Shared" right now

I just wanted to say something before we get too deep into the refactor...

**Comment by arschles** [comment]
So the jenkins job passed. I've restarted the travis job one last time to make really extra sure the failure is not a flake.

**Comment by n3wscott** [comment]
Looks to be a flake on:

    --- FAIL: TestBasicFlows/async_bindings (37.22s)
    	framework.go:81: Starting server on port: 27363
    	controller_test.go:730: controller start
    	controller_test.go:742: informers start
    	controller_test.go:989: error waiting for binding condition: timed out waiting for the condition
    		expecting: {Type:Ready Status:True LastTransitionTime:0001-01-01 00:00:00 +0000 UTC Reason: Message:}
    		last seen: &{Type:Ready Status:False LastTransitionTime:2018-03-15 17:43:49 +0000 UTC Reason:Binding

**Comment by jeremyrickard** [comment]
I reverted this back to the prior commit that had passed and it just passed CI. I'll handle the change the status object in another PR.

**Comment by eriknelson** [comment]
@jeremyrickard I'm thinking I'll probably do the same. I don't have the status change in the broker PR or the serviceclass PR, and haven't seen any integration hiccups. Also want to confirm wrapping those shared status objects is indeed the direction we want to go.

**Pull request merged**
