### PR TITLE
Removing the test-apiserver script

### PR DESCRIPTION
**Pull request by arschles**
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/842

### CODE REVIEW

**Comment by MHBauer** [comment]
I missed commentary on 842.

Why remove this? It's the only thing we have that tests that kubectl talks to our apiserver. Is it taking to long to run? I think it is a good sanity test.

It's an integration test because it checks contact between kubectl and the apiserver. It does not rely on the controller or core kube apiserver..

If we are deciding to remove this you need remove all of the kubectl stuff as well.

**Comment by duglin** [comment]
I was told we have other tests that do this stuff.  If that's not true then I agree, we shouldn't remove it. @pmorie which tests did you say covered this?

**Comment by arschles** [comment]
@duglin @MHBauer see `clientset_test.go`

**Comment by pmorie** [comment]
Yeah, I view this as basically the same as clientset_test.go

> If we are deciding to remove this you need remove all of the kubectl stuff as well.

Which stuff did you mean, @MHBauer?

**Comment by pmorie** [comment]
Nevermind, @arschles you do need to remove all the scripting around kubectl in this PR.

**Comment by MHBauer** [comment]
That's testing our client, not kubectl. I like ensuring the compatibility with straight kubectl. I don't understand what problem or maintenance burden we're trying to solve.

**Comment by MHBauer** [comment]
Side issue: Do we intend to test the kubectl plugins when they exist? I think we will need something like this test, but with the plugins installed. I do still want to also make sure we're usable without plugins.

**Comment by duglin** [comment]
If we don't have tests that hit the apiserver from kubectl then I'd like to keep these because that's the end user experience of it and I'd like verification that it will continue to work for 'em.

**Comment by arschles** [comment]
Moving to 0.1.0, as this is not yet finished

**Comment by arschles** [comment]
I'm closing this in favor of keeping the script that exercises `kubectl`

**Pull request closed without merging**
