### PR TITLE
WIP: Add metadata types / refactor API types

### PR DESCRIPTION
**Pull request by pmorie**
Adds:

- Specific types for various kinds of metadata
- Narrower scope which is more usable for parameters fields
- Types that hold OSB-specific fields for all resources

Just submitting the type changes for now.  Obviously this will create changes throughout the codebase which I will make once we have agreed on the API changes.

Fixes: #218 #270

### CODE REVIEW

**Comment by duglin** [comment]
I have mixed feelings about this.

On the one hand the idea of defining these fields in a less OSBAPI way feels good because it means we're not as tied to that one API.  But on the other hand, it feels like we're encouraging changes that are not tied to "the API". Or put another way, does trying to hide the fact we're OSBAPI-compliant encourage us to go beyond, or differ from, the spec we're trying to gain interop around? 

In one respect you can look at this as just a syntax change, dropping the "OSB" letters from properties and defining logical groupings/structs for them, but one nice thing about having them in their current form is that it makes it clear which things are part of the spec we're following and which are extensions/differences. It also makes it easier for newbies to see how this relates to the spec we're adhering to. This PR forces a mapping (not just in words but in type structures) for them, and I'm not sure what the benefit is for our end-user's understanding.

If we had other APIs we wanted to support immediately then this would be an easier thing to accept.

Just pondering...

**Comment by pmorie** [comment]
Yep, no rush to get this in. I had actually wanted to just wanted to get metadata types in and all of this wound up happening.  If we don't like it I can trim a bunch of this stuff back out (tig status ftw).

Another API I coukd see us implementing (but don't know enough about it yet to understand how good of a fit it is from an API perspective) is [APS](https://apsstandard.org/).  I have no immdiate plans to implement any other APIs but I think it would be b st to avoid thinking of our API as just a twin to OSB. I think we should give ourselves the latitude to do what makes sense for us rather than being constrained by how the OSB currently is. I also think that certain parts of the OSB API are very un-kube andl that we need to adapt them into a k8s-like API for things to make sense to users that don't and won't know about the implementation details of the OSB API.

I did try to split into subtypes based on the fields that I felt were more 'universal' (example: 'tags') and which were obviously only artifacts of the OSB API (max db per node). The feeling I had while doing that is that it is an incremental improvement and we might wind up doing another refactoring later. We do have that capability, because this is an alpha API.

**Comment by pmorie** [comment]
Btw @duglin how did you feel about the metadata fields? If you like thise, i can pull them into another less intrusive PR.

**Comment by pmorie** [comment]
After talking with @duglin this morning, I'm going to close this PR and add some flat fields for metadata for now.  We can iterate to find the right factoring as we go.

For the record this is basically an opinionated idea for what the right decomposition of objects is into 'universal' fields and fields which are very specific to the OSB API.

**Pull request closed without merging**
