### PR TITLE
add TPR, cleanup support to walkthrough e2e script

### PR DESCRIPTION
**Pull request by kibbles-n-bytes**
1) Now `test_walkthrough.sh` will use a tpr-backed API server if you pass in `--with-tpr`.
2) `--cleanup` will get rid of all resources spun up during walkthrough.

Although the output is still quite ugly, this allows for people to test the walkthrough easily on their local machine.

~~Jenkins will still only run the etcd-based walkthrough; there is an issue outstanding ( #600 ) that prevents the deletion of TPR resources.~~
**EDIT**: Now Jenkins will run the tests on a TPR-based walkthrough as well up until deletion, and then hackily deletes the resources manually.

Closes: #632

### CODE REVIEW

**Comment by arschles** [comment]
@kibbles-n-bytes you could use the workaround described at https://github.com/kubernetes-incubator/service-catalog/issues/600#issuecomment-288524199 to do TPR cleanup here

**Comment by arschles** [comment]
@kibbles-n-bytes should this be labelled `jenkins`?

**Comment by kibbles-n-bytes** [comment]
@arschles To your second question, not the way the label was intended. The label was supposed to be a trigger for Jenkins to run on a build, but I've changed this. See my response on #591 . That means the Jenkins label now has no purpose, though *could* be used for Jenkins-specific changes (I suppose any edits of the Jenkinsfile?), but I think just using the `testing` label is enough. This PR is more meant for non-Jenkins use of the `test_walkthrough.sh` script anyway.

For the first question, I'll try it out!

**Comment by kibbles-n-bytes** [comment]
Part of the changes here will fix #632 .

**Comment by duglin** [comment]
LGTM

**Pull request merged**
