### PR TITLE
Fix svcat create class

### PR DESCRIPTION
**Pull request by carolynvs**
This PR is a 
 - [ ] Feature Implementation
 - [x] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:

```console
$ svcat create class custom-mysql --from mysql --scope cluster
Error: unable to create cluster service class (resourceVersion should not be set on objects to be created)
```

While I was in here I fixed the following:
* Disallow all scope for create class
* Copy just the spec when creating a new class (this fixes the error above). 
* Set both the k8s name _and_ the external name when copying a class, because svcat displays external name, not k8s name (because k8s names for service catalog resources are usually unreadable).

**Which issue(s) this PR fixes** 

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
- [ ] Tests
- [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by shubheksha** [comment]
@carolynvs, would it make sense to fix the methods touched in this PR to accept Class instead of ClusterServiceClass?

**Comment by carolynvs** [comment]
@shubheksha I'm confused about which methods you mean? But in general, no it would be better in a follow-on PR, since that's not related to fixing `svcat create class`. 😀

**Comment by carolynvs** [comment]
/assign @jboyd01

Hey Jay, this slipped through when I first reviewed this feature. Like I forgot that svcat does some funny things (displaying the external name) because the k8s name is unreadable. 😝 

Can you please take a look and maybe try it out yourself with svcat?

**Comment by jboyd01** [comment]
This looks good and correct, I took it for a test drive and it handled well.  One thing that might be worth wider discussion is the externalID (today we set the new class's externalID = the source class's externalID).  I think we have other prs/discussions about externalID should be unique.  But discussing with @carolynvs I understand this is intentional as the broker wouldn't know what service this is about.  More discussion to follow.
/lgtm

**Comment by carolynvs** [comment]
/assign @jberkhahn 

Would you please take a look at this too? I want to make sure we've ironed out the problems before we copy the implementation for create plan.

**Comment by jberkhahn** [comment]
So, I think it's a little weird that if you try to make a namespaced class out of a cluster scoped class or vice versa the error you get is "class foobar not found".

other than that it looks ok.

**Comment by carolynvs** [comment]
> I think it's a little weird that if you try to make a namespaced class out of a cluster scoped class or vice versa the error you get is "class foobar not found". 

@jberkhahn Agreed, the UX around changing the scope of resource when copying it isn't great. Would you like to open an issue and we can brainstorm on how to improve it?

**Comment by carolynvs** [comment]
Can I get an `/approve` from one of the other maintainers? @jboyd01 @jberkhahn  Or is there more that needs to change in this PR?

**Pull request merged**
