### PR TITLE
Make Parameters fields optional in the API

### PR DESCRIPTION
**Pull request by pmorie**
A couple issues:

- These fields lacked json tags in the versioned API; created https://github.com/kubernetes-incubator/service-catalog/issues/446 to add a verify script to catch these
- These fields should be pointers, so that we can distinguish unset from empty values correctly

### CODE REVIEW

**Comment by duglin** [comment]
Any chance of getting some tests for this as part of this PR?

**Comment by duglin** [comment]
nvm

**Comment by duglin** [comment]
LGTM

**Comment by pmorie** [comment]
@duglin @vaikas-google this addresses one of doug's things from #415

**Comment by vaikas-google** [comment]
LGTM

**Pull request merged**
