### PR TITLE
on release, also push images tagged as 'latest'

### PR DESCRIPTION
**Pull request by krancour**
Upon merge or release, in addition to immutable images, we also push mutable images tagged as `canary` (instead of `latest`). If I understand correctly, this is because we don't want anyone to ever mistake an image built from the head of master for something that has been formally released / is production-worthy. Contrary to `latest`, `canary` (evoking the trope of a canary in a coal mine) more than adequately conveys the risk inherent in using an image tagged as such.

That's all well and good... but we've had a few releases now and are approaching GA and still have never pushed any images tagged `latest`-- and I do think that defies convention. i.e. Even if we don't like or encourage the use of mutable images, the widespread convention is _still_ that images of the latest stable release are tagged as such.

This PR fixes that. When we tag a release in git, which results (as before) in pushing an immutable image tagged with the git tag, we will _also_ (as before) push a mutable image, but (unlike before) that mutable image will be tagged with `latest` instead of `canary`.

To proactively address some possible dissent...

I debated with myself for a while whether this was a good idea or not. Does the mere availability of an image tagged `latest` not encourage the anti-pattern of _using_ a mutable image? And it may. I would _not_ open this PR if not for the fact that we _already_ produce a mutable image tagged as `canary`. If someone is intent on living dangerously and the _only_ mutable image available is `canary`... yikes. Pushing _stable_ images tagged as `latest` provides such daredevils with a moderately safer alternative. This is how I rationalized this to myself.

I'm more than willing to hear arguments against this.

### CODE REVIEW

**Comment by MHBauer** [comment]
What is `mutable image`?

**Comment by krancour** [comment]
@MHBauer a "mutable image" is an image that, once created, isn't set in stone. It is, conceivably, routinely updated. `latest` is the canonical example of a mutable image. It does not refer to a specific version. It refers to the _latest_ (stable, ideally) version. That means that what version you get varies based on when you pull it. This non-deterministic behavior is the impetus for it being generally discouraged to _use_ mutable images.

Our image tagged as `canary` represents just such a "moving target." It always represents an image built from the (current) head of master. Pull it today and you get one thing. Pull it tomorrow and you get something else.

What everything boils down to here is if we're going to publish mutable images _at all_, we should provide one that is more stable than what's in the head of master. i.e. `canary` is all well and good,  but we should have `latest` point to the latest _release_.

**Comment by MHBauer** [comment]
Okay, we're talking about the tags, not the images.

**Comment by krancour** [comment]
Perhaps it is semantically incorrect for me to say "mutable (or immutable) _image_." Regardless, it would seem we're on the same page in terms of understanding this now?

**Comment by MHBauer** [comment]
Once you described it, yes.

**Comment by arschles** [comment]
@krancour I am good with this. tag releases are as stable as we get (right now), so it makes sense for `latest` to have `latest` represent the last stable

**Comment by duglin** [comment]
LGTM

**Comment by duglin** [comment]
just waiting for CI

**Pull request merged**
