### PR TITLE
Decompose controller unit tests

### PR DESCRIPTION
**Pull request by pmorie**
Follow up to #893; decomposes the controller unit tests into appropriately named `controller_*_test.go` files.

### CODE REVIEW

**Comment by MHBauer** [comment]
Travis says the boilerplate is wrong somehow, but otherwise I trust it's done right.

**Comment by pmorie** [comment]
Dang

**Comment by pmorie** [comment]
Fixed

**Comment by blacksagi** [comment]
Black1885sagi

**Comment by vaikas-google** [comment]
Changes look fine, just curious about the names for the tests having the controller_ prefix in everything. since they live in controller/*** Seems like the controller_ prefix is redundant. But I don't feel super strongly about it.

**Pull request merged**
