### PR TITLE
update approvers

### PR DESCRIPTION
**Pull request by jboyd01**
added jboyd01, kibbles-n-bytes, nilebox, staebler

### CODE REVIEW

**Comment by jpeeler** [comment]
/lgtm
will it automatically put the label on?

**Comment by MHBauer** [comment]
Can we put people in more specific places? It'd be nice to have experts on the specific areas vs "WHOLE REPO".

Lately I don't see a lot of reviews happening from most of these people.

**Comment by MHBauer** [comment]
To clarify, in historical relevance these people are all great. We have to realize that putting them in this list means they're going to be called by the bot to do things. So if they're not doing things now, what goal are we trying to achieve? I'd be more accepting of this if there were more OWNERS on sub-directories.

**Comment by jboyd01** [comment]
@MHBauer  You raise a good point about the bot using the names to assign people for review.  With this update I was approaching it from we want these developers to be able to approve PRs when they do make time to work on Catalog, not necessarily be assigned to review work.

Let's say we have a developer who is a Service Catalog veteran and long proven code submitter & approver but currently is focused on other work and only occasionally has time to work on Catalog.  If they aren't an approver in OWNERS, prow will not use their /LGTM to move the PR forward, right?  If they manually add a LGTM1 or LGTM2 label will that satisfy the prow workflow?  My point here is it would be a shame to turn our back on qualified reviewers when they do have time to participate.  If the labels still work, I'm all for leaving them out of OWNERS and documenting how they must interact with the workflow.

**Comment by carolynvs** [comment]
I would like to add people who should be able to perform the new prow actions so that they aren't accidentally locked out as Jay said.

I would also like to see us get more sub-owners defined in directories because right now people who aren't the right reviewers are being autoassigned by prow and it's really annoying.

I'm going to merge this and then do a follow-up PR to try to fix point #2.

**Pull request merged**
