### PR TITLE
Improve logging in walkthrough tests

### PR DESCRIPTION
**Pull request by kibbles-n-bytes**
1) Removes the `set -x` debug flag in `test_walkthrough.sh` and adds more useful printed logs
2) Artifacts the deployment/pod descriptions and container logs for apiserver and controller-manager in Jenkins

### CODE REVIEW

**Comment by MHBauer** [comment]
What are artifacts?

**Comment by kibbles-n-bytes** [comment]
@MHBauer Persisted files after the build finishes. So in this case, I'm recording logs for the deployments/pods/containers and saving them as separate files so as to not clutter up the overall build log with too much information.

You should be able to see these files by following the "Details" link on the Jenkins build. So for instance, for this build here: https://service-catalog-jenkins.appspot.com/job/service-catalog-PR-testing2/262/

Hopefully there should be a "Build Artifacts" section in the middle area with a bunch of log files.

**Comment by MHBauer** [comment]
Cool. Looks helpful.

**Comment by arschles** [comment]
Adding this to 0.0.3, since it helps with flakes

**Pull request merged**
