### PR TITLE
Removing trailing slashes from broker server URLs

### PR DESCRIPTION
**Pull request by arschles**
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/567

### CODE REVIEW

**Comment by duglin** [comment]
LGTM if CI if ok

**Comment by kibbles-n-bytes** [comment]
LGTM

**Comment by simonleung8** [comment]
Both code and test LGTM

**Comment by MHBauer** [comment]
looks fine as long as we construct using the format strings.

**Comment by arschles** [comment]
I've merged this, as it closes a MVP 2 blocking bug

**Pull request merged**
