### PR TITLE
Update to osb client 0.0.10

### PR DESCRIPTION
**Pull request by n3wscott**

### CODE REVIEW

**Comment by MHBauer** [comment]
done in #1901

**Comment by nilebox** [comment]
@MHBauer I prefer this PR to be merged and #1901 to be rebased after that, as these changes are independent.

**Comment by nilebox** [comment]
LGTM.

**Comment by jboyd01** [comment]
LGTM

**Comment by MHBauer** [comment]
@nilebox okay. trying to drive reviews to #1901 to get it merged.

**Pull request merged**
