### PR TITLE
fix func comment problem

### PR DESCRIPTION
**Pull request by shouhong**
This PR is a 
 - [ ] Feature Implementation
 - [X] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**: fix func comment problem

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by MHBauer** [comment]
/hold
merge with  #2497

**Comment by jboyd01** [comment]
@shouhong Thanks for the PR.  I'm merging this, in the future it would be best to combine these simple typo fixes into a single larger PR if you would, it will reduce the amount of time folks have to spend reviewing.  Thanks!

**Pull request merged**
