### PR TITLE
Add a travis badge

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by martinmaly** [comment]
Love it! LGTM

**Comment by krancour** [comment]
Veto. There is a more canonical means of doing this with markdown without falling back on HTML.

```
[![Build Status](https://travis-ci.org/kubernetes-incubator/service-catalog.svg?branch=master)](https://travis-ci.org/kubernetes-incubator/service-catalog)
```

**Comment by duglin** [comment]
@krancour doi - forgot about that - thanks - fixed

**Comment by krancour** [comment]
Thanks @duglin. Veto rescinded. Before I LGTM, however, can I suggest that this badge should move _below_ the heading? That seems to be where various status badges are placed for the majority of projects I have looked at, not the least of which is k8s itself.

**Comment by duglin** [comment]
yup moved!!

**Comment by arschles** [comment]
LGTM

**Comment by krancour** [comment]
@duglin thanks for making both changes! My LGTM doesn't count since @arschles beat me to it and we both represent Deis, but I wanted to say thank you for the changes nonetheless. 👍

**Comment by pmorie** [comment]
LGTM, merging.

**Pull request merged**
