### PR TITLE
Remove consuming service instance stuff.

### PR DESCRIPTION
**Pull request by bmelville**
Now that bindings are consumed natively in kubernetes, these service instances which previously consumed bindings are no longer relevant.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by pmorie** [comment]
@bmelville can I get a description on this PR for posterity?

**Comment by bmelville** [comment]
Done thanks.

**Comment by bmelville** [comment]
@mkibbe1993 

Hey Michael, how does this and the lack of consuming instances affect the test stuff we've gotten set up?

**Comment by pmorie** [comment]
@arschles @krancour can we get review on this one closed out?

**Comment by arschles** [comment]
LGTM, merging

**Pull request merged**
