### PR TITLE
Stop Kubernetes resource leak and refactor wait loops.

### PR DESCRIPTION
**Pull request by mkibbe1993**
Change-Id: Ide00e8b8bfb469711efdeb0a227cc661677771d8

### CODE REVIEW

**Comment by martinmaly** [comment]
Folks, this is first of the series of commits that will enable using Jenkins for e2e tests with service-catalog repo, as we discussed on slack.

**Comment by martinmaly** [comment]
LGTM (`LGTM1` label added)

**Comment by arschles** [comment]
There's some serious bash-fu in here, but it all looks reasonable. I'm assuming this is some setup for e2e tests?

LGTM (`LGTM2` label added)

**Comment by martinmaly** [comment]
:) bash-fu. Correct, this is all to enable e2e tests and fail-fast mode (verify things are spinning up correctly so we detect failure as soon as possible, rather than emitting "fail" at the end without much detail).

**Comment by duglin** [comment]
@mkibbe1993 please put more descriptive text in your PR.  Comments like https://github.com/kubernetes-incubator/service-catalog/pull/108#issue-193586051 don't really mean anything.

**Comment by duglin** [comment]
gonna trust that this works since I can't test it locally.

LGTM

**Comment by mkibbe1993** [comment]
Whoops, sorry about that @duglin , that's an artifact of the way our version control system here works that I didn't notice had slipped through on my commits. Didn't mean to include that!

**Pull request merged**
