### PR TITLE
Remove prototype controller

### LINKED ISSUE #482: [Meta] Remove the "old" controller
The "new" controller is in `./pkg/controller/wip`, and it will be fully functional after https://github.com/kubernetes-incubator/service-catalog/pull/403 is in. The old controller code should be removed and the `controller/wip` code should be moved under `./pkg/controller`.

Along with this change, any applicable documentation and the `./deploy/catalog` chart, which is outdated, should be updated.

List of TODOs mentioned above:

- [x] Remove the old controller code (#486)
- [x] Move the wip controller code into `./pkg/controller` (https://github.com/kubernetes-incubator/service-catalog/pull/495)
- [x] Remove the `./deploy/catalog` helm chart and rename the `./deploy/wip-catalog` chart to `./deploy/catalog` #503 
- [ ] Update any necessary docs

Requires #403

### PR DESCRIPTION
**Pull request by pmorie**
Removes the prototype controller and associated bits.

Depends on #485 

First of a series that closes #482

### CODE REVIEW

**Comment by pmorie** [comment]
One unanticipated effect of this: the Makefile is significantly easier to understand.

**Comment by pmorie** [comment]
@arschles 

> LGTM. Are you going to move the stuff in ./pkg/controller/wip out of the wip folder in a separate PR? If so, this one shouldn't close #482

Yep, I still have follow-ups to do to get all of the old code out, this is the biggest chunk, though.  Updated PR description to reflect that.

**Comment by arschles** [comment]
@pmorie thanks!

**Comment by vaikas-google** [comment]
This also removes the 'batteries included' broker, what's the reasoning for that? There should be a way to remove the controller without removing, say registry.

**Comment by pmorie** [comment]
@vaikas-google I didn't think the registry had a purpose if the prototype controller was removed.  Maybe I'm unclear on what it does?

**Comment by vaikas-google** [comment]
Registry has metadata about helm charts that make them suitable for being brokered through k8s broker.

**Comment by arschles** [comment]
@vaikas-google and I talked on a DM session. Below are details on the registry along with my opinion.

The registry is a metadata storage system for the helm based broker. The broker looks in this store to determine which helm charts it knows about, and where they are (i.e. where is the helm chart repository). If you run a helm broker, you can update its registry to add a new provisionable helm chart.

I think we should keep the registry and its associated helm broker but not in this repository. @vaikas-google I believe that now is the time to pull it and the helm broker into a new repository. Can you do that? We should plan to bring it and other brokers together in the future.

**Comment by vaikas-google** [comment]
If we think it's useful, then it should be pulled into a separate PR where somebody can easily figure out the pieces that need to be recreated. But, if we just need a rubberstamp to make progress, I'll do that.

**Comment by duglin** [comment]
LGTM

**Comment by pmorie** [comment]
> If we think it's useful, then it should be pulled into a separate PR where somebody can easily figure out the pieces that need to be recreated. But, if we just need a rubberstamp to make progress, I'll do that.

Thanks for understanding - I actually had thought that this was part of the TPR prototype.  I think this would be useful independently and would support it having a life of its own in another repo.

**Pull request merged**
