### PR TITLE
don't list plans twice (svcat describe class --traverse)

### PR DESCRIPTION
**Pull request by jboyd01**
When you describe a class with --traverse option, the plans are listed twice:
```console
$ svcat describe class user-provided-service --traverse     
  Name:          user-provided-service                 
  Description:   A user provided service               
  UUID:          4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468  
  Status:        Deprecated                            
  Tags:                                                
  Broker:        ups-broker                            

Plans:
   NAME           DESCRIPTION        
+---------+-------------------------+
  default   Sample plan description  

Broker:
  Name:     ups-broker  
  Status:   Ready       

Plans:
   NAME           DESCRIPTION        
+---------+-------------------------+
  default   Sample plan description  
```

### CODE REVIEW

**Comment by jberkhahn** [comment]
Seems simple enough. 

Are we sure that we always want to print the plans? At that point, traverse is only adding the broker information. I think you might want to remove the line that always prints the plans, and leave the line in the traverse loop.

See (here)[https://github.com/jboyd01/service-catalog/blob/8b5c41c80c84d795cdb6965c6de2f400454d95ea/cmd/svcat/plan/describe_cmd.go#L131] for how we do it in `svcat describe plan`

**Comment by jboyd01** [comment]
Good point @jberkhahn.  I've moved the printing of plans down to the traverse section before the broker details (I think order is best to keep the plan before broker).

example output now:
```console
$ svcat describe class dh-hello-world-apb 
  Name:          dh-hello-world-apb                   
  Description:   deploys hello-world web application  
  UUID:          9f7da06f179b895a8ee5f9a3ce4af7ef     
  Status:        Active                               
  Tags:                                               
  Broker:        ansible-service-broker               

$ svcat describe class dh-hello-world-apb  --traverse
  Name:          dh-hello-world-apb                   
  Description:   deploys hello-world web application  
  UUID:          9f7da06f179b895a8ee5f9a3ce4af7ef     
  Status:        Active                               
  Tags:                                               
  Broker:        ansible-service-broker               

Plans:
   NAME              DESCRIPTION            
+---------+--------------------------------+
  default   A sample APB which deploys      
            Hello World                     

Broker:
  Name:     ansible-service-broker  
  Status:   Ready   
```

**Comment by carolynvs** [comment]
Nice catch!

I would strongly prefer that either a) we get rid of traverse altogether since I'm not sure it provides value or b) always show plans when describing a class and don't double show them when --traverse is specified.

The reason why plans are displayed by default is that it's the more common use case for that command and I wanted to show useful information by default, instead of hiding it behind a flag.

What do you think?

**Comment by jboyd01** [comment]
The class and plans do go hand in hand....  I can see reason to include it.  Yet, the command says show me the class, not the class and plans.  And wouldn't the describe plan duplicate the plan details we include in the describe class?  Not that there is anything wrong with multiple ways to get the same info...

I'd kind of like a svcat show-me-everything ordered by broker -> class -> plans, but that is beside the point.  I guess I was thinking I don't see much use of traverse.

**Comment by jberkhahn** [comment]
Now that I think about it, I think it would make the most sense to remove the traverse flag entirely and just show the plan names by default. If the user wants more info on plan foo, they can get plans foo.

Also, how are you even supposed to know the traverse flag exists? It doesn't show up when i `svcat get classes -h`

**Comment by jboyd01** [comment]
ok, I'm on it, will remove traverse

**Pull request merged**
