### PR TITLE
Change the image versions from :canary to :v0.0.3

### PR DESCRIPTION
**Pull request by vaikas-google**

### CODE REVIEW

**Comment by pmorie** [comment]
I don't think we should need this - we could do a 0.0.3-1 milestone

**Comment by MHBauer** [comment]
I don't understand why we need one vs the other to be able to comment on this.

**Comment by arschles** [comment]
what's wrong with this @pmorie ?

@MHBauer this is to pin the walkthrough to a stable release rather than the tip of master at all times. I've made the decision to do so

**Comment by pmorie** [comment]
Completely misread this, lgtm

**Comment by pmorie** [comment]
We should bump this every release IMO

**Comment by vaikas-google** [comment]
@pmorie that's what I thought and hence was surprised to find it set to :canary and not to say: v0.0.2

**Comment by arschles** [comment]
The wiki document instructs to bump it every release, however this is the first release that the instructions were in place 😄

**Pull request merged**
