### PR TITLE
Move Jenkins files

### PR DESCRIPTION
**Pull request by mkibbe1993**
Moves the Jenkins-related files in `contrib/hack/` to `contrib/jenkins`.

Closes: #137

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

thanks. A step in the right direction IMO.
Do you happen to know about some of the other scripts - like run.sh, or hack/cleanup.sh ?  They don't look like jenkins stuff, they look more like helper tools for standing up and playing with an env, but I don't see much in the way of docs around them. So I'm inclined to delete them until we have docs that explain how people are supposed to use them. Anyone know?

**Comment by rifung** [comment]
@mkibbe1993 would know more but I remember him telling me to use cleanup.sh to clean up my GKE environment because previously there were some things that would leak if you just removed the cluster manually.

**Comment by mkibbe1993** [comment]
@duglin `run.sh` was used before to stand up the demo project when the main way to run it was to run the controller/registry/broker binaries on your local machine. Can be moved to `hack/`, or possibly deleted if we're no longer interested in running binaries locally. `cleanup.sh` I hadn't looked at before, but it cleans up the resources added when going through the demo, and does it nicer than the way I explicitly name things in `hack/jenkins/cluster_utilities.sh`. I will probably take that code, consolidate it into my script, and then delete that file.

@rifung That was cleanup_cluster.sh, whose main usage is in Jenkins but also provides us a helpful way to also cleanup our GKE environment without having to do it manually. The naming similarity is an unfortunate coincidence.

**Comment by mkibbe1993** [comment]
To be honest, I feel it makes more sense to move most of these files into something like `hack/demo`; the scripts do not rely on the Jenkins environment, and though they were designed with Jenkins in mind, they can be used (and I have used them many times) locally as well.

**Comment by krancour** [comment]
Cross posting a comment I made on #211:

https://github.com/kubernetes-incubator/service-catalog/pull/211#issuecomment-271584570

> If I can suggest an alternative to the `hack/jenkins` directory that @duglin proposed, please consider `contrib/hack/jenkins`... my rationale is that I think everything that is non-vital should live somewhere under `contrib` such that (if for some imaginative reason) we ever deleted `contrib`, build/test would still pass _and_ we wouldn't be left with a bunch dead code and scripts in `hack/...` or elsewhere.

**Comment by pmorie** [comment]
> To be honest, I feel it makes more sense to move most of these files into something like hack/demo; the scripts do not rely on the Jenkins environment, and though they were designed with Jenkins in mind, they can be used (and I have used them many times) locally as well. Jenkins just needed automated scripts that followed the walkthrough demo to a tee.

If it's not for Jenkins, let's not name it that way.  I would rather have Jenkins run something named as `demo` than demo something named as `Jenkins`.

**Comment by duglin** [comment]
rebase needed

**Comment by mkibbe1993** [comment]
> If it's not for Jenkins, let's not name it that way. I would rather have Jenkins run something named as demo than demo something named as Jenkins.

Actually, rethinking about it, I think it's okay for now. The scripts there are "general use", but quite user unfriendly and undocumented. For the time being, let's put them in `hack/jenkins` and I can revisit them and make them more robust in the future should the desire arise.

**Comment by krancour** [comment]
Any reason this stuff isn't going under contrib somewhere? It seems non-essential.

**Comment by mkibbe1993** [comment]
@krancour It sounds like you're more questioning why the `hack/` directory lives in the root, rather than why the Jenkins stuff goes in `hack/jenkins`. That seems tangential to this PR. We can start an issue about moving `hack/` to `contrib/` since everything in there is non-essential.

**Comment by krancour** [comment]
@mkibbe1993 I was actually inquiring specifically about the Jenkins stuff... but the broader convo about `hack/` (in its entirety) moving under `contrib/` is already started in #252

**Comment by krancour** [comment]
Sorry... I mis-stated the above. #252 is actually about merging `hack/` and `build/`, but there is a separate question, obviously, of whether `hack/` should move under `contrib/`. Sorry for confusion.

**Comment by mkibbe1993** [comment]
@krancour I'm still confused as to where you think is best and what you want from this PR. Above you stated you think the Jenkins stuff should move to `contrib/hack/jenkins`. That looks like two moves to me: one where the files move into `hack/jenkins` (this PR), and a second where we move the entire `hack` directory to `contrib/hack`.

Does that not seem like the right course of action?

**Comment by krancour** [comment]
@mkibbe1993:

> That looks like two moves to me: one where the files move into `hack/jenkins` (this PR), and a second where we move the entire `hack` directory to `contrib/hack`.

Sorry for any and all confusion. Let's try to keep the convo here narrowly scoped. Whether _all_ of `hack/' should move to `contrib/hack/` is probably not a question to entertain here. I only felt rather certain that the Jenkins stuff belonged under `contrib/` somewhere and `contrib/hack/` seems reasonable.

All that said, I don't want to belabor this, since other issues and PRs are weighing the future of the rest of the hack directory. So I am fine with this PR as it stands now. I would have LGTM'ed, except @arschles already did and Deis gets just one vote.

Don't let me block this.

**Comment by mkibbe1993** [comment]
Updated this PR because of the move of `hack` into `contrib`. Now moves the files to `contrib/jenkins`.

**Comment by duglin** [comment]
still LGTM

**Comment by pmorie** [comment]
LGTM, thanks @mkibbe1993

**Pull request merged**
