### PR TITLE
Decompose controller.go

### PR DESCRIPTION
**Pull request by derekwaynecarr**
I think its safe to say the controller.go file is really big.  It reminds me of our past experience with `kubelet.go` being too big.  I have decomposed the controller.go into controller_*.go files based on resource type.  I hope this will reduce conflict files on PRs.

There is no other behavioral change with this.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
the e2e test failure looks like a flake.

**Comment by pmorie** [comment]
I created an issue for the flake and kicked jenkins

**Comment by pmorie** [comment]
LGTM assuming CI passes.

For others: the context here is that I did the exact same refactor to the kubelet code and it paid off with far fewer and easier rebases.

**Comment by MHBauer** [comment]
issue is #898 

I do not need a terrible amount of convincing to chop things up, but it's still all one package, so the visibility hasn't changed.

**Pull request merged**
