### PR TITLE
Fix hrefs again

### PR DESCRIPTION
**Pull request by duglin**
apparently adding "www" to the URL will fix them.  go figure

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
Seems fine now without this change. I think it was a transient issue with that particular link.

**Comment by duglin** [comment]
yes I just got word that the added another round of fixes this AM.  Before this they were telling me it wasn't going to be fixed.

**Comment by duglin** [comment]
however, switching to https is probably a good thing in general

**Comment by kibbles-n-bytes** [comment]
Regardless of whether it was a transient, I agree `http -> https` is good in general so LGTM.

**Pull request merged**
