### PR TITLE
remove from travis integration-tests which are now running in prow

### PR DESCRIPTION
**Pull request by MHBauer**
itests in prow take ~30minutes

We need to make the integration tests create only one set of certificates and reuse them for the whole run.

### CODE REVIEW

**Comment by jboyd01** [comment]
Shouldn't we also remove  `build-integration`?

**Comment by MHBauer** [comment]
@jboyd01 my gut says it provides a quick enough signal that things are bad that we should leave it in for now.
remove the hold if you agree with `/hold cancel`

**Comment by MHBauer** [comment]
I am going to add a comment that says why what's in that list is in it.

**Comment by jboyd01** [comment]
Yeah, sure, it's so quick in comparison to any tests we run, I'm all for it.  Thanks for the details.
/LGTM
/approve

**Pull request merged**
