### PR TITLE
Let travis cache the glide cache

### PR DESCRIPTION
**Pull request by krancour**
This should speed up Travis a bit.

### CODE REVIEW

**Comment by duglin** [comment]
neat, I didn't know it was able to do that. 

LGTM

**Comment by MHBauer** [comment]
can we do the go/pkg then as well? or is that too much state?

**Comment by MHBauer** [comment]
Looks like it works. 11 minutes vs 15~17.

**Comment by krancour** [comment]
> can we do the go/pkg then as well? or is that too much state?

Are you referring to source code? If so, I don't think it makes sense to do that. I think this makes the most sense for untracked files that get pulled down from elsewhere by an "expensive" process such as `glide install`.

**Comment by krancour** [comment]
> Looks like it works. 11 minutes vs 15~17.

I think those times aren't meaningful to compare because, afaik, Travis actually includes time waiting to execute in those numbers.

Also... I got this wrong... so the cache isn't even enabled!

I currently have this in the PR:

```
cache:
- .glide
```

But I should have this:

```
cache:
  directories:
  - .glide
```

I'm fixing now. I will post build logs that show the cache is enabled.

**Comment by krancour** [comment]
Fixed. Standby for proof...

**Comment by krancour** [comment]
Works now... although there's nothing in the cache on the first go-round:

```
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.06s$ Installing caching utilities
0.00s
1.23sattempting to download cache archive
fetching PR.245/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.tgz
fetching master/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.tgz
could not download cache
0.00s
0.41sadding /home/travis/build/kubernetes-incubator/service-catalog/.glide to cache
creating directory /home/travis/build/kubernetes-incubator/service-catalog/.glide
```

**Comment by MHBauer** [comment]
`${GOPATH}/pkg` not the source code.

**Comment by duglin** [comment]
@krancour not sure how to read what you pasted, does that show the before/after timings?

**Comment by krancour** [comment]
@duglin disregard the timings. @MHBauer was pointing out before and after, but those times aren't accurate because they include wait time.

**Comment by krancour** [comment]
@MHBauer, unless I am quite mistaken, with the combination of containerized build and glide, there is effectively not anything in the gopath except our own code.

**Comment by MHBauer** [comment]
I suppose the containerization might effect it. I'm not sure what's mounted.

**Comment by MHBauer** [comment]
If it's all containerized, how is the glide cache escaping?

**Comment by MHBauer** [comment]
I see, it's in the repo root now. 👎

**Comment by duglin** [comment]
do we have any timing info at all to know if this helps?

**Comment by krancour** [comment]
> If it's all containerized, how is the glide cache escaping?

> I see, it's in the repo root now. 👎

I don't quite understand these comments.

Leave Travis out of the equation for a moment...

`.glide` is untracked. It's populated when `glide install` runs. This directory is used as a cache to populate `vendor` more rapidly (without having to go out to the internet) on subsequent `glide install` runs (provided the cache contains the correct package versions required per `glide.lock`, otherwise, glide _does_ pull packages down from the internet). Locally, the existence of this cache speeds up your `glide install` executions pretty significantly.

Now let's talk Travis...

Because `.glide` is untracked, this useful cache is lost from one job execution to the next.

By caching the cache in Travis, the cache stays primed. If a given branch doesn't _have_ a cache associated with it, Travis gives it a copy of the master branch's cache.

I know with absolute certainty that this is both safe and efficient.

**Pull request merged**
