### PR TITLE
Add Docker builds to Travis

### PR DESCRIPTION
**Pull request by martinmaly**
This adds both in-container build, including cross-compilation,
as well as build of Docker images for the catalog and example
brokers.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by krancour** [comment]
What is the point of building the binaries for Darwin?

**Comment by arschles** [comment]
same question as @krancour. can someone give a scenario when we'll run this binary outside a docker container?

**Comment by martinmaly** [comment]
There are number of us who develop on Macs. With Go project portability is more assured than with, say, C++ so having CI run darwin build may not be strictly necessary. If the only way to run the system is on Docker, would it lengthen development iteration period? Unless impossible, I think there is value in being able to run things locally.

**Comment by martinmaly** [comment]
@krancour @arschles - I removed the Darwin build and am keeping only 'make docker' which will do build-linux implicitly.

**Comment by krancour** [comment]
@martinmaly I'm +1 on the change that removes the Darwin build from Travis, so this officially LGTM.

To continue the conversation, however, I'm struggling to understand why we'd even include the capability to compile for Darwin at all in this project. I get that many (include @arschles and myself) use Macs for development, but where's the scenario where any of these components, once built, are run anywhere other than within a k8s cluster?

**Comment by martinmaly** [comment]
@krancour Good question. Let me elaborate:

The most extreme case is that it is impossible for the build to produce Mac binary. By logical extension, it should be impossible to produce any locally executable artifacts (devil's advocate question is: what would make running locally on Linux worth supporting in the Docker-only world?).
We could build inside Docker, run tests inside Docker etc, regardless of developer machine architecture or OS.

This would work well for server-side components (things that run inside k8s cluster).

The counter-example is any CLI tooling for which not only do we need locally-executable builds (I realize that there is currently none in the repo but the original seed code has CLI tools which we removed for the purpose of seeding the kubernetes-incubator repo), but also some way to produce binary releases. Those would be why it is a good thing to support cross-compilation which, on a Linux release machine, can generate darwin executable.

That's the benefits part.

To answer the question why the makefiles support things that they do  ... when I created the Makefiles (on my mac) I needed to be able to produce, on a mac, a Linux docker image and Linux binary; hence in-container cross-compilation (i tried on-mac cross-compilation but that didn't work). Once I had that it was actually equally easy to support cross-compilation for both darwin and linux targets at the same time (the delta is negligible).

Finally, our CI machinery runs inside k8s cluster so the Jenkins workers are containers and if we only supported in-Docker build we couldn't run 'make build' inside a Docker container. I tried it and while it is possible to do 'docker in docker' it really means 'docker next-to docker' where the container communicates with the docker that owns it to spin up sibling, not nested, containers, and mapping sources from the original container (which is executing make) to the sibling (which is executing go build) is quite impossible, because the directories/volumes the 'make container' tries to map into the 'go build container' are interpreted in the context of the Docker host, not the 'make container.

So running CI in containers necessitates non-Docker builds, doing those are as hard as supporting non-Docker builds for LInux and Darwin at the same time, and likewise, doing in-container builds for Linux is as hard as supporting both Linux and Darwin. Plus the CLI scenario mentioned above, in my mind, rounds out the rationale for supporting both Darwin and LInux both as local builds, and in-Docker builds.

Does this help?

**Comment by krancour** [comment]
@martinmaly you've headed off a future line of inquiry from me 😉 . I have long been a proponent of Dockerized builds. I led the charge to start doing that at Deis and it was a positive change for us because it eliminated the roadblock that contributors needed to spend time (possibly hours) building an "artisanally crafted" development environment containing not just our toolchain, but specific versions of each tool therein...

That said, I am _completely_ empathetic to the constraints you highlighted that have forced you in the direction of non-Docker builds. Consider me convinced as far as that aspect of this is concerned.

What I remain curios about is why code of this nature would ever be _run_ anywhere but within k8s? Implicitly that asks why it would ever be _run_ anywhere other than a container. Implicitly, that, in turn, asks why it would ever be run anywhere but linux/amd64. (And I totally recognize that there are small bands of people who are very interested in running k8s on Raspberry Pi clusters, but let's discount them and say that only amd64 architecture generally matters.)

Re: CLIs, I agree 100% that cross-compilation for multiple OS and architectures is desirable, but I don't see where that capability is required for or _must_ necessarily extend to any of the other components, i.e. the ones we're currently cultivating in this repo. Is there any reason that _all_ builds of these components (regardless of where those builds run) cannot exclusively target linux/amd64?

Also, I recognize that we're hijacking this thread! (Sorry!) Feel free to slack me with your response or we can even zoom if you like.

**Comment by vaikas-google** [comment]
LGTM

**Comment by pmorie** [comment]
Merging.

**Pull request merged**
