### PR TITLE
Remove PodPreset embedding from Binding

### PR DESCRIPTION
**Pull request by nilebox**
Reverts the change https://github.com/kubernetes-incubator/service-catalog/pull/760.
Should be replaced by a separate resource discussed in https://github.com/kubernetes-incubator/service-catalog/issues/994 (not part of this PR)

### CODE REVIEW

**Comment by pmorie** [comment]
I'm okay with this but we need to put another resource back in first.

**Comment by duglin** [comment]
Actually we don't need to wait - they're orthogonal - and I'd like to see us move to beta sooner with the minimum needed.  If we do this PR then UX would be:
```
$ kubectl create -f binding.yaml     # to just create the secret
$ kubectl create -f podpreset.yaml   # to link the secret to "the app"
```
Even if the podpreset is created before the secret is ready there's no harm. I checked and the PodPreset will modify any new pod and that pod's creation will be put on hold until the secret becomes available. Which seems like ok semantics for now.

I think the discussions around creating any extra resources (like PodPresetBinding):
1 - are likely to take a while, which just pushed beta out even more
2 - are additive and non-API breaking changes
3 - have undefined requirements today since (as proof of us redesigning today) we don't have a good sense of how we'll want to use this or where the pain points are yet with just the core resources available to us. 

So, for all of those reasons I'd like to get this PR in, ask people to play with just PodPresets, get to Beta, and in the meantime (in parallel, or after beta) we can continue to talk about "if" and "what" additional resources are needed.  I don't see the need to rush this decision for Beta.

**Comment by duglin** [comment]
LGTM

But we need a follow-on PR to modify the walkthru to show how to use podpreset. Not really due to this PR, but just because its been noticed that we don't show that part of the flow today.

**Comment by pmorie** [comment]
> Actually we don't need to wait - they're orthogonal - and I'd like to see us move to beta sooner with the minimum needed.

Disagree, I consider PodPresetBinding a criteria for beta.  We should talk about it next week in a design meeting.

**Comment by nilebox** [comment]
@pmorie even if PodPresetBinding is critical for beta, I agree with @duglin that it is orthogonal to this PR.

This feature was alpha anyway, and current walkthrough doesn't provide example of using embedded PodPreset (actually, it doesn't cover credentials injection into Pod at all). As @duglin pointed out, there is already UX of manually creating PodPreset, which is going to be supported even after we add support for PodPresetBinding.

**Comment by nilebox** [comment]
@pmorie According to https://github.com/kubernetes-incubator/service-catalog/issues/1098, we need to merge this change before beta, without adding an alternative support for PodPreset. Is that correct?
If so, can we remove `do-not-merge` label and merge it?

**Pull request merged**
