### PR TITLE
Ensure the controller never performs a no-op status update

### PR DESCRIPTION
**Pull request by luksa**
Prior to this commit, the controller would, in some cases, post a status
update to the API server where the object's status would be exactly the
same as the object's existing status.

The biggest problem with these no-op status updates is that they result
in the "the object has been modified; please apply your changes to the
latest version and try again" error being logged during
integration tests. The error is logged because the test deletes the
object while the controller is performing a no-op status update.

### CODE REVIEW

**Comment by luksa** [comment]
I'm open to suggestions on how not to have to drag the copy of the object throughout all the code, but this seemed like the most robust way of handling this error (instead of, for example, returning a boolean from the `setServiceInstanceCondition` and then checking it prior to actually posting the updated object to the API server).

**Comment by jboyd01** [comment]
This makes sense to me, I'm not aware of a more elegant way to handle this.  A couple of minor nits you might consider:
* I'd like to see originalBinding or originalInstance vs original
* I'd change these debug msgs to a higher verbosity, maybe a V(5) or something:
    glog.V(4).Info(pcb.Message("Not updating condition, because it wasn't modified"))

**Comment by luksa** [comment]
@jboyd01 Done. Thanks.

BTW: where can I learn more about when to use what log level in svc cat?

**Comment by nilebox** [comment]
Not sure if I like this PR, as it adds significant complexity to the code and involves reflection.

Also, if there are situations where we do unnecessary status updates (I am unaware of those), I would prefer to fix these places on case-by-case basis rather than masking this issue the way this PR does.

And especially I wouldn't want the production code mitigate the issue specific to integration tests (based on the description of this PR it's unclear whether issue is specific to integration tests, or integration tests show actual issue we might encounter in production).

I'll add a `do-not-merge` label for now and would suggest to discuss it at the next SIG call, or at least get clarification on more concrete examples.

**Comment by nilebox** [comment]
@luksa after reviewing your other PR #1887, I wonder if it would be possible to write similar unit tests detecting no-op status updates (e.g. by intercepting the status update function in the fake client)? This would help us to detect and fix such cases rather than masking them.

**Comment by luksa** [comment]
Superseded by #2531

**Pull request closed without merging**
