### PR TITLE
Update OSB client

### PR DESCRIPTION
**Pull request by kibbles-n-bytes**
I need to include the latest `github.com/pmorie/go-open-service-broker-client` version, but Glide will just not cooperate with me trying to just update that one library.

Note: If we don't want all these changes, I can do the OSB client one alone, but then the `glide.lock` will be out of date.

### CODE REVIEW

**Comment by staebler** [comment]
We made an effort a few weeks ago to explicitly specify the version to use for each dependency. It looks like github.com/gorilla/context is a dependency that we are not explicitly specifying in the glide.yaml file--probably a dependency of github.com/gorilla/mux. Should we are add github.com/gorilla/context to our glide.yaml file, even if we are not using it directly?

**Comment by kibbles-n-bytes** [comment]
@staebler Sure, that works. I updated the PR to freeze `github.com/gorilla/context` and just include the OSB client changes. `glide update` is still updating some transitive dependencies, though.

transitive dependencies

**Comment by staebler** [comment]
`glide i -v` should remove the folders that are untracked.

**Comment by kibbles-n-bytes** [comment]
Sweet, that worked for those three, thanks.

**Comment by staebler** [comment]
LGTM

**Pull request merged**
