### PR TITLE
Document NO_DOCKER

### PR DESCRIPTION
**Pull request by pmorie**
#prettystandard

### CODE REVIEW

**Comment by duglin** [comment]
I thought we didn't want to advertise this feature

**Comment by pmorie** [comment]
@duglin would you rather people dig through the makefile?

**Comment by pmorie** [comment]
I can add a note saying that we do not support it, but it is there, if you want it.

**Comment by duglin** [comment]
I'd prefer we removed the option :-)
Short of that I'd prefer if we didn't say anything about it at all - its a non-supported, non-recommended option - based on what we agreed to in the past.

**Comment by MHBauer** [comment]
And yet #431 exists and is not closed.

Either it's not supported, and we take it out, or someone needs to take ownership.

**Comment by pmorie** [comment]
bikeshed strange attactor, closing

**Pull request closed without merging**
