### PR TITLE
lint ignores files marked as generated

### PR DESCRIPTION
**Pull request by MHBauer**
- add comments to lint hand-made expansions
 - remove client from linter ignores

Experiment complete! Ready to merge!

### CODE REVIEW

**Comment by carolynvs** [comment]
What is the experiment? I vote for keeping the ignore on generated code, but maybe I'm missing something?

**Comment by MHBauer** [comment]
Ah yes, the experiment. 

Golang tools now ignore code with a comment  https://golang.org/s/generatedcode
```
Generated files are marked by a line of text that matches the regular expression, in Go syntax:
^// Code generated .* DO NOT EDIT\.$
```
k8s gengo generators now add that comment.

**Comment by carolynvs** [comment]
I'm still a bit confused. Is this the final PR that you want to merge, or should I just ignore it because you are using it to test stuff out?

**Comment by MHBauer** [comment]
final PR ready to go.
experiment is successfull in my mind.

I think this should go in, because I'm all for reducing lines of code when they don't do anything. Includes process stuff like Makefiles.

I can create a followup for investigating the other ignores if that would help, but some I'm not sure will ever change.

**Comment by jboyd01** [comment]
Nice Morgan, LGTM.

**Pull request merged**
