### PR TITLE
Commit generated code on a temporary basis

### PR DESCRIPTION
**Pull request by pmorie**
Generate the generated code and commit it.  This is not a troll and not meant to run counter to our previous discussions on this subject, and not meant to change the status of #203.

During #215 debugging, it was discovered that some of the conversion code was being generated with an incorrect import that referenced `vendor`.  This got me thinking and I did some digging and found that the defaults are not being generated as expected.  So, what I would like to do for now is check in the generated code until we are confident that it is stable as determined by a fuzzing test similar to the [`serialization_test.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/serialization_test.go), after which perhaps we will be in a position to know what we will do longer term after #203 is researched.

Special note to @duglin and @MHBauer: I know you both are against this and we have gone back and forth on this before the break.  I'm really not trying to pick a fight - but I think for now I would like to have this checked in so we can be confident it keeps generating the right content as we refactor the generation bits.

### CODE REVIEW

**Comment by jpeeler** [comment]
LGTM

Having a git diff available while working on the code generation will be a very welcome change.

**Comment by krancour** [comment]
Not crazy about this, but the rationale is defensible and I know with certainty @pmorie is not trying to pick a fight here. Folks should just be aware that in the near term, before submitting PRs, they will need to manually re-run code generation _if_ they have touched `pkg/apis`. LGTM

**Comment by pmorie** [comment]
@krancour @duglin 

> Folks should just be aware that in the near term, before submitting PRs, they will need to manually re-run code generation if they have touched pkg/apis

Can't we make a `make` rule to describe this?

**Comment by krancour** [comment]
> Can't we make a make rule to describe this?

There's already a make target that runs code generation... the problem is enforcing that people run that _before_ committing their code.

**Comment by pmorie** [comment]
@krancour 

> the problem is enforcing that people run that before committing their code.

We will need to have a script that re-runs the generation in CI and kicks you out if there are any diffs.  That's what happens upstream.  I'd like @jpeeler to do that in a follow-up.  Sound good?

**Comment by duglin** [comment]
LOL making it really hard to bite my tongue

**Comment by krancour** [comment]
sgtm

**Comment by MHBauer** [comment]
How do we catch generator failures if not by generating the code? How do we make sure there aren't hand tweaks in this?

My worry is that this calcifies/solidifies, and nobody understands why the code is the way it is. Can we CI the generator to check against the code in the repo? Anything?

**Comment by pmorie** [comment]
@MHBauer 

> Can we CI the generator to check against the code in the repo?

That is exactly what I was saying that upstream does, guess it didn't carry.  This seems to be an area that I have a lot of difficulty explaining things in :)

**Comment by krancour** [comment]
@pmorie and I just discussed this at length because I started to second guess my LGTM, but he re-sold me on the idea. I'm going to try to make an appeal here as to why this is, on a temporary basis, a good idea.

To test that the code generators are doing what they're supposed to do, we really need serialization tests that we don't have yet. In the interim, that means we have no idea whether the generators are generating the right stuff or not. What's even worse is that when code in a generator is changes, we have no insight at all into its impact on what it generates.

If we _check in_ the generated code, then we can all _see_ diffs in the generated code to give us a gut-level understanding of how changes to the generators themselves have influences the code they generated.

On a temporary basis, this makes sense.

> How do we make sure there aren't hand tweaks in this?

As @pmorie pointed out, we can run generation during CI and fail the build if the newly generated code doesn't match the generated code that was checked in. (I would urge a follow up PR to handle that sooner rather than later.)

At the end of the day, this is all about getting generated code tracked so we can _see_ differences. It's imperfect, but we're flying blind right now, and with this, we'd at least be flying with one eye barely squinting open.

**Comment by pmorie** [comment]
I spent some time talking to @krancour and @duglin today and think we cleared some mismatches about some fundamentals, which is good.  HOWEVER, it appears to me that #215 is now in a place where we can combine this PR and add a serialization test into that PR, so I am going to close this out for now.

Apologies for any mismatches we have had on this subject.

**Pull request closed without merging**
