### PR TITLE
Align util package naming.

### PR DESCRIPTION
**Pull request by bmelville**
Better to have one common naming for util than 3 different ones.

Signed-off-by: Brendan Melville <bmelville@google.com>

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by pmorie** [comment]
LGTM, I strongly prefer 'util' over 'utils', personally.

**Comment by bmelville** [comment]
You and me and the rest of the world too :)

**Comment by arschles** [comment]
LGTM, merging

**Pull request merged**
