### PR TITLE
moving broker and examples directories

### PR DESCRIPTION
**Pull request by arschles**
under the new contrib directory

Fixes https://github.com/kubernetes-incubator/service-catalog/issues/51

### CODE REVIEW

**Comment by martinmaly** [comment]
I suspect that this change won't build successfully as-is. The top-level Makefile will need to be updated (https://github.com/kubernetes-incubator/service-catalog/blob/master/Makefile#L20) and the makefiles which were moved will need update of the relative paths in the include clauses (https://github.com/kubernetes-incubator/service-catalog/blob/master/broker/k8s/Makefile#L19)

**Comment by pmorie** [comment]
@martinmaly 

> I suspect that this change won't build successfully as-is. The top-level Makefile will need to be updated (https://github.com/kubernetes-incubator/service-catalog/blob/master/Makefile#L20) and the makefiles which were moved will need update of the relative paths in the include clauses (https://github.com/kubernetes-incubator/service-catalog/blob/master/broker/k8s/Makefile#L19)

We should keep the build working, but the current arrangement with the build is not optimal.  We should not need a Makefile in each package.  I will open another issue for that.

**Comment by arschles** [comment]
+1 on a single makefile. thoughts on merging this and then cleaning up the build and makefile situation immediately thereafter?

cc/ @martinmaly @pmorie

**Comment by vaikas-google** [comment]
LGTM

**Comment by martinmaly** [comment]
I don't have issue with temporarily breaking build to separate pure move from edits and shortening the window where racing commits cause painful rebases. I'd support merging this right away and recovering right thereafter.

you'll need the CLA though regardless.

**Comment by pmorie** [comment]
> +1 on a single makefile. thoughts on merging this and then cleaning up the build and makefile situation immediately thereafter?

SGTM.  I would like to track closely against what Kubernetes does in this area, but a single Makefile that 'just works' is good for now.  Some work needs to be done to consume the upstream build infrastructure.

**Comment by pmorie** [comment]
LGTM

**Comment by krancour** [comment]
LGTM

**Comment by arschles** [comment]
Note that I have signed the CLA, but the bot doesn't recognize that fact at the moment. https://github.com/kubernetes/test-infra/issues/1130 is tracking the fix(es) to this issue.

**Pull request merged**
