### PR TITLE
Fix field order in CatalogRestriction in servicecatalog/types.go

### LINKED ISSUE #2299: Mismatch between v1beta1/CatalogRestrictions and internal/CatalogRestrictions
The order of the properties is reversed. In `v1beta1/types.go`:
```go
type CatalogRestrictions struct {
	// ServiceClass represents a selector for plans, used to filter catalog re-lists.
	ServiceClass []string `json:"serviceClass,omitempty"`    <-----
	// ServicePlan represents a selector for classes, used to filter catalog re-lists.
	ServicePlan []string `json:"servicePlan,omitempty"`      <-----
}
```
vs. `servicecatalog/types.go`:
```go
type CatalogRestrictions struct {
	// ServiceClass represents a selector for plans, used to filter catalog re-lists.
	ServicePlan []string    <-----
	// ServicePlan represents a selector for classes, used to filter catalog re-lists.
	ServiceClass []string   <-----
}
```

Because of this, the conversion between the two types isn't correct. But luckily, this doesn't seem to have any ill effects, since we're performing the wrong conversion two times. 

But, the error does become apparent when you try to create a broker with an invalid restriction:

For example, applying the following ClusterServiceBroker spec:
```
spec:
  url: http://ups-broker-ups-broker.ups-broker.svc.cluster.local
  catalogRestrictions:
    serviceClass:
    - "invalid class restriction"
```
throws the following error:
```
The ClusterServiceBroker "ups-broker-invalid" is invalid: spec.catalogRestrictions.servicePlan: Invalid value: []string(nil): unable to parse requirement: found 'class', expected: '=', '!=', '==', 'in', notin'
```
Note that the error shows `servicePlan` instead of `serviceClass` and that the invalid value is `[]string(nil)` instead of `[]string{"invalid class restriction"}`.

Similarly, if the spec contains `catalogRestrictions.servicePlan`:
```
spec:
  url: http://ups-broker-ups-broker.ups-broker.svc.cluster.local
  catalogRestrictions:
    servicePlan:
    - "invalid plan restriction"
```
this is the error:
```
The ClusterServiceBroker "ups-broker-invalid" is invalid: spec.catalogRestrictions.serviceClass: Invalid value: []string{"invalid plan restriction"}: unable to parse requirement: found 'plan', expected: '=', '!=', '==', 'in', notin'
```

This time, the error mentions `catalogRestrictions.serviceClass` instead of `servicePlan`. But at least here, the correct invalid value is printed.

I'll send a PR shortly. We can discuss the fix there (my hunch is that we may run into a few problems).

### PR DESCRIPTION
**Pull request by luksa**
The order did not match the one in v1beta1/types.go, leading to an
incorrect conversion between the two types.

Fixes #2299

### CODE REVIEW

**Comment by luksa** [comment]
I'm not sure about the consequences of this fix. 

Will it affect existing service catalog deployments - is the `servicecatalog/types.go` version of the struct used to store the object in etcd? Will it therefore break existing broker objects (i.e. will class and plan restrictions be flipped)?

**Comment by luksa** [comment]
I've verified that changing the order doesn't break previously stored brokers, since we're serializing to JSON when storing in etcd:
```
/ # etcdctl get /registry/servicecatalog.k8s.io/clusterservicebrokers/ups-broker
/registry/servicecatalog.k8s.io/clusterservicebrokers/ups-broker
{"kind":"ClusterServiceBroker","apiVersion":"servicecatalog.k8s.io/v1beta1","metadata":{"name":"ups-broker","uid":"a1171b56-aa9c-11e8-b223-0242ac110002","generation":1,"creationTimestamp":"2018-08-28T08:30:32Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"servicecatalog.k8s.io/v1beta1\",\"kind\":\"ClusterServiceBroker\",\"metadata\":{\"annotations\":{},\"name\":\"ups-broker\",\"namespace\":\"\"},\"spec\":{\"catalogRestrictions\":{\"servicePlan\":[\"spec.externalName=premium\"]},\"url\":\"http://ups-broker-ups-broker.ups-broker.svc.cluster.local\"}}\n"},"finalizers":["kubernetes-incubator/service-catalog"]},"spec":{"url":"http://ups-broker-ups-broker.ups-broker.svc.cluster.local","relistBehavior":"Duration","relistRequests":0,"catalogRestrictions":{"servicePlan":["spec.externalName=premium"]}},"status":{"conditions":[{"type":"Ready","status":"True","lastTransitionTime":"2018-08-28T08:30:34Z","reason":"FetchedCatalog","message":"Successfully fetched catalog entries from broker."}],"reconciledGeneration":1,"lastCatalogRetrievalTime":"2018-08-28T08:30:34Z"}}
```

**Comment by jberkhahn** [comment]
/approve

yeah refactors for consistency!

**Pull request merged**
