### PR TITLE
Add deregister command in svcat

### PR DESCRIPTION
**Pull request by jichenjc**
svcat only support register now, deregister is added to support
remove broker registered.

### CODE REVIEW

**Comment by luksa** [comment]
@jichenjc You need to run `make test-update-goldenfiles`.

**Comment by jichenjc** [comment]
I run make test golden configuration and encoutner weird issue locally, submit to CI for double check

**Comment by luksa** [comment]
/lgtm cancel

Actually, @jichenjc can you add a `deregister broker` test to `TestCommandOutput()` in `svcat_test.go`. Make sure to include a newline at the end of `output/deregister-broker.txt` and you'll see that the command doesn't add the newline:
```
[luksa@w541 service-catalog]$ svcat deregister ups-broker
Successfully removed broker "ups-broker"[luksa@w541 service-catalog]$ 
```

Can you also please fix that?

**Comment by jichenjc** [comment]
ok, I will fix it soon by adding the test and the new line, thanks for the reminder

**Comment by jichenjc** [comment]
root@kvm-016922:~/go/src/github.com/kubernetes-incubator/service-catalog# bin/svcat/svcat get brokers
      NAME       NAMESPACE                        URL                                STATUS
+--------------+-----------+------------------------------------------------+----------------------+
  nasty-broker               http://nasty-service.default.svc.cluster.local   ErrorFetchingCatalog
root@kvm-016922:~/go/src/github.com/kubernetes-incubator/service-catalog# bin/svcat/svcat deregister nasty-broker
Successfully removed broker "nasty-broker"


should be fine now :)

**Comment by jboyd01** [comment]
This looks good for Cluster service brokers but lacks support & tests for Name Spaced brokers.  We can do that in a followup.  @jichenjc do you have any interest in doing that next? :)
/approve

**Comment by jichenjc** [comment]
yes, I will create another issue and PR to fix the namespace followup, thanks for the reminder

**Pull request merged**
