### PR TITLE
Add status.presentInCatalog field to service/plan

### PR DESCRIPTION
**Pull request by pmorie**
Part of #801; adds status to ServiceClass/Plan and a `PresentInCatalog` field to each of those that will indicate whether a ServiceClass or Plan is currently present in the broker's catalog.

Note, since the API work turned out to be substantial, this PR will not alter the controller behavior.  I'll make a follow-up PR that uses these fields.

### CODE REVIEW

**Comment by pmorie** [comment]
I need to update the RBAC rules still

**Comment by pmorie** [comment]
Actually, the controller doesn't use the new status subresources yet, so I'm going to leave RBAC out until my next PR.

**Comment by nilebox** [comment]
@pmorie so this PR just adds a new field and `/status` endpoint, but doesn't actually use it yet?

**Comment by nilebox** [comment]
LGTM

**Comment by pmorie** [comment]
@nilebox 

> @pmorie so this PR just adds a new field and /status endpoint, but doesn't actually use it yet?

correct

**Pull request merged**
