### PR TITLE
Client gen

### PR DESCRIPTION
**Pull request by MHBauer**
I didn't know spaces were valid in makefiles. I thought it had to be all tabs.

Separated in two commits. one of gencode.

### CODE REVIEW

**Comment by MHBauer** [comment]
Followed this document https://github.com/kubernetes/community/blob/master/contributors/devel/generating-clientset.md

**Comment by MHBauer** [comment]
We can use the flag `--clientset-name` to change the `internalclientset` directory. The possible naming scheme there seems to indicate release versions.

**Comment by duglin** [comment]
seem pretty straightforward
LGTM

**Comment by pmorie** [comment]
> seem pretty straightforward

I think you mean 'pretty standard'

**Comment by pmorie** [comment]
@arschles has given me verbal LGTM on this

**Comment by arschles** [comment]
+1

**Pull request merged**
