### PR TITLE
make svcat get/describe plan work with namesapced resources

### PR DESCRIPTION
**Pull request by jberkhahn**
a lot of this was already done, just cleaning up the tests in cmd/svcat and making a single method in pkg/svcat work with both ns and cluster types

### CODE REVIEW

**Comment by jberkhahn** [comment]
@MHBauer @jboyd01

**Comment by MHBauer** [comment]
"already done"? Done where? Do you mean it's work that matches other work? Which work?

**Comment by MHBauer** [comment]
/lgtm
I get it now. Straightforward and I get all the removal of some tests for replacement by the ginkgo tests.

**Pull request merged**
