### PR TITLE
Fix typos: specifc->specific classses->classes

### PR DESCRIPTION
**Pull request by mooncak**
Signed-off-by: Bily Zhang <xcoder@tenxcloud.com>

 

This PR is a 
 - [ ] Feature Implementation
 - [-] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
Fix typos: specifc->specific classses->classes

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by mooncak** [comment]
> /approved
> /lgtm

Can you correct "/approved" to "/approve" ?  actually it's "/approve", thanks :-)

**Comment by luksa** [comment]
For the record: I saw that I had the option of editing @duglin 's comment. I was wondering if me fixing /approve to /approve would mark the issue as approved (it shouldn't, since I'm not an approver). Luckily, it didn't. I then changed the comment back.

**Comment by duglin** [comment]
/approve
sorry :-)

**Pull request merged**
