### PR TITLE
Support only containerized build

### LINKED ISSUE #227: Eliminate support for out-of-container build, test, etc.
Currently, make targets involving dependency resolution via glide, compiling, testing etc. can optionally be executed in or out-of container. (Set env var `DOCKER=1` to run in-container.)

As discussed in #219, I'd like us to consider eliminating support for out-of-container builds.

Utilizing in-container builds only minimizes the tooling that any contributor must have access to (go, glide, etc. and specific versions thereof) and maximizes the consistency of the build/test environment from one contributor to the next.

The tangible benefit of eliminating support for out-of-container build, test, etc. is reduced complexity for many of our make targets.

cc @duglin 

Assigning this to myself (because I care about it), but let's all feel free to discuss before I take any action.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #227 

cc @duglin

### CODE REVIEW

**Comment by duglin** [comment]
in general I'm +1 on this but I'll hold off reviewing until #230 goes in as that'll force a big rebase.

But we need more people to buy into this since it might be controversial.

**Comment by pmorie** [comment]
I am willing to be convinced but am starting from a strong do not want
standpoint.

**Comment by krancour** [comment]
@pmorie since you're willing to be convinced...

It's likely that we've all been in one or more of the following positions before:

* Spending more time that we'd like ensuring we have the right toolchain to work on product x.
* Having difficulty troubleshooting someone else's issue because you can't account for minute environment differences. We've all heard "it worked on _my_ machine."

I often cite these as reasons why using Docker to provide a standardized development environment, where changes to the environment itself are tracked and versioned along with the rest of our codebase, is A Good Thing™. You probably didn't need to be sold on this idea, and it's great that we already do this...

The trouble is that we don't enforce that way of doing things. As long as we support the _option_ to bypass all of that by building out-of-container, some people will, and that means we don't get the full benefit. What's worse is that our Makefile incurs extra complexity to support that option that we might wish people wouldn't actually exercise. 😿 

As it stands now, here are three different permutations we support:

* In-container build
    * Whether on Mac or Linux should be of only minor consequence
* Out-of-container build on Mac
* Out-of-container build on Linux

It's tedious having to test all these permutations each time we make an improvement to the build/test process.

But since you were a good sport in saying you were willing to be convinced, I am willing to be convinced in the other direction. Can you articulate specific reasons you would _like_ to see continued support for out-of-container builds?

**Comment by pmorie** [comment]
In theory, supporting a single style of build cuts down on the cognitive load and energy required to maintain the project developer experience.  I like that you would be running in the exact same environment as in CI (now that travis supports Docker images).

However, I do have some concerns around running and debugging tests.  My setup for that involves running `go test` locally.  I think I can adapt my IDE tooling (I use the GoTools plugin for Sublime text) to running tests in a container, but I expect that others might find that they have issues around this.  For example, I know that at least a couple people on the team use VSCode and IntelliJ -- will their IDE integrations work correctly with this?  Do we expect that people will debug unit tests locally using `go test`?

**Comment by duglin** [comment]
I can't speak to the debugging side of things because I don't use any tools for debugging - I get by with just trying to do the test's steps manually. So, from my perspective, the most important thing is to make sure that our testing infrastructure is easy to follow and there's limited "magic".  If a newbie can look at a test and easily figure out how to reproduce those same steps outside of the test framework we have then I tend to think we've complicated it too much. This also means that it should be easy for someone new to add new tests too - no big learning curve.

How does this relate to @pmorie's comment? People should be able to use whatever debugging tools they want, and they should be able to set them up to reproduce a particular test easily/quickly - meaning look at a test and be able to know how to manually reproduce that test outside of the framework. So, running in a container (which should for the most part be just wrapping some command with "docker run") shouldn't really impact much.

Side note: this is why I had such a negative reaction to the possibility of using ginko. I love tools/helper-funcs to save me typing, but not to hide (or introduce) complexity.

**Comment by martinmaly** [comment]
There are definitely benefits to hermetic (containerized) builds so in principle I don't object, but we need to ensure the following use case is supported: CI/CD pipeline which uses containers as workers. That's the Jenkins setup we are using. I am not sure if with this change it will actually work because docker-in-docker is quite tricky.

@krancour, can you please demonstrate that with these changes one can spin up Jenkins worker - a container - and all make commands will be supported? build, tests, package into Docker images, push etc.?

Personally, when I did the initial set up the only way to enable running CI/CD worker in container was to support non-containerized build in our makes; otherwise, the build would be running docker in docker which works in some cases but requires amount of control over the worker container that I could not attain in Jenkins/Kubernetes combination.

Perhaps it is not a goal to support CI/CD with containerized workers, although there would be an element of irony in it. Or perhaps it works but to my knowledge this project is not yet set up to demonstrate it.

Thus, I'd strongly urge to wait, build a serious CI/CD (or revive the one we had but which got broken by the series of make changes and refactorings) and only then proceed with that safety net.

Just my 2c though.

**Comment by duglin** [comment]
@martinmaly I'm interested in trying to setup what you asked about. But to be clear, are you running Jenkins itself in a container or is Jenkins running natively and the jobs it starts runs in containers?

**Comment by martinmaly** [comment]
Jenkins master runs on a VM and uses [Kubernetes Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Kubernetes+Plugin) to spin up workers.

I actually tried to have the master run on Kubernetes as well but I had difficulty setting it up so I had to fall back on a VM-hosted master.

**Comment by duglin** [comment]
FWIW, just did this and it worked:
```
root# docker run -ti --privileged ubuntu bash

root@ecb0857919c4# apt-get -y update
root@ecb0857919c4# apt-get -y uprade
root@ecb0857919c4# apt-get -y install curl git make
root@ecb0857919c4# curl -sSL https://get.docker.com/ | sh
root@ecb0857919c4# service docker start
root@ecb0857919c4# git clone https://github.com/kubernetes-incubator/service-catalog.git
root@ecb0857919c4# cd service-catalog
root@ecb0857919c4# DOCKER=1 make all images
```
of course this all depends on whether the jenkins container has the right privileges to run docker in docker.

**Comment by martinmaly** [comment]
wow, cool! Hopefully it'll also work on the k8s Jenkins worker.

**Comment by MHBauer** [comment]
https://github.com/kubernetes-incubator/service-catalog/pull/231#issuecomment-271107587

> root@ecb0857919c4# apt-get -y uprade

... uprade ? j/k

**Comment by duglin** [comment]
yea well I had do some manual extraction from my "script" output :-)

**Comment by krancour** [comment]
@martinmaly I tried to look back on our conversation history in Slack and found it was gone. (I think the k8s Slack doesn't preserve history for as long as I'd like.) Anyway... I was looking there to try to recall the reasons out-of-container build was even a thing. You've reminded me of it now-- Jenkins slaves. Thanks!

I'm not going to close this just yet, but I am going to see if I can come up with a more palatable, k8s-inspired alternative that allows us to build in or out-of container, but with less complexity.

**Comment by arschles** [comment]
Trying to provide some nonpartisan analysis here: this patch doesn't prevent doing things directly on the host or within an editor. You won't have a `make` target for them.

For example, I have been building & testing, both in the console and in-editor, using raw commands (`go` et al.). See below for how to do so.

# Testing on the Host

If you have the correct `go` toolchain, Go environment, `glide` installed, and dependencies installed, run `go test $(glide nv)` to unit-test all packages in the repo. I already do this with a hotkey in atom.

# Debugging on the Host

Many debugging tools rewrite code and then run `go test` on the rewritten source. `godebug`, for example, is a one-liner on the console.

A few debugging tools execute against machine code directly, so they need to `go build`. This is the most complex workflow with standard (non-`make`) tools because you need to know which package to build (you can't build them all because there are multiple `main`s).

That is, you can't `go build ./...`, you have to `go build ./something-with-a-main` instead.

# CI/CD

Looks like @krancour is still looking at ways to provide scripts that facilitate CI/CD as it stands now. Note that we have a meeting scheduled for 1/11/2017 to discuss the future of CI/CD. We should discuss options to run containerized builds/tests on our CI/CD system of the future.

Using a hermetically sealed "dev container" or VM (we do not want to do this. happy to expand on why) is the only way I know of to ensure the same dev, test and e2e environments

**Comment by duglin** [comment]
On the plus side, if we did just docker builds then our CI would be about 1/2 the time since we build/test both ways  :-)

**Comment by pmorie** [comment]
> On the plus side, if we did just docker builds then our CI would be about 1/2 the time since we build/test both ways :-)

This is actually a pretty powerful argument to me.  I am leaning towards saying let's go for this, but make it explicit that we expect people to do whatever they need to to test / debug locally.

**Comment by krancour** [comment]
Closed in favor of #238

**Pull request closed without merging**
