### PR TITLE
Fix comments on 'get bindings'

### PR DESCRIPTION
**Pull request by jichenjc**
Trivial Fix: add namespace into supported list

 actually namespace is supported when retrieve the bindings

### CODE REVIEW

**Comment by carolynvs** [comment]
@jichenjc Thanks for the fix! Here are the instructions for how to regenerate the golden files, those files are out-of-date with your recent change, and that is why the unit tests are failing.

https://svc-cat.io/docs/devguide/#golden-files

**Comment by jboyd01** [comment]
@jichenjc this looks good but you need to regenerate the golden files used by unit tests so it will pass.  See https://github.com/kubernetes-incubator/service-catalog/pull/2355#issuecomment-424375914 for details.

**Pull request merged**
