### PR TITLE
Delete duplication in files

### PR DESCRIPTION
**Pull request by mooncak**
Signed-off-by: Bily Zhang <xcoder@tenxcloud.com>

 

This PR is a 
 - [ ] Feature Implementation
 - [-] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
Delete duplication in files:

1. pkg/apis/servicecatalog/types.go
2. pkg/apis/servicecatalog/v1beta1/types.go
3. pkg/controller/controller_instance_test.go

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by luksa** [comment]
@mooncak You need to run `make build` and check-in the modified files (`openapi_generated.go` for example).

**Comment by mooncak** [comment]
> @mooncak You need to run `make build` and check-in the modified files (`openapi_generated.go` for example).

@luksa , run `make build` under service-catalog directory? I ran it but nothing modified.

**Comment by luksa** [comment]
@mooncak Hmm, that's odd. Have you tried running `make clean` first? When I run the build on your branch, the file gets updated.

**Comment by mooncak** [comment]
> @mooncak Hmm, that's odd. Have you tried running `make clean` first? When I run the build on your branch, the file gets updated.

I have `make build` to updated the openapi_generated.go file

**Pull request merged**
