### PR TITLE
Add .kubeconfig to .gitignore

### PR DESCRIPTION
**Pull request by pmorie**
Pretty much what it sounds like.

### CODE REVIEW

**Comment by krancour** [comment]
@pmorie how is it that `.kubeconfig` is getting created within the project's working directory in the first place?

**Comment by pmorie** [comment]
I'm creating it.

**Comment by arschles** [comment]
LGTM

**Comment by MHBauer** [comment]
Sound fine. Do not care. Still would like comments in the ignore.

lgtm

**Comment by krancour** [comment]
> I'm creating it.

Through what process? I can't spot anything in master that is a codified process (e.g. build, test, etc.) or manual process (e.g. walkthrough) that would create this file. Am I overlooking something?

If you _manually_ created that file, for whatever reason, I'm not sure that is justification for adding this to `.gitignore`. I could arbitrarily create a `.plumbus` file in my working directly and I think we'd all agree _that_ shouldn't be added to `.gitignore`. I really do hate being a stickler, but I'm not sure I see how this is any different.

**Comment by pmorie** [comment]
@krancour I have 4 different things now that I routinely run on my local system for which I like to keep separate kubeconfigs with direnv:

1.  k8s
2.  OpenShift Origin
3.  OpenShift Enterprise
4.  service-catalog API server

My personal system is to keep a unique kubeconfig in the root directory of each project and set `KUBECONFIG` for that directory using direnv.  This is pretty critical for me to keep things straight.

**Comment by krancour** [comment]
I mean I get _why_ you're doing it. I just don't like the precedent it sets-- that we are willing to make accommodations in our repo for individual contributor's unique workflows. It's just `.gitignore` now, but what's next? More customizations to our already-difficult build process because _one person_ wants to `<xyz>`?

All that being said, I don't want to endlessly debate this issue when we clearly have bigger fish to fry, so... LGTM, but with reservations above entered for the record.

**Comment by krancour** [comment]
Whoops. @arschles already offered a Deis LGTM. I think we're all operating in good faith here. I am just going to merge this.

**Comment by MHBauer** [comment]
I'd like to see a direnv description or example at some point, but I think I just need to remember to take time and look it up.

**Comment by pmorie** [comment]
> It's just .gitignore now

That's what `.gitignore` is _for_.

**Pull request merged**
