### PR TITLE
Update video links in README

### PR DESCRIPTION
**Pull request by jberkhahn**
As per the suggestion in the meeting today, updating the README with some more recent videos.

### CODE REVIEW

**Comment by jberkhahn** [comment]
morgan cannot into approving, apparently
although, the git robot should probably watch that, too
/approve

**Comment by MHBauer** [comment]
I cannot? What?

**Comment by jberkhahn** [comment]
You submitted an approving review, which doesn't link up with the git robot, so it didn't count. You need to use the / command or add the label manually.

**Pull request merged**
