### PR TITLE
remove obsolete documentation on proposed future v1

### LINKED ISSUE #2008: API type names are not up to date
https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/v1/api.md

### PR DESCRIPTION
**Pull request by MHBauer**
This PR is a 
 - [ ] Feature Implementation
 - [ ] Bug Fix
 - [x] Documentation

**What this PR does / why we need it**:
Removes obsolete documentation. Out of date documentation is confusing.

**Which issue(s) this PR fixes** 
resolves #2008 

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [x] Documentation

### CODE REVIEW

**Comment by jberkhahn** [comment]
think you need to remove some more references to the pages you removed, the travis build is failing on them

**Comment by MHBauer** [comment]
/assign @jberkhahn 
updated, should pass the link-checker now.

**Pull request merged**
