### PR TITLE
Add SecretTransform integration test (for RenameKeyTransform)

### LINKED ISSUE #1892: Add integration tests for credential remapping
@n3wscott and I both missed this in #1868

### PR DESCRIPTION
**Pull request by luksa**
Closes #1892

### CODE REVIEW

**Comment by n3wscott** [comment]
LGTM, looks like the failure was the thing I was fighting yesterday

**Comment by luksa** [comment]
Rebased to get the failing integration tests fixed.

**Comment by luksa** [comment]
Closing, as this test already went in as part of #1927

**Pull request closed without merging**
