### PR TITLE
Define common interfaces for cluster and namespaced classes and plans

### PR DESCRIPTION
**Pull request by carolynvs**
This is necessary groundwork for the svcat cli to deal with both `ClusterServiceBrokers` and `ServiceBrokers`. I expect that interface may expand to add more values from the common specs but for now I just wanted to get it defined so that the many issues for supporting namespaced brokers aren't blocked by a larger PR (#2116).

### CODE REVIEW

**Comment by jboyd01** [comment]
@carolynvs - travis doesn't appreciate your lack of copyright in the two new files.  I didn't catch it in review.

**Comment by carolynvs** [comment]
Sorry abut that, forgot to run `verify` locally... 😊 Fixing!

**Pull request merged**
