### PR TITLE
Abstract a function to set operatetime.

### PR DESCRIPTION
**Pull request by wayilau**
This PR is a 
 - [x] Feature Implementation
 - [ ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** 
abstract a funciton to simplfy code, code reuse.

### CODE REVIEW

**Comment by jberkhahn** [comment]
I think this is a bad idea. This function isn't going to get reused anywhere else, and I don't think the increased misdirection is worth the 4 lines we save

**Comment by wayilau** [comment]
yes, This function isn't going to get reused anywhere else, but This function has too many lines that make it inconvenient to read. what do you think ?
@jberkhahn

**Comment by wayilau** [comment]
why the builds broken ? i was not changing any other code...
@jberkhahn

**Comment by jberkhahn** [comment]
I don't know why. The error we're getting is an error from the auto-generated code with the message "oops".

**Comment by taragu** [comment]
@wayilau thanks for your PR! I'm with @jberkhahn on this. It's only 4 lines of code we are refactoring and it will only be used in two places

**Comment by wayilau** [comment]
OK, i close this now.

**Pull request closed without merging**
