### PR TITLE
Updating deregister_cmd.go

### LINKED ISSUE #2439: deregister confusingly fails if missing --scope cluster
# Bug Report 

**What happened**:

```
$ svcat get brokers
                  NAME                   NAMESPACE                                      URL                                              STATUS
+--------------------------------------+-----------+----------------------------------------------------------------------------+----------------------+
  email-worlds-simplest-service-broker               http://email-worlds-simplest-service-broker.default.svc.cluster.local:3000   ErrorFetchingCatalog

$ svcat deregister email-worlds-simplest-service-broker
Error: deregister request failed (servicebrokers.servicecatalog.k8s.io "email-worlds-simplest-service-broker" not found)
```

I also cannot resync the broker if I think I've resolved an issue:

```
$ svcat sync broker email-worlds-simplest-service-broker
Error: could not sync service broker email-worlds-simplest-service-broker (unable to get broker 'email-worlds-simplest-service-broker' (servicebrokers.servicecatalog.k8s.io "email-worlds-simplest-service-broker" not found))
```

**What you expected to happen**:

That the broker was deregistered/CRDs deleted.

### PR DESCRIPTION
**Pull request by AdamDang**
Fix the error parameter 
--cluster should be --scope=cluster

### CODE REVIEW

**Comment by carolynvs** [comment]
@AdamDang The PR title and description don't match the code fix provided by this PR. The help text is incorrect using `--cluster` instead of `--scope=cluster`, however that doesn't have anything to do with the linked issue.

Are you okay with me cleaning up the title and description of your PR to match the fix, or did you intend to fix that bug mentioned in the linked issue?

/hold

**Comment by carlory** [comment]
Hi @carolynvs , I think that this issue #2439 is not a bug. 

```shell
svcat deregister email-worlds-simplest-service-broker
```

because this command can not deregister a cluster broker.

**Comment by AdamDang** [comment]
Thanks @carolynvs 
It's my fault, I confirmed that the change in this PR could not solve the mentioned issue.
So can I close it now?

**Comment by carolynvs** [comment]
No worries!

**Pull request closed without merging**
