### PR TITLE
Adding protobuf annotations to v1alpha1 types

### PR DESCRIPTION
**Pull request by mijajasinski**
Adds annotations enabling generation of protobuf messages from go types defined in service catalog.

### CODE REVIEW

**Comment by mijajasinski** [comment]
I think the CLA should be ok now.

**Comment by mijajasinski** [comment]
I was able to generate .proto file using kubernetes's go-to-protobuf just with this file.

The annotations are hand-crafted, and I'm afraid there is no good documentation for the structure.
If you're not familiar with the format, best bet is to follow conventions used across kubernetes codebase and run them through go-to-protobuf to check if it doesn't generate errors.

The structure of the tag is fairly simple - you provide wiretype (usually bytes), field number (as governed by protobuf rules: no reuse withing a type, etc.), name for the field in generated proto, and casttype where it's required (usually for enum fields and imported types).

The main benefit of providing possibility to generate protobuffer from these structs is easier API consumption from other OO languages than golang (otherwise you have to access json objects).

Let me know if I can provide more context, or help in any other way.

**Comment by MHBauer** [comment]
where is go-to-protobuf? It sounds like that should be integrated into either the code-generation or verify step of the build.

**Comment by pmorie** [comment]
I think this is a good PR as an exercise, but we are going to be eliminating the v1alpha1 version of this API soon.  Feel free to continue if you don't mind repeating work if that happens before this PR goes in, otherwise, feel free to wait until the API is bumped.

**Comment by pmorie** [comment]
@mijajasinski I would merge this if it included the protobuf generation - are you up for adding that in?

**Comment by n3wscott** [comment]
Looks like we have moved to v1beta1 and v1alpha1 is gone. We still want protobuf gen?

**Comment by nilebox** [comment]
@mijajasinski the PR hasn't been updated since August, closing. Feel free to reopen if you want to continue working on it.

**Pull request closed without merging**
