### PR TITLE
Fix data race in instance integration test

### LINKED ISSUE #1625: Race in integration tests
Looks like #1611 introduced a new data race in the integration tests:

```
    --- FAIL: TestDeleteServiceInstance/deprovision_instance_after_in_progress_provision (10.90s)
    	framework.go:76: Starting server on port: 4184
    	controller_test.go:479: controller start
    	controller_test.go:491: informers start
    	framework.go:72: Shutting down server on port: 4184
    	testing.go:699: race detected during execution of test
	testing.go:699: race detected during execution of test
```

Looking into this now.

### PR DESCRIPTION
**Pull request by jpeeler**
Modifying the controller reactions after the setup function (in the test
function in this case) leads to races. Using a dynamic reaction solves this
issue.

Also, change the test to look for a successful provision rather than a request
in flight condition so that no timing issues can occur.

Closes #1625

### CODE REVIEW

**Comment by pmorie** [comment]
@MHBauer 

> A Dynamic Reaction is saying we can update what the reaction returns during the test rather than it being hardcoded to do one thing at the start?

Yeah - you can program the fake to return ‘in progress’ first and then ‘succeeded’ using this flavor of reaction

**Comment by kibbles-n-bytes** [comment]
@jpeeler A couple questions:

1) What was the race situation in the original test? I don't see anything that jumps out as a race.

2) It seems to me like the new version changes the behavior of the test. If I understand correctly, the original test is meant to confirm that a deprovision attempt will cancel an in-progress async provision. Now it looks like the new test just checks a normal async happy path.

**Comment by MHBauer** [comment]
@kibbles-n-bytes  data race on the original PR reproduced below for the record.

I've attempted to write down my understanding in #1625 previously.

```
=== RUN   TestDeleteServiceInstance/deprovision_instance_after_in_progress_provision
[restful] 2017/12/16 18:32:07 log.go:33: [restful/swagger] listing is available at https:///swaggerapi
[restful] 2017/12/16 18:32:07 log.go:33: [restful/swagger] https:///swaggerui/ is mapped to folder /swagger-ui/
==================
WARNING: DATA RACE
Read at 0x00c42fde6100 by goroutine 4017:
  github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake.(*FakeClient).PollLastOperation()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go:182 +0x237
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).pollServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:938 +0x6b7
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:390 +0x59cb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstanceKey()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:212 +0x3ca
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).(github.com/kubernetes-incubator/service-catalog/pkg/controller.reconcileServiceInstanceKey)-fm()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x55
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1.1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:228 +0xf7
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:245 +0xb2
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x6f
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xcd
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.Until()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x5a
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:207 +0x9e
Previous write at 0x00c42fde6100 by goroutine 4145:
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func10()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1291 +0x38e
  github.com/kubernetes-incubator/service-catalog/test/integration.(*controllerTest).run()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:927 +0x815
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func11()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1313 +0x4a5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
Goroutine 4017 (running) created at:
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:206 +0xcb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).Run()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x524
  github.com/kubernetes-incubator/service-catalog/test/integration.newTestController.func2()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:487 +0x51
Goroutine 4145 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1304 +0xaba
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Read at 0x00c426c2b380 by goroutine 4017:
  github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake.(*PollLastOperationReaction).react()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go:359 +0xd4
  github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake.(*FakeClient).PollLastOperation()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go:183 +0x32e
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).pollServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:938 +0x6b7
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:390 +0x59cb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstanceKey()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:212 +0x3ca
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).(github.com/kubernetes-incubator/service-catalog/pkg/controller.reconcileServiceInstanceKey)-fm()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x55
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1.1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:228 +0xf7
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:245 +0xb2
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x6f
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xcd
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.Until()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x5a
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:207 +0x9e
Previous write at 0x00c426c2b380 by goroutine 4145:
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func10()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1292 +0x263
  github.com/kubernetes-incubator/service-catalog/test/integration.(*controllerTest).run()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:927 +0x815
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func11()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1313 +0x4a5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
Goroutine 4017 (running) created at:
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:206 +0xcb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).Run()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x524
  github.com/kubernetes-incubator/service-catalog/test/integration.newTestController.func2()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:487 +0x51
Goroutine 4145 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1304 +0xaba
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Read at 0x00c426c2b388 by goroutine 4017:
  github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake.(*PollLastOperationReaction).react()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go:359 +0xe6
  github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake.(*FakeClient).PollLastOperation()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/github.com/pmorie/go-open-service-broker-client/v2/fake/fake.go:183 +0x32e
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).pollServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:938 +0x6b7
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:390 +0x59cb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstanceKey()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:212 +0x3ca
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).(github.com/kubernetes-incubator/service-catalog/pkg/controller.reconcileServiceInstanceKey)-fm()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x55
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1.1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:228 +0xf7
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:245 +0xb2
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x6f
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xcd
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.Until()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x5a
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:207 +0x9e
Previous write at 0x00c426c2b388 by goroutine 4145:
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func10()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1292 +0x263
  github.com/kubernetes-incubator/service-catalog/test/integration.(*controllerTest).run()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:927 +0x815
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func11()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1313 +0x4a5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
Goroutine 4017 (running) created at:
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:206 +0xcb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).Run()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x524
  github.com/kubernetes-incubator/service-catalog/test/integration.newTestController.func2()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:487 +0x51
Goroutine 4145 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1304 +0xaba
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Read at 0x00c426c2b3a0 by goroutine 4017:
  runtime.convT2Estring()
      /usr/local/go/src/runtime/iface.go:274 +0x0
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).pollServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:1021 +0x172c
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:390 +0x59cb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstanceKey()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:212 +0x3ca
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).(github.com/kubernetes-incubator/service-catalog/pkg/controller.reconcileServiceInstanceKey)-fm()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x55
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1.1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:228 +0xf7
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:245 +0xb2
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x6f
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xcd
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.Until()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x5a
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:207 +0x9e
Previous write at 0x00c426c2b3a0 by goroutine 4145:
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func10()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1293 +0x2c6
  github.com/kubernetes-incubator/service-catalog/test/integration.(*controllerTest).run()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:927 +0x815
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func11()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1313 +0x4a5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
Goroutine 4017 (running) created at:
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:206 +0xcb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).Run()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x524
  github.com/kubernetes-incubator/service-catalog/test/integration.newTestController.func2()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:487 +0x51
Goroutine 4145 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1304 +0xaba
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Read at 0x00c426c2b3b0 by goroutine 4017:
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).pollServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:1021 +0x17a8
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:390 +0x59cb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).reconcileServiceInstanceKey()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_instance.go:212 +0x3ca
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).(github.com/kubernetes-incubator/service-catalog/pkg/controller.reconcileServiceInstanceKey)-fm()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x55
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1.1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:228 +0xf7
  github.com/kubernetes-incubator/service-catalog/pkg/controller.worker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:245 +0xb2
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x6f
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xcd
  github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait.Until()
      /go/src/github.com/kubernetes-incubator/service-catalog/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x5a
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker.func1()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:207 +0x9e
Previous write at 0x00c426c2b3b0 by goroutine 4145:
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func10()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1293 +0x2c6
  github.com/kubernetes-incubator/service-catalog/test/integration.(*controllerTest).run()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:927 +0x815
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance.func11()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1313 +0x4a5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
Goroutine 4017 (running) created at:
  github.com/kubernetes-incubator/service-catalog/pkg/controller.createWorker()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:206 +0xcb
  github.com/kubernetes-incubator/service-catalog/pkg/controller.(*controller).Run()
      /go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller.go:178 +0x524
  github.com/kubernetes-incubator/service-catalog/test/integration.newTestController.func2()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_test.go:487 +0x51
Goroutine 4145 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:789 +0x568
  github.com/kubernetes-incubator/service-catalog/test/integration.TestDeleteServiceInstance()
      /go/src/github.com/kubernetes-incubator/service-catalog/test/integration/controller_instance_test.go:1304 +0xaba
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:746 +0x16c
==================
```

**Comment by arschles** [comment]
Looks like all questions in the thread are answered, labelling and merging now

**Comment by staebler** [comment]
@kibbles-n-bytes 

1) The data race was due to the `PollLastOperationReaction` field in the fake osb client being read from one thread and written to in another thread. The reader thread is the controller worker thread attempting to get a response to a poll last operation request. The writer thread is the test thread attempting to change the reaction from one that returns StateInProgress to one that returns StateSucceeded.
2) The old version waiting until the provision succeeded before attempting the delete, just like the new one does. The difference is that the old one also attempted to verify that the ProvisioningInProgress condition reason was also seen. However, since the test just uses a counter for the transition of the response to the poll last operation request, there was no guarantee that the test would ever see the ProvisioningInProgress. The instance could have already completed its provisioning prior to the test verifying the ProvisioningInProgress.

**Pull request merged**
