### PR TITLE
Follow constant convention for ErrorWithOriginatingIdentityReason

### LINKED ISSUE #2530: ErrorWithOriginatingIdentityReason doesn't follow convention since it includes spaces
# Bug Report 

All ServiceCatalog condition reasons are written in camel case, without spaces. But `errorwithOriginatingIdentity` contains spaces: 

https://github.com/kubernetes-incubator/service-catalog/blob/37b874716ad709a175e426f5f5638322a600849f/pkg/controller/controller_instance.go#L64

The constant is used as a condition reason here: https://github.com/kubernetes-incubator/service-catalog/blob/37b874716ad709a175e426f5f5638322a600849f/pkg/controller/controller_instance.go#L2185

We should remove those spaces.

### PR DESCRIPTION
**Pull request by imcsk8**
This PR is a 
 - [ ] Feature Implementation
 - [ x ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:

All ServiceCatalog condition reasons are written in camel case, without spaces.
But errorwithOriginatingIdentity contains spaces.

**Which issue(s) this PR fixes** 

Fixes #2530 

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by jboyd01** [comment]
> variable itself seems incorrectly named. not a `reason` or a `message`

Agreed @MHBauer , there are several similar variables here in the same situation.

**Comment by luksa** [comment]
@mhbauer, @jboyd01 see https://github.com/kubernetes-incubator/service-catalog/pull/2519

**Pull request merged**
