### PR TITLE
Fix typos: verfies -> verifies

### PR DESCRIPTION
**Pull request by mooncak**
Signed-off-by: Bily Zhang <xcoder@tenxcloud.com>

 

This PR is a 
 - [ ] Feature Implementation
 - [- ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
Fix typos: verfies -> verifies

**Which issue(s) this PR fixes** 

Fixes #

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by duglin** [comment]
can you try to put more than one typo in a PR? You don't need separate PRs per typo

**Comment by mooncak** [comment]
> can you try to put more than one typo in a PR? You don't need separate PRs per typo

ok

**Pull request merged**
