### PR TITLE
Add unit test for cmd/svcat/broker/get_cmd.go

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by jberkhahn** [comment]
Hey there, see my comment in #2179, but I'd like to put a hold on adding tests to cmd/svcat for the moment.

/hold

**Comment by jberkhahn** [comment]
See my comment in (2197)[https://github.com/kubernetes-incubator/service-catalog/pull/2179], but I'd like this to be refactored into a Ginkgo test that matches the other unit tests I'm writing. Currently this isn't a very good unit test because it is actually using the code in pkg/svcat and goes all the way to a fake kubeclient. I'd like for the unit tests to only test pkg/svcat code.

**Comment by carolynvs** [comment]
Heads up that there is an open PR that is also changing the tests for the `svcat get brokers` command: #2227

**Comment by jberkhahn** [comment]
if there's no update on this, I'm going to close it

**Pull request closed without merging**
