### PR TITLE
warning for those editing pkg/client

### PR DESCRIPTION
**Pull request by MHBauer**
I've seen people edit pkg/client and become confused by why there changes disappear, or don't show up or this or that on the CI.

#417 is merely the most recent manifestation.

I wanted something a bit more catchy than README, so that's my explanation for the file name.

### CODE REVIEW

**Comment by duglin** [comment]
let's twiddle the generated files names (to have a 'zz' or something like that in them). People won't notice a warning file - at least I wouldn't have.

**Comment by MHBauer** [comment]
For `informer-gen` & `lister-gen` the only knob we have is adjusting the `--output-package`flag.

If clients are in `clientset_generated`, then perhaps the informers and listers should be in a similarly named directory?

**Comment by MHBauer** [comment]
Or we could move everything into some kind of `pkg/generated`

**Comment by duglin** [comment]
I would really like that but I was wondering what that would mean for people trying to import our generated code - which I think is the main usecase for checking in this stuff.

**Comment by pmorie** [comment]
LGTM

One thing we do to handle this type of concern in upstream is have a 'verify' script that regenerates all the code and verifies that there are no changes relative to what's in the tree.  We need that here.

**Comment by arschles** [comment]
I think this is a good start. I'd like to see [other](https://github.com/kubernetes-incubator/service-catalog/pull/418#issuecomment-282799601) [suggestions](https://github.com/kubernetes-incubator/service-catalog/pull/418#issuecomment-282624621) discussed and possibly implemented in follow ups.

I am merging this.

**Pull request merged**
