### PR TITLE
WIP: complete rewrite of tpr-based storage

### LINKED ISSUE #407: Add TPR storage to the tests in test/integration/clientset_test.go
They currently test just the etcd-based server. I believe there is a bug with service class creation as well, so this will force fixing that bug.

Left to do:

- [x] Mock out the client interface and pass it to the TPR options in integration.go
    - Probably using `github.com/kubernetes-incubator/service-catalog/pkg/client/clientset_generated/clientset/fake` -- requires #505, as @krancour is writing a mock `RESTClient` that this fake will need to use.
- [ ] Re-enable the TPR storage type in clientset_test.go

### PR DESCRIPTION
**Pull request by krancour**
Closes #407 
And others? Need to identify.

I want to also do some manual testing before I consider this out of a WIP state.

Don't try to read the diffs. Just look at this like a _complete_ rewrite, because I really did start from the ground up.

These are current, known issues with this branch that require resolution:

- [ ] __Integration test strategy may be unreliable.__ Tests rely on a mocked out core apiserver. This may not be adequately mimicking the behavior of a core apiserver and may therefore be unfairly influencing the integration tests. Should explore using an _actual_ core apiserver.
- [ ] __Integration tests failing-- tests for creating resources fails.__ e.g. after creating and listing: "should have exactly one broker, had 0 brokers". Issue could be in create _or_ in list.
- [ ] @pmorie: "When I create an instance while using TPR as the backend for the API server, I can get that specific instance, but listing instances does not work, even when using the qualified API version and resource name"
- [ ] __Updates result in an infinite update loop.__ To see this in action, create any resource (e.g. a broker). When the controller updates its status to reflect that the broker's service offerings have been imported as `ServiceClass` resources, it will attempt to update broker state. This triggers _another_ event that causes the controller to once again update state... ad infinitum. Shutting down the controller stops the infinite loop... until you restart it. This would seem to point to the controller receiving additional / too many events when TPR-backed storage is in uses-- events which are no received when etcd-backed storage is in use.

### CODE REVIEW

**Comment by krancour** [comment]
I am currently seeing this some kind of infinite loop wherein resources are being successfully updated over and over again. Trying to pinpoint the cause.

**Comment by arschles** [comment]
@krancour why a complete rewrite? The last discussion we had, I recall you said you were going to refactor the versioner and fix some minor bugs in the storage interface itself.

I'd like to avoid an all-at-once, complete rewrite here.

**Comment by krancour** [comment]
Your recollection of our last discussion seems to differ from mine. I recall telling you that I basically started fresh using the upstream etcd3 based implementation as a starting point and I just differed from it as necessary.

**Comment by arschles** [comment]
@krancour I remember you saying that, but my understanding was that you were doing that as an exercise to figure out what's missing or broken, not to do a rewrite.

A lot of work -- including manual testing -- went into making the existing list/watch/get/create code work, and I'd rather you or anyone else didn't have to redo that work, at least not all in a single PR.

To be clear: I am not against throwing away the TPR based storage implementation and rebuilding if you think that's necessary. I am against doing it all at once.

One idea to mitigate is rewriting the TPR based versioner in a single PR, and then do rewrites of other small-to-medium sized pieces in follow-ups?

**Comment by krancour** [comment]
> A lot of work -- including manual testing -- went into making the existing list/watch/get/create code work, and I'd rather you or anyone else didn't have to redo that work, at least not all in a single PR.

I appreciate what has gone into it, but what exists now doesn't actually work. You'll find you cannot get through the walkthrough using trp-backed storage.

**Comment by arschles** [comment]
@krancour - ok, fair enough. let me know when you'd like a review

**Comment by pmorie** [comment]
Moving to 0.0.3 because this isn't complete.

**Comment by pmorie** [comment]
Moving to 0.0.4 because this isn't done yet.

**Comment by krancour** [comment]
This PR was a hail mary. I was trying to address numerous hard-to-identify issues with tpr-backed storage by rewriting it from the ground up whilst carefully using the upstream etcd3-backed storage impl as a template. It worked to an extent, but the approach hasn't resonated and a more focused effort is currently underway to bulk up unit, integration, and e2e tests to help iteratively identify and correct issues. Closing this.

**Pull request closed without merging**
