### PR TITLE
Fixing install command

### PR DESCRIPTION
**Pull request by seanmck**

### CODE REVIEW

**Comment by staebler** [comment]
@seanmck The installation instructions are for running the helm chart from the https://svc-catalog-charts.storage.googleapis.com repo. Your proposed changes would run the local helm chart instead.

**Comment by krancour** [comment]
@seanmck make sure you've done this first:

```
$ helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
```

And then the `helm install` command will work as it's currently written.

**Comment by seanmck** [comment]
Ah - missed that step, thanks @krancour. I think this part threw me off:

> From the root of this repository:

If it's using the remote chart, that shouldn't matter right?

**Comment by MHBauer** [comment]
dup of #1535 

Should we move step 1 and step 2 closer and move all the middle matter into a notes section?

**Pull request closed without merging**
