### PR TITLE
Move the contents of the script dir to hack/

### PR DESCRIPTION
**Pull request by pmorie**
In kubernetes, we keep the kind of thing that initially went into the `script` directory in the `hack` directory.

@kubernetes-incubator/maintainers-service-catalog

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

one question, just for my own education, why do golang projects use the word "hack" for this kind of stuff?  I actually think "script" makes more sense - I'm not suggesting we use "script" I just want to understand the history behind the word "hack".

**Comment by pmorie** [comment]
@duglin don't know.

**Comment by bgrant0607** [comment]
hack was introduced here, I believe:
https://github.com/kubernetes/kubernetes/pull/10

**Comment by duglin** [comment]
@bgrant0607 yea but that doesn't give the history behind the word "hack", which I've seen used in other golang projects. Always felt like it had a negative connotation to it, as something quick-n-dirty instead of "a place to put scripts we use".  oh well.

**Comment by pmorie** [comment]
'hack' is what i do to have fun, so it has a positive connotation for me.

**Comment by bgrant0607** [comment]
@duglin You could ask the author of the PR. :-)

**Comment by arschles** [comment]
fwiw, I don't think the `hack` directory is something generalized to Go projects

since this seems to follow what kubernetes/kubernetes does, I'm ok with it

**Comment by martinmaly** [comment]
One more file affected by the rename is Jenkinsfile. We should discuss what kind of CI we want for the incubator repo; for the moment we have a private instance of Jenkins we use but I am assuming we'll want some system visible to the group at some point.

**Comment by vaikas-google** [comment]
LGTM

**Comment by arschles** [comment]
LGTM

**Comment by pmorie** [comment]
I'm going to hold tight on this until @arschles fixes the build after #57, since it will change this PR significantly, probably.

**Comment by arschles** [comment]
note that https://github.com/kubernetes-incubator/service-catalog/pull/57 is currently awaiting a CLA bot fix, so up to you if you want to proceed with this patch. I'll take care of any conflicts that may arise in 57, as well as fixing the build.

**Comment by arschles** [comment]
@pmorie #57 is now merged. This is ready to go after conflicts resolved

**Comment by krancour** [comment]
No a blocker for this, per se, but orthogonal to this... we should discuss whether the contents of the `script/` (now `hack/`) directory make assumptions that are an unreasonable hindrance to contributors who don't satisfy those assumptions. Sometimes less is more.

**Comment by duglin** [comment]
rebase needed

**Comment by pmorie** [comment]
@kubernetes-incubator/maintainers-service-catalog PTAL, rebase.

**Comment by duglin** [comment]
CI failure looks real

**Comment by duglin** [comment]
L50 of Makefile needs updating

**Comment by pmorie** [comment]
> L50 of Makefile needs updating

Bizarre, I distinctly remember changing that.

**Pull request merged**
