### PR TITLE
Move ups-broker template to deploy/catalog

### PR DESCRIPTION
**Pull request by martinmaly**
The file was accidentally in the wrong directory.

### CODE REVIEW

**Comment by duglin** [comment]
What is the deploy dir for?  If they're related to one of the samples can we move them to their owning dir?

**Comment by martinmaly** [comment]
At the moment the deploy directory contains a Helm chart which will spin up the service catalog, and the example brokers, inside a k8s cluster:

https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/walkthrough.md#deploying-to-kubernetes

there may be a better place for it (which I'd rather not address in this commit) but I'd be happy to add a README to go in with this. wdyt?

**Comment by duglin** [comment]
ok. LGTM

In the other PR, let's move it under the samples dir since its related to those.

**Comment by arschles** [comment]
LGTM (`LGTM2` label added)

**Comment by pmorie** [comment]
LGTM, merging.

**Pull request merged**
