### PR TITLE
Improve logging during deploy and poll endpoints

### PR DESCRIPTION
**Pull request by mkibbe1993**
Improves the logging of the demo project deployment script, used by Jenkins. Currently, it was using a debug flag that was extremely verbose in output, especially during the waiting loops. This version should strike a bit better balance.

Also polls the endpoints of the services to make sure they're up before continuing with deployment.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

@mkibbe1993 can you do me a favor and open up a PR that moves all of the jenkins files/scripts into "hack/jenkins" dir? I'd like to do some clean-up of "hack" but I'm afraid that I might delete a file that's needed by jenkins. By moving all jenkins files into the same dir we can avoid this confusion.  I'd do it myself but I don't know which files are used by jenkins (including the one at the root of the repo - like run.sh)

**Comment by pmorie** [comment]
LGTM.

@mkibbe1993 you should check out the `test-cmd.sh` test in upstream as an example of how this type of testing is done in k8s.

**Comment by pmorie** [comment]
@krancour can you review this, please?

**Comment by mkibbe1993** [comment]
@duglin Sorry, I've been out sick for a few days. Sure, I can do that.

@pmorie Will do!

**Comment by duglin** [comment]
@mkibbe1993 thanks for the other PR!

**Comment by krancour** [comment]
Sorry for the delay. LGTM. I second @duglin's request that Jenkins-related stuff moves into a directory where it's clear that's what it is. If I can suggest an alternative to the `hack/jenkins` directory that @duglin proposed, please consider `contrib/hack/jenkins`... my rationale is that I think everything that is non-vital should live somewhere under `contrib` such that (if for some imaginative reason) we ever deleted `contrib`, build/test would still pass _and_ we wouldn't be left with a bunch dead code and scripts in `hack/...` or elsewhere.

But that is non-blocking for this PR.

**Pull request merged**
