### PR TITLE
e2e start

### PR DESCRIPTION
**Pull request by MHBauer**
It's really the same exact test as the integration test, but with a differently configured client and no starting of a server internally. 

We need to be able to tell the test, "go and talk to this server". 

I'm waiting for the controller to settle down before I tackle adding that.

Need to also figure out running a broker and add it to the same pod (for testing for now) until we can run this on a cluster where everything runs elsewhere.

I don't know the best-practices on exposing pods, so I copied the example yaml and modified it till it works. 

Process to work is:
 - run kubernetes with dns (I actually don't think this is needed anymore)
 - `kubectl create -f e2e-setup.yaml`
 - `go test e2e_test.go' which looks at localhost for the exposed port 30000 and talks to it using our standard client

### CODE REVIEW

**Comment by pmorie** [comment]
cc @kibbles-n-bytes

**Comment by MHBauer** [comment]
devious idea, `local-up-cluster` *is* available in our vendored repo. We could call that...

**Comment by MHBauer** [comment]
We'd also need to have kubectl inside to do this, or write a client to push the create and delete yamls.

**Comment by MHBauer** [comment]
There's a `kubectl.sh` in vendor I can try.

**Comment by MHBauer** [comment]
`kubectl.sh` requires a built `kubectl` from the k9s build.

If we go with an internal client, we need to get the credentials into running thing somehow. Might be easier to run the e2e as a pod, but I'm not sure how we'd get the results out and make sure it works.

**Comment by pmorie** [comment]
Where @MHBauer and I left this:

Our e2e binary will:

1.  Accept kubeconfigs for core and service-catalog API servers as inputs
2.  Assume that kubernetes and the service-catalog are already deployed

**Comment by MHBauer** [comment]
I'm encountering the same bizarrbitrary choice to munch `restclient.Config` into `client.Config` that made it impossible to use the `client-go/tools` to read a kubeconfig for our code.

**Comment by MHBauer** [comment]
using the existing e2e framework can't work because the version of the k8s repo we have vendored has a symlink for client-go, which get's munged to the published client-go. So, anything in e2e will not compile at the same time as the inclusion of the client-go repo and the glide strip-vendor call we do.

**Comment by pmorie** [comment]
>  So, anything in e2e will not compile at the same time as the inclusion of the client-go repo and the glide strip-vendor call we do.

That seriously sucks -- we might need to put this on the list of things to do after we rebase (I hope this will be next week).  Can you establish that the version in master would work correctly?  It should be using client-go correctly currently.

**Comment by MHBauer** [comment]
still a symlink. The code in the published library does look like an exact copy of master now. No more bizarrbitrary package renaming. Better chance of working.

Closing this for now.

**Pull request closed without merging**
