### PR TITLE
Add metadata fields to ServiceClass and ServicePlan

### PR DESCRIPTION
**Pull request by pmorie**
After discussion w/ @duglin on #287 I decided to just add 'flat' fields directly in these types for now.

### CODE REVIEW

**Comment by MHBauer** [comment]
If they're still OSB specific do we want the OSB prefix?

Also, what is the purpose of changing this?

**Comment by pmorie** [comment]
No, I'm going to take those out of the other fields, too.  The reality is, we are closely following the OSB API for now; designing for other APIs in the future is not currently a goal.

**Comment by MHBauer** [comment]
Oh boy, I sure love these generated changes that obfuscate all the real changes included in the same commit.

**Comment by MHBauer** [comment]
All right, I'm done being a jerk. Can we please have the generated changes separated out from the real changes? Or is there a way to have One real change and one generated change per commit? I'm not familiar with the generation.

**Comment by pmorie** [comment]
I can totally put them into different commits, and normally do, but it was late.

**Comment by duglin** [comment]
LGTM

**Comment by krancour** [comment]
LGTM. The whole bit about separating the changes in generated code into their own commit so we could review just actual changes was extremely helpful. We should all make a habit of that.

**Pull request merged**
