### PR TITLE
Wire storage correctly for broker and binding

### PR DESCRIPTION
**Pull request by pmorie**
After this, the broker and binding resources work correctly in etcd.

### CODE REVIEW

**Comment by MHBauer** [comment]
lgtm contingent on build

**Comment by MHBauer** [comment]
for the historic record, instead of specifying the `StorageDecorator` at the top level, we could specify `generic.UndecoratedStorage` explicitly in each individual store declaration. As it is, all store implementations will use the same decorator function specified at the top level.

**Comment by arschles** [comment]
Ping me when CI is done, I'll merge

**Pull request merged**
