### PR TITLE
dynamically grab latest GKE cluster version for Jenkins

### PR DESCRIPTION
**Pull request by kibbles-n-bytes**
Currently, GKE's default master Kubernetes version is 1.5.6, but the catalog needs >=1.6.0. However, the patch version keeps changing, and there's not way to specify "at least 1.6" when creating a cluster. Until the default is >=1.6.0, manually grab the latest GKE master version from the list of valid versions, and use that for Jenkins.

### CODE REVIEW

**Comment by kibbles-n-bytes** [comment]
@MHBauer I'd be completely shocked if they removed support for 1.6+ at this point, but I'll add in an extra check just to be 100% confident.

**Comment by MHBauer** [comment]
When can expect to see a `v1.7` release pop up? I think that might break the revised script.

**Comment by kibbles-n-bytes** [comment]
Yup, that'll break it, but at that point the workaround shouldn't be necessary. Didn't want to put in anything super heavy duty.

**Comment by pmorie** [comment]
Not for a while. Juneish iirc

**Pull request merged**
