### PR TITLE
Add test for get cmd in cmd/broker folder

### PR DESCRIPTION
**Pull request by jichenjc**
This adds the coverage of unit test by creating new file cmd/svcat/broker/get_cmd_test.go

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
Hi @jichenjc ! I noticed that you closed a few of your PRs recently that seemed related.  If you are having any problems, feel free to come on over to the service-catalog slack channel or send an email to the group list (https://svc-cat.io/community/)! :)

**Comment by jichenjc** [comment]
Thanks a lot , I am new to github flow and service provider code so I failed to pass some CI test and don't know how to refresh the code (e.g I created a PR and it failed in CI , then how to upload code again and make CI pass etc) , for this one (2175) , I created another PR (2178, 2179) and try to address my code by using that PR

**Comment by kikisdeliveryservice** [comment]
No problem, @jichenjc Did you have a look at the [devguide](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/devguide.md)? 

No need to make new PRs in that case! If you made changes to your code locally: add the file in git, commit the change and then just re-push it to the same branch on Github.  That branch is still connected to the Pull Request, so it will update with your new commits on Github. (It's the same idea as a Gerrit patch with a Change-ID.)  The tests will then rerun. If you run the tests locally before you push and they all pass, just take a closer look in the Travis CI link and find what the error is.  Sometimes Travis CI is flakey and it's not you. In that case, let people know on Slack or here in the PR and someone should be able to help you with the CI problem.

While you figure out the flow just put in the title of your PRs: WIP (that's work in progress) so people will know that you are still working on it.

I hope this helps!!

**Comment by jichenjc** [comment]
ok, thanks a lot, I will submit the patch again from local to forked repos and wait for the CI :)

really appreciate  your help and will ask more questions in slack later on if I have :)

**Pull request closed without merging**
