### PR TITLE
Remove unused API fields

### PR DESCRIPTION
**Pull request by pmorie**
Per #813 and #843, remove the dashboard SSO and `maxDBPerNode` fields.

### CODE REVIEW

**Comment by MHBauer** [comment]
Nuke `OSBMaxDBPerNode` while you're deleting things.

**Comment by MHBauer** [comment]
fat fingered it, sorry.

**Comment by pmorie** [comment]
@MHBauer 💣 it's nuked

**Comment by duglin** [comment]
LGTM

**Pull request merged**
