### PR TITLE
Cleanup controller unit test

### PR DESCRIPTION
**Pull request by pmorie**
Extract literal names into constants and reduce number of args returned by `newTestController`.

### CODE REVIEW

**Comment by duglin** [comment]
CI failure

**Comment by simonleung8** [comment]
Missing `testBindingName` const definition, otherwise it is much cleaner. LGTM

**Comment by MHBauer** [comment]
I like constants.

**Comment by duglin** [comment]
LGTM

**Comment by kibbles-n-bytes** [comment]
LGTM

**Pull request merged**
