### PR TITLE
adding query string params to unbind requests

### PR DESCRIPTION
**Pull request by arschles**
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/884

### CODE REVIEW

**Comment by arschles** [comment]
cc/ @ljnelson

**Comment by duglin** [comment]
LGTM

But why did the tests pass before this?

**Comment by arschles** [comment]
@duglin not sure. I was going to address some test improvements in a follow-up.

**Comment by ljnelson** [comment]
@duglin I can't speak to this service-catalog codebase, but I can say that [Grizzly is very by-the-book in this area](https://github.com/javaee/grizzly/blob/2.3.x/modules/http/src/main/java/org/glassfish/grizzly/http/HttpServerFilter.java#L708-L722).

**Comment by krancour** [comment]
The format string used to construct the unbind URL already accounts for these query parameters:

```
bindingDeleteFormatString = "%s/v2/service_instances/%s/service_bindings/%s?service_id=%s&plan_id=%s"
```

> But why did the tests pass before this?

This is why. 😉 

That being said, I do believe that this PR utilizes a more idiomatic way of setting query params, but the format strings used to construct those URLs should also be amended along with this so that we're not doubling up on all the query params.

**Comment by krancour** [comment]
> That being said, I do believe that this PR utilizes a more idiomatic way of setting query params

Apart from being idiomatic, I've also realized that the previous approach (which relied only on format strings) didn't account for any query parameters whose values required url-encoding.

**Comment by arschles** [comment]
Looks like this can be closed in favor of https://github.com/kubernetes-incubator/service-catalog/pull/888. @vaikas-google do you agree?

**Comment by vaikas-google** [comment]
Yes, agreed.

**Comment by arschles** [comment]
ok, closing. thanks

**Pull request closed without merging**
