### PR TITLE
Move broker client into pkg/brokerapi.

### LINKED ISSUE #157: Extract Open Service Broker Client into its own package
Currently, the Open Service Broker Client is under controller/util.  It should be extracted into its own package; I propose `pkg/brokerapi/openservicebroker` as a path.

### PR DESCRIPTION
**Pull request by bmelville**
Fixes #157.

### CODE REVIEW

**Comment by duglin** [comment]
LGTM if CI is ok

**Comment by pmorie** [comment]
LGTM

**Comment by pmorie** [comment]
@arschles @krancour can we get review closed out on this one?

**Comment by arschles** [comment]
LGTM, merging

**Pull request merged**
