### PR TITLE
Fix manual hack of glide.lock file

### PR DESCRIPTION
**Pull request by staebler**
As part of the work for #1517, the glide.lock file was massaged manually to avoid pulling in the latest version of google.golang.org/appengine. This change fixes that by explicitly specifying the appengine version in the glide.yaml file.

When running `glide up && glide i -v`, the only change in the vendor tree is to the vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go file. That file was changed manually as part of #1458. I would like the opinion of @nilebox on whether that change was needed. I don't relish the idea of having to manually ensure that we keep that change around as we run glide updates.

### CODE REVIEW

**Comment by nilebox** [comment]
LGTM. Second that we should never manually change `glide.lock` and `vendor/*`.

> When running glide up && glide i -v, the only change in the vendor tree is to the vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go file. That file was changed manually as part of #1458.

That definitely wasn't my intention. I guess it was an accidental result of some automatic find & replace. Will take a look at this change and revert it.

**Comment by staebler** [comment]
@nilebox I don't think you need to revert anything. This PR will effectively revert that change from your PR. I only wanted to make sure that it wasn't an intentional change on your part that I would be overriding.

**Comment by nilebox** [comment]
@staebler ah cool, I see the change now. Yeah, it was an accidental change replacing `Core` with `CoreV1` (this change is probably still should be made, but in the `apiserver` repo).

**Comment by kibbles-n-bytes** [comment]
LGTM. +1 to never manually editing `glide.lock`. Seems like this solves the last of our current glide woes? :tada:

**Pull request merged**
