### PR TITLE
Update Code of Conduct

### PR DESCRIPTION
**Pull request by mbssaiakhil**
Made the last sentence uniform wrt other sentences

### CODE REVIEW

**Comment by duglin** [comment]
LGTM

**Comment by kibbles-n-bytes** [comment]
It seems like there should also be no period at the end of:

```Other unethical or unprofessional conduct```

(At the end of the bulleted list.) The Contributor Covenant version (http://contributor-covenant.org/version/1/2/0/) does not have one either.

**Comment by MHBauer** [comment]
Can we link somewhere,or do we have to physically have the text present?

**Comment by pmorie** [comment]
Make sure these changes are reflected in the kubernetes/community repo -
that is where this text was taken from.

**Pull request merged**
