### PR TITLE
Added validation for ServiceBinding spec ParametersFrom

### LINKED ISSUE #1691: ServiceBinding parametersFrom attribute is not validated for having no keys
Service Catalog version used: 1.3

If you try to create a ServiceInstance with parametersFrom having empty key:

```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-instance
  namespace: my-namespace
spec:
  externalClusterServiceClassName: my-class
  externalClusterServicePlanName: my-plan
  parametersFrom:
    - secretKeyRef:
        name: my-secret
```
You get an error:

> The ServiceInstance "my-instance" is invalid: spec.parametersFrom.secretKeyRef.key: Required value: key is required

On the other hand, if you attempt to create a ServiceBinding with empty key:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: my-binding
  namespace: default
spec:
  instanceRef:
    name: my-instance
  parametersFrom:
  - secretKeyRef:
      name: my-secret
  secretName: binding-secret
```
Even though, this is incomplete information, binding gets created and the "parametersFrom" looks like that:
```
  parametersFrom:
  - secretKeyRef:
      key: ""
      name: my-secret
```

I believe the second scenario should return an error, akin to what happens in case of ServiceInstance.

### PR DESCRIPTION
**Pull request by witlessbird**
Closes #1691

### CODE REVIEW

**Comment by witlessbird** [comment]
@MHBauer: now that you mention it, I can probably extract common test cases into a single test suite.

**Comment by witlessbird** [comment]
@MHBauer: I realized I'm not sure how to extract test code in such a way it doesn't end up in the main binary (or am I overthinking this?).

I'm also not sure what to make of the test failures...

**Comment by MHBauer** [comment]
@witlessbird rebase after 08af73ff5bda1853c5c30aa15f2389e0900f222f and tests should work.

**Comment by witlessbird** [comment]
* rebased

**Comment by MHBauer** [comment]
looking good.

**Pull request merged**
