### PR TITLE
Workaround spf13/viper stringarray bug

### LINKED ISSUE #1699: svcat provision/bind doesn't parse params properly
When svcat was migrated to this repo, I had to add viper into the mix in order to bind to the kubectl plugin environment variables. This introduced a bug in `svcat provision` and `svcat bind`:

```console
$ svcat provision # ... the args don't matter, as long as --param isn't set
Error: invalid --param value (invalid parameter ([]), must be in name=value format)
```

This is an open issue with viper, https://github.com/spf13/viper/issues/246. Will follow up with a workaround PR shortly.

### PR DESCRIPTION
**Pull request by carolynvs**
Fixes #1699.

* Added failing test for the viper bug
* Refactored our commands so that we can test validation errors

Let me know if you'd prefer that the last commit in this PR (which refactors the remaining commands to be testable), should be split into a separate PR.

### CODE REVIEW

**Comment by MHBauer** [comment]
@jberkhahn Any opinion?

**Comment by MHBauer** [comment]
@carolynvs does the new testing catch the bug as it would have been?

**Comment by jberkhahn** [comment]
I haven't dug into the Cobra stuff yet, so I can't comment on this. I will echo Morgan though, would like a test that shows this is fixed.

**Comment by carolynvs** [comment]
The very first commit added a failing test. The second fixes it and the third commit added arg validation tests for the other commands.

**Pull request merged**
