### PR TITLE
Add securityContext

### PR DESCRIPTION
**Pull request by obeyler**
This PR is a 
 - [X] Feature Implementation
 - [ ] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
This PR add the opportunity to set a securityContext to be able to run serviceCatalog on a K8S with PodSecurityContext set as RunAsNonRoot
If you don't setup securityContext each deployment is staled with this :
image

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [X] New feature 
   - [ ] Tests
   - [X] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by obeyler** [comment]
CLA is signed

**Comment by jberkhahn** [comment]
looks like you need to rebase on master

**Comment by jberkhahn** [comment]
other than that this looks good, will lgtm it when you have it rebased

**Comment by obeyler** [comment]
@jberkhahn rebase done

**Comment by jberkhahn** [comment]
Yeah, I think you messed up your rebase. You're currently showing 1000+ and many commits that are already on master.

**Comment by obeyler** [comment]
Ok I'll will redo a new PR from scratch It will be easier. :-)

**Comment by obeyler** [comment]
I do it again this PR due to bad previous rebase : 
see Add securityContext #2571

**Pull request closed without merging**
