### PR TITLE
Add lastTransitionTime to API conditions

### PR DESCRIPTION
**Pull request by pmorie**
Per #627, add transition time to API conditions and have the controller begin setting it whenever a condition's status changes.

### CODE REVIEW

**Comment by MHBauer** [comment]
Reading the api-conventions doc, LastTransitionTime is described as `last time the condition transit from one status to another`. Is this the same? Do we want to document it explicitly here?

It also describes this field as not necessarily being persisted. Do we need to decide on storing or not storing it and doing something specific in storage code?

**Comment by pmorie** [comment]
> Reading the api-conventions doc, LastTransitionTime is described as last time the condition transit from one status to another. Is this the same? Do we want to document it explicitly here?

Yeah, I will add godoc comments to the new fields and make another PR adding comments to all API fields

> It also describes this field as not necessarily being persisted. Do we need to decide on storing or not storing it and doing something specific in storage code?

It should be stored - I think that comment is pertinent to the fact that you should expect that you might lose status and have to rebuild it from spec.

**Comment by pmorie** [comment]
So, no, there is no additional storage work to do.

**Comment by arschles** [comment]
@pmorie can you rebase this? I believe the changes in #695 should fix the flake in [jenkins](https://service-catalog-jenkins.appspot.com/job/service-catalog-PR-testing2/228/)

**Comment by pmorie** [comment]
@MHBauer 

> How would one reconstruct last transition time from status?

If you don't have a status, you should just re-list the broker.  See #702

**Comment by MHBauer** [comment]
Okay, less reconstruct and more reconcile to throw you into a specific state.

**Pull request merged**
