### PR TITLE
Remove hack/ from repo layout description

### PR DESCRIPTION
**Pull request by krancour**
Ugh... I believed this change to have been included in an amendment to #246, but I was mistaken. (Must have amended the commit and force pushed, but forgot to `git add` the change first. Damnit!)

A million apologies!

cc @duglin

### CODE REVIEW

**Comment by arschles** [comment]
This is a 1 line removal from the documentation that was already approved in a previous PR. I'm merging this now, and happy to revert if anybody has an issue with it later.

**Comment by krancour** [comment]
ty @arschles

**Comment by duglin** [comment]
retroactive lgtm :-)

**Comment by arschles** [comment]
thx @duglin 👍

**Pull request merged**
