### PR TITLE
Add some design docs

### PR DESCRIPTION
**Pull request by duglin**
This is far from complete but I decided to put it out there for people to start to comment on to see if its headed in an ok direction.  If the base direction is ok then we can merge it and submit subsequent PRs to expand on the missing pieces.

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by mdshuai** [comment]
:+1:

**Comment by arschles** [comment]
@duglin CI is failing on this:

```console
build/../docs/design.md: Can't find anchor '#current-design'
```

Otherwise, LGTM

**Comment by duglin** [comment]
fixed broken link @arschles thanks!

**Comment by arschles** [comment]
@duglin what is the status of this PR?

**Pull request merged**
