### PR TITLE
fix log output to use formatted output

### PR DESCRIPTION
**Pull request by MHBauer**
fix for https://github.com/kubernetes-incubator/service-catalog/pull/1053#discussion_r128422201

### CODE REVIEW

**Comment by nilebox** [comment]
LGTM

**Comment by arschles** [comment]
Since this PR fixes an obvious bug on master, I am going to merge after travis runs.

**Comment by nilebox** [comment]
Either Travis or Jenkins should be enough, as they both include building the sources.

**Comment by arschles** [comment]
Thanks for merging @nilebox!

**Pull request merged**
