### PR TITLE
Not all shells set PWD

### PR DESCRIPTION
**Pull request by wryun**
CURDIR is guaranteed to be there by Make.

### CODE REVIEW

**Comment by MHBauer** [comment]
@wryun I'm surprised you're not under the corporate cla for atlassian, we already have @nilebox and @ash2k

**Comment by wryun** [comment]
Just had my primary github email set incorrectly. I think it should be fine now (assuming that this comments redoes the CLA check, as hinted at by the bot).

**Comment by MHBauer** [comment]
kicked travis to see if we can get under the build limit

**Comment by MHBauer** [comment]
What is `$(PWD)`? Some convenience function for `$(shell pwd)`?

https://www.gnu.org/software/make/manual/make.html#index-CURDIR

**Comment by MHBauer** [comment]
oh, derp, `PWD` is literally the environment variable

**Comment by wryun** [comment]
Thanks - I'm probably the only one who will be affected by this, but it tripped me up 3 months ago and I'd forgotten it when I went to poke Service Catalog again yesterday.

**Comment by duglin** [comment]
Lgtm

**Comment by MHBauer** [comment]
@wryun what shell are you running?

**Comment by wryun** [comment]
https://wryun.github.io/es-shell/ (I didn't write it, just made a website)

**Pull request merged**
