### PR TITLE
Proposal for CRDs as a backing store.

### PR DESCRIPTION
**Pull request by n3wscott**
Starting point.

### CODE REVIEW

**Comment by ash2k** [comment]
https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/rHEoQ8cgYwk

**Comment by nilebox** [comment]
@n3wscott have you discussed this idea with API machinery folks? Last time we checked it was not recommended to use CRD as a backing store for API server.

**Comment by nilebox** [comment]
Also I agree that it might be better to join forces with https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/rHEoQ8cgYwk project to get it done properly.

**Comment by n3wscott** [comment]
Looks like that proposal is DOA:

> No, we should absolutely not do this.

I have had several reviews and the google side of k8s thinks it is a fine medium term solution to use CRDs as a backing store with caveats

**Pull request closed without merging**
