### PR TITLE
Initialize ClusterServiceBroker/ServiceBroker client only on add/update actions

### LINKED ISSUE #2492: Cannot delete ClusterServiceBroker/ServiceBroker when wrong auth is specified
# Bug Report 

**What happened**:
The ClusterServiceBroker/ServiceBroker cannot be deleted when specified auth Secret does not exist.

**What you expected to happen**:
The ClusterServiceBroker/ServiceBroker can be deleted even if they are in error state because of the missing Secret.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create ClusterServiceBroker/ServiceBroker with incorrect auth.
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBroker
metadata:
  name: misconfigured-broker
  namespace: default
spec:
  url: http://dummy.com
  authInfo:
    basic:
      secretRef:
        name: not-existing-creds 
```
2. Delete created ServiceBroker
```bash
kubectl delete ServiceBroker misconfigured-broker
```

Then the `deletionTimestamp` is set, but ServiceBroker resource is never deleted. 

**Troubleshooting**:
The problem is that the ClusterServiceBroker/ServiceBroker clients are always initialized. They should be created only in case of add or update action as it was previously, see: https://github.com/kubernetes-incubator/service-catalog/pull/2337/files#diff-1aa1085b3dd6f459f3f1e5d2ec2ec35bL138

[This](https://github.com/kubernetes-incubator/service-catalog/pull/2493) small PR fixes this problem.

### PR DESCRIPTION
**Pull request by mszostok**
This PR is a 
 - [ ] Feature Implementation
 - [x] Bug Fix
 - [ ] Documentation

**What this PR does / why we need it**:
This PR fixes problem with deleting ClusterServiceBroker/ServiceBroker when they are in error state because of the missing Secret.

**Which issue(s) this PR fixes** 
Fixes #2492

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] New feature 
   - [ ] Tests
   - [ ] Documentation
 - [ ] SVCat CLI flag
 - [ ] Server Flag for config
   - [ ] Chart changes
   - [ ] removing a flag by marking deprecated and hiding to avoid
         breaking the chart release and existing clients who provide a
         flag that will get an error when they try to update

### CODE REVIEW

**Comment by mszostok** [comment]
Hi @luksa, I checked all test cases create for the **ClusterServiceBroker** and I found test `TestReconcileClusterServiceBrokerDelete`, so I modified it and added coverage for the problem from  #2492.
Another option is to create a new test similar to [this one](https://gist.github.com/mszostok/c0d18319b08acf444b116fdd187f9afe#file-sc-testing-go-L27-L85) but IMO it’s easier to have this contract defined in one test. What is your opinion? 

Due to the fact that there were no tests for**ServiceBroker**, I added there exactly the same as defined in **ClusterServiceBroker**.

If you think that it should be handled in a different way then I will update my PR :) 

Here is the test output when someone will break the contract
```
--- FAIL: TestReconcileClusterServiceBrokerDelete (0.01s)
    --- FAIL: TestReconcileClusterServiceBrokerDelete/no_auth (0.00s)
        controller_clusterservicebroker_test.go:677: Unexpected broker client update action
    --- FAIL: TestReconcileClusterServiceBrokerDelete/basic_auth (0.00s)
        controller_clusterservicebroker_test.go:677: Unexpected broker client update action
        controller_test.go:2061: [{ActionImpl:{Namespace:test-ns Verb:get Resource:{Group: Version:v1 Resource:secrets} Subresource:} Name:auth-secret}]
        controller_test.go:2055: goroutine 4 [running]:
            runtime/debug.Stack(0xc00037e000, 0xc0003bfbc0, 0x10f33c5)
                /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
            github.com/kubernetes-incubator/service-catalog/pkg/controller.fatalf(0xc0003a8100, 0x1f56da8, 0x3f, 0xc0003bfc40, 0x3, 0x3)
                /Users/i331808/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_test.go:2055 +0x26
            github.com/kubernetes-incubator/service-catalog/pkg/controller.assertNumberOfActions(0xc0003a8100, 0xc00041d4c0, 0x1, 0x1, 0x0)
                /Users/i331808/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_test.go:2062 +0x20a
            github.com/kubernetes-incubator/service-catalog/pkg/controller.TestReconcileClusterServiceBrokerDelete.func1(0xc0003a8100)
                /Users/i331808/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_clusterservicebroker_test.go:684 +0x898
            testing.tRunner(0xc0003a8100, 0xc00041c900)
                /usr/local/go/src/testing/testing.go:827 +0xbf
            created by testing.(*T).Run
                /usr/local/go/src/testing/testing.go:878 +0x353
            
        controller_test.go:2056: Unexpected number of actions: expected 0, got 1;
            actions: [{ActionImpl:{Namespace:test-ns Verb:get Resource:{Group: Version:v1 Resource:secrets} Subresource:} Name:auth-secret}]
    --- FAIL: TestReconcileClusterServiceBrokerDelete/bearer_auth (0.00s)
        controller_clusterservicebroker_test.go:677: Unexpected broker client update action
        controller_test.go:2061: [{ActionImpl:{Namespace:test-ns Verb:get Resource:{Group: Version:v1 Resource:secrets} Subresource:} Name:auth-secret}]
        controller_test.go:2055: goroutine 16 [running]:
            runtime/debug.Stack(0xc00037e0f0, 0xc0003bfbc0, 0x10f33c5)
                /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
            github.com/kubernetes-incubator/service-catalog/pkg/controller.fatalf(0xc0003a8700, 0x1f56da8, 0x3f, 0xc0003bfc40, 0x3, 0x3)
                /Users/i331808/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_test.go:2055 +0x26
            github.com/kubernetes-incubator/service-catalog/pkg/controller.assertNumberOfActions(0xc0003a8700, 0xc0000c9800, 0x1, 0x1, 0x0)
                /Users/i331808/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_test.go:2062 +0x20a
            github.com/kubernetes-incubator/service-catalog/pkg/controller.TestReconcileClusterServiceBrokerDelete.func1(0xc0003a8700)
                /Users/i331808/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_clusterservicebroker_test.go:684 +0x898
            testing.tRunner(0xc0003a8700, 0xc00041d530)
                /usr/local/go/src/testing/testing.go:827 +0xbf
            created by testing.(*T).Run
                /usr/local/go/src/testing/testing.go:878 +0x353
            
        controller_test.go:2056: Unexpected number of actions: expected 0, got 1;
            actions: [{ActionImpl:{Namespace:test-ns Verb:get Resource:{Group: Version:v1 Resource:secrets} Subresource:} Name:auth-secret}]
FAIL
FAIL    github.com/kubernetes-incubator/service-catalog/pkg/controller  0.066s
```

as you can see, there are two valuable information
`controller_clusterservicebroker_test.go:677: Unexpected broker client update action`
and
`controller test.go:2056: Unexpected number of actions: expected 0, got 1;` in case of the `kubeActions := fakeKubeClient.Actions()` assertion.

the stack trace is not something that I've added. Is printed by default by your method, see: https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_test.go#L2054-L2057

IMO worth to removed the stack trace printing and replaced it with `t.Helper()`. I tested that and the test output is more readable:
```
=== RUN   TestReconcileServiceBrokerDelete
--- FAIL: TestReconcileServiceBrokerDelete (0.00s)
=== RUN   TestReconcileServiceBrokerDelete/no_auth
    --- FAIL: TestReconcileServiceBrokerDelete/no_auth (0.00s)
        controller_servicebroker_test.go:150: Unexpected broker client update action
=== RUN   TestReconcileServiceBrokerDelete/basic_auth
    --- FAIL: TestReconcileServiceBrokerDelete/basic_auth (0.00s)
        controller_servicebroker_test.go:150: Unexpected broker client update action
        controller_servicebroker_test.go:157: [{ActionImpl:{Namespace:test-ns Verb:get Resource:{Group: Version:v1 Resource:secrets} Subresource:} Name:auth-secret}]
        controller_servicebroker_test.go:157: Unexpected number of actions: expected 0, got 1;
            actions: [{ActionImpl:{Namespace:test-ns Verb:get Resource:{Group: Version:v1 Resource:secrets} Subresource:} Name:auth-secret}]
=== RUN   TestReconcileServiceBrokerDelete/bearer_auth
    --- FAIL: TestReconcileServiceBrokerDelete/bearer_auth (0.00s)
        controller_servicebroker_test.go:150: Unexpected broker client update action
        controller_servicebroker_test.go:157: [{ActionImpl:{Namespace:test-ns Verb:get Resource:{Group: Version:v1 Resource:secrets} Subresource:} Name:auth-secret}]
        controller_servicebroker_test.go:157: Unexpected number of actions: expected 0, got 1;
            actions: [{ActionImpl:{Namespace:test-ns Verb:get Resource:{Group: Version:v1 Resource:secrets} Subresource:} Name:auth-secret}]
FAIL
```
and the line number points to the correct line in your test. I could take care of it, but it should be addressed by another task.

This feature was introduced in [Go 1.9 relase](https://blog.golang.org/go1.9). More about the `t.Helper()` behaviour you can read [here](https://routley.io/tech/2017/11/05/intermediate-go-testing.html#helper-functions).


Additionally, I found such test in *controller_servicebroker_test.go*
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_servicebroker_test.go#L34-L42
I truly do not understand what is the purpose of this test? and how the service broker can be covered by the cluster test cases? IMO it's misleading and should be removed.

**Comment by jboyd01** [comment]
Nice update @mszostok.  I like the use of t.Helper() and I was unaware of it.  Thanks!

@luksa has been doing a lot of cleanup of tests for reconciler rework, he's probably in the best position to comment regarding https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_servicebroker_test.go#L34-L42 

/lgtm

**Pull request merged**
