### PR TITLE
Check in vendor directory

### PR DESCRIPTION
**Pull request by pmorie**
Over the last 8 or so days, I've been working with @jpeeler on getting roundtripping of API objects to work.  This involved a ton of deep dives in k8s code and adding debugging statements to upstream code.  Doing this was prohibitively difficult due to the fact that we do not let git track the vendor directory.  I think we have reached the point where we need to change that.

Arguments for:

1.  Easy to manage changing code for dependencies in order to debug
2.  Easy to collaborate on (1) by using a shared branch in git
3.  Much easier to create patches and feed back changes into upstream from these debugging runs (which is something I have done numerous times when debugging problems in OpenShift, which also vendors the k8s repo)

### CODE REVIEW

**Comment by MHBauer** [comment]
I will never not boo the concept of committing 4.8 million lines of code.

**Comment by pmorie** [comment]
For the record, I've removed the `glide install` invocation from the Makefile, since we should now be building based on the state of the `vendor` directory.

**Comment by MHBauer** [comment]
I would like to understand the problems you encountered. If you both checked out the same commit, what was getting out of sync?

**Comment by pmorie** [comment]
@MHBauer 

> I would like to understand the problems you encountered. If you both checked out the same commit, what was getting out of sync?

There's no easy way to share the debugging changes you've made to files that aren't tracked by git.

**Comment by MHBauer** [comment]
So there were changes being made to stuff in vendor?

**Comment by pmorie** [comment]
Correct - not functional, debugging only. Not intended to be checked in.

**Comment by MHBauer** [comment]
Couldn't we check vendor into a branch to debug, do the debug, and then remove the vendor commit at the end? Help me understand the steps to doing vendor check in temporarily vs permanently. I'm going to go poke at it now.

**Comment by pmorie** [comment]
We could do that, but it's a process that involves hacking up the makefiles
and dockerfiles.  I feel like you shouldn't have to hack up the repo to do
this type of basic debugging.  I expect that we are going to be doing thus
A LOT as we begin using k8s code, and think that trying to repeat some
manual process each time is going to be burdensome and error prone.

Let me be honest here: I really do not understand what the objections to
this approach are based on except personal subjective taste. You literally
have to download the same bits if you let glide manage the directory.

**Comment by duglin** [comment]
maybe its in here and I missed it, but what's the process for updating the vendor dir since you erased glide from scbuildimage?

**Comment by MHBauer** [comment]
Is it correct to flatten the kubernetes `vendor/` into our own?

**Comment by MHBauer** [comment]
What is the makefile hacking?

**Comment by MHBauer** [comment]
Ah, I see, the glide steps. I don't think we should automatically call glide for exactly that reason, but that's my fault.

**Comment by pmorie** [comment]
You have to remove all glide installs frothe makefile and dockerfiles,
remove the line from gitignore, check in the vendored code.  This also
means you have to push the vendored code every time you have to debug an
issue like this.

Like I said, I do not personally understand objections to this as anything
but a style thing.  I'm willing to listen if someone can make the argument.

**Comment by krancour** [comment]
This is so that we can more easily share modifications to dependencies? The upstream repos should be the book of record for each dependency; not our tainted copies of them. There's just way too much that can go wrong here. When you submit a PR that upgrades any dependencies, there could be thousands of lines of changes added as a result-- changes that are for all practical purposes unreviewable-- unreviewable, but _not_ unimportant because we build against them. This just sounds awful to me.

**Comment by pmorie** [comment]
It's both for collaborative debugging and creating patches to dependencies
to feed back debugging enhancements into them.

We can add a verify script that checks the integrity of the vendor
directory based on the glide yaml and lock - that should work to mitigate
risks you are concerned about.

I'm perfectly happy not to do this if someone can show me a better way.

**Comment by pmorie** [comment]
@MHBauer @krancour All of the go projects that I personally work on commit their vendored dependencies, so I'm extremely curious how you two handle this situation:

1.  I need to debug some problem
2. Hey, it looks like it goes into dependency X, which is missing meaningful debugging code in this area or missing the kind of debugging code I need
3. I add some debugging code and get closer, but dang, I just cannot figure it out; let me see if trusted work pal and colleague can help
4. I want to pass the exact same state easily in git to my trusted pal so they don't have to hunt around like I just did
5. Sweet, we finally figured out the problem, and I want to push changes into dependency X to make this easier for the next person to debug

For me, this happens almost every time I need to debug something, and I find committing the vendored code is a great facilitator of working through these problems.

As I said, if someone can show me a way which is objectively better, I'm happy to go that way.

**Comment by MHBauer** [comment]
I think one of the points of accepting glide initially was that glide could handle this scenario. Is it possible to create a customized k8s branch with debug info and temporarily point at it?

**Comment by pmorie** [comment]
> I think one of the points of accepting glide initially was that glide could handle this scenario. Is it possible to create a customized k8s branch with debug info and temporarily point at it?

This would be an acceptable solution for me, I think. I'll look into this tomorrow, but if someone wants to chime in with a link I wouldn't mind.

**Comment by pmorie** [comment]
Hrm, looks like this might be what I am looking for:

https://glide.readthedocs.io/en/latest/commands/#glide-mirror

**Comment by krancour** [comment]
I was going to suggest the same.

**Comment by MHBauer** [comment]
I'd be interested to know if mirror does what you want.

I used the a modification of glide.yaml
```
  version: customized-k8s
  repo: https://github.com/MHBauer/kubernetes.git
```
then a `glide update -v`
then build the apiserver `go build -i -v cmd/apiserver/apiserver.go`
then run and we should see an upstream change
```
./apiserver --etcd-servers http://localhost:2379
W0112 21:49:36.497262   66237 authorization.go:33] Authorization is disabled
W0112 21:49:36.497336   66237 handlers.go:50] Authentication is disabled
E0112 21:49:36.497407   66237 genericapiserver.go:264] INSTALLING APIS UPSTREAM
I0112 21:49:36.499832   66237 apiserver.go:127] Finished installing API groups
[restful] 2017/01/12 21:49:36 log.go:30: [restful/swagger] listing is available at https://192.168.0.12:6443/swaggerapi/
[restful] 2017/01/12 21:49:36 log.go:30: [restful/swagger] https://192.168.0.12:6443/swaggerui/ is mapped to folder /swagger-ui/
I0112 21:49:36.500948   66237 server.go:201] Running the API server
I0112 21:49:36.500954   66237 serve.go:79] Serving securely on 0.0.0.0:6443
```
The line `E0112 21:49:36.497407   66237 genericapiserver.go:264] INSTALLING APIS UPSTREAM` comes from a change in my fork of k8s upstream.

Can checkout this branch on my fork `https://github.com/MHBauer/service-catalog/tree/my-upstream`

**Comment by pmorie** [comment]
I think I am convinced, just going futz around with this for a bit, closing this PR for now.

**Pull request closed without merging**
