### PR TITLE
Podpreset initializer

### PR DESCRIPTION
**Pull request by droot**
This PR implements PodPreset functionality using Kubernetes Initializers.

* Note for Reviewers *
This PR is built on top of branch which implements PodPreset APIs.
I have called main object "initializer" to reflect the functionality better but I am open to renaming it podpresetController if people think that is the correct name for it.

### CODE REVIEW

**Comment by MHBauer** [comment]
I am confused. If the point of the initializers is that they are separate and not compiled in to our apiserver, do we really want them compiled into the controller? Shouldn't it be it's own thing? This is getting kind of mind-bending for me.

**Comment by droot** [comment]
@MHBauer Re: Initializer "being separate" refers to the fact that they are NOT compiled in kubernetes core api-server. They do need to be compiled in an external controller (in this case svc-catalog controller) and if they need any API resource for their behavior like in our case PodPreset, you need an api-server as well for resource definition as well.

**Comment by nilebox** [comment]
@pmorie @jpeeler is there anything useful left in this PR after you've merged #1694 We should probably close it.

**Comment by jpeeler** [comment]
If you really want to close this now you can, but I have a PR that is a rebased version of the code here coming soon. And I'll make sure to close this PR once that PR is submitted. But yes, this code is required for pod presets to actually do anything.

**Pull request closed without merging**
