### PR TITLE
Refactor Jenkins tests and base them on automated client.

### PR DESCRIPTION
**Pull request by mkibbe1993**

### CODE REVIEW

**Comment by arschles** [comment]
Can we put Jenkins related stuff into `hack/jenkins` from here on out?

**Comment by mkibbe1993** [comment]
Sorry guys, all the file locations and such are all over the place at the moment due to differing conventions, I'm on it.

**Comment by mkibbe1993** [comment]
Alright, things should be moved all into 'hack/' now. I didn't move stuff into 'hack/jenkins' because the intent with these scripts is that they were created in order to be able to use them by Jenkins, but they should be general purpose and able to be used locally. They do rely on you deploying to a GCP project, however, but the intent was to later remove that coupling.

**Comment by arschles** [comment]
@mkibbe1993 thanks! I've created https://github.com/kubernetes-incubator/service-catalog/issues/143 for follow-up work to decide on the best location and do the moves.

I'd like to err on the side of expediency here (and in many other e2e-related PRs), as I believe that a solid foundation of e2e tests is important for us to have before we start making major functional changes to the codebase.

**Comment by arschles** [comment]
LGTM (`LGTM2` label added)

**Comment by arschles** [comment]
needs rebase

**Comment by martinmaly** [comment]
Are there any pending concerns with this PR that would prevent merging? If so, might we unblock the e2e testing work by opening issues for what remains and doesn't have issue already? Thanks, @arschles for opening #143!

**Comment by duglin** [comment]
LGTM

**Pull request merged**
