### PR TITLE
[WIP] Update .travis.yml to run the repo-sync job

### PR DESCRIPTION
**Pull request by viglesiasce**
Starting the process of moving the chart sync to Travis when tags are submitted.

TODO:

- [x]  [Encrypt JSON service account key](https://docs.travis-ci.com/user/encryption-keys/#Usage)
- [x]  Add encrypted key to .travis.yml
- [ ]  Ensure normal CI for PRs works as expected

### CODE REVIEW

**Comment by MHBauer** [comment]
yes, both blunderbuss and wip plugin worked! @carolynvs

**Comment by MHBauer** [comment]
@viglesiasce do one of us with access to travis need to do the encryption step? Do you need to pass the key to us to encrypt, or can you pass us the encrypted value?

**Comment by viglesiasce** [comment]
So it looks like someone with Travis admin-ish access needs [to encrypt the secret file](https://docs.travis-ci.com/user/encrypting-files/). I can work with someone to provide the file. The steps I used were as follows:

```shell
docker run -it -v `pwd`:/tmp/svc-cat ruby bash
cd /tmp/svc-cat
gem install travis
travis login --org
travis encrypt-file service-account.json -r kubernetes-incubator/service-catalog 
```
This will add the decryption key as an ENV in the Travis stages. We'll then need to:

1. Check in the encrypted file
2. Decrypt it using openssl in the before_install phase

**Comment by carolynvs** [comment]
@viglesiasce I can do that. Will ping you for the top secret file of doom on slack.

**Comment by carolynvs** [comment]
Due to a bug in our travis file, this PR must be rebased in order to get the CI build to run for this PR.

**Comment by MHBauer** [comment]
not sure why it says `iv undefined` the var is present.

Not sure what the contents are, all I can think of is adding quotes or something. The value should be some hex string.

**Comment by carolynvs** [comment]
@MHBauer I was the one who encrypted the file for Vic since I had access to GitHub. Perhaps I did it wrong? I basically just ran the commands he gave me.

**Comment by MHBauer** [comment]
I guess it's possible. Do you still have the file or should I go to Vic if I want to give it a try?

**Comment by carolynvs** [comment]
@MHBauer I'll follow up with you on Slack so that you can try it yourself.

**Comment by MHBauer** [comment]
hopefully superseded by #2147. We should know today or tomorrow based on performing a release.

**Comment by MHBauer** [comment]
maybe fixed for good by https://github.com/kubernetes-incubator/service-catalog/pull/2173

Let's wait for one successfull release with the process and then close this.

**Comment by MHBauer** [comment]
this is complete. we had a successfull automated release last night.
v0.1.27
https://travis-ci.org/kubernetes-incubator/service-catalog/jobs/408306861
/close

**Pull request closed without merging**
