### PR TITLE
Add namespace flags to get plans

### PR DESCRIPTION
**Pull request by artmello**
Closes: #2243

### CODE REVIEW

**Comment by carolynvs** [comment]
@jberkhahn what do you think about us adding owners files to the cli so that we are automatically tagged as reviewers on PRs like this? I think that's a thing? 🤔

**Comment by jberkhahn** [comment]
I thought it was already a thing but the top level owners also count and it randomly picks 2? If you can figure out a way to make it bug us specifically that sounds good.

**Comment by jboyd01** [comment]
@artmello This looks like a great start.  As @jberkhahn indicated the golden output file needs to be updated as its failing unit tests.

I think output needs to be adjusted so we can differentiate between cluster and namespace scoped plans.  The command `svcat get classes` added a column that specified namespace (blank for cluster) - I think we should probably do the same here (Name/Namespace/Class/Description)

@artmello it would be awesome if you can update, we've got users that would love to see this functionality in svcat.

**Comment by artmello** [comment]
@jberkhahn / @jboyd01 Thanks a lot for reviewing. I added the new "Namespace" column when showing Plans table output. Hopefully with latest commits the issues with unit tests are gone.

**Comment by jboyd01** [comment]
Nice work @artmello.  As I was reviewing I realized that a related issue that wasn't discussed in #2243 was the describe command.  I'll open a new issue for it though, I don't see a reason to hold up the work you did here.
/approve

**Comment by jboyd01** [comment]
just a follow up to my last comment - - #2216 was already created covering namespace scope for describe

**Pull request merged**
