### PR TITLE
Run tpr-backed storage int tests using real apiserver

### LINKED ISSUE #693: Make TPR integration tests run against a real Core API server
Current TPR integration tests use a fake rest API client to mock out the core API server. The TPR tests are mirrors of the etcd based tests, but we had to cut the codepaths for TPR in these tests short because they didn't pass. I'd like us to execute against a real server for two reasons:

1. We won't have to maintain a fake client & keep parity with the real TPR API
2. We can be sure that test failures expose bugs in our TPR storage implementation (not the fake client)

After this is done, we should re-enable all of the tests for TPR storage (the same code that tests etcd) and create one issue (as necessary) for each bug in our TPR storage implementation.

_Note_: @krancour has significant knowledge on what we've done with the fake client and he has done work to begin running a core server in the same process as the tests in https://github.com/kubernetes-incubator/service-catalog/pull/683.

cc/ @pmorie

### PR DESCRIPTION
**Pull request by krancour**
Fixes #693 

This swaps a real core apiserver client for a real core apiserver in for the mocked out core apiserver client that was previously used.

This is absolutely critical for identifying and troubleshooting the numerous issues that exist with tpr-backed storage, as the mocked out apiserver client doesn't seem to behave with sufficient similarity to the real thing.

Note that I have also been able to re-enable a small subset of previously-disabled integration tests-- which is how we know this is all working. 😄 

__Current state:__ Tests pass... and then the integration test process crashes anyway. It looks like it is OOM. If I watch the memory in my Docker VM locally, these tests are eating up 4GB of memory by the end. I suspect that either the catalog apiserver or core apiserver is leaking memory (as opposed to the tests themselves).

I am going to take a step back from this for a few days and let some others see if they can't put their finger on what's going on.

### CODE REVIEW

**Comment by arschles** [comment]
@krancour to disable auth from the command line invocation of the server, we use `--insecure-bind-address` and `--insecure-port`.

In this PR's code, it looks like you're setting an insecure bind port [here](https://github.com/kubernetes-incubator/service-catalog/pull/683/files#diff-5355822fb692e615dc2e6bea3e0a924cR69) already, but not an insecure bind address.

Perhaps setting up that address and configuring the client to hit that would work. I think you're gonna have to do some experimentation to find out.

**Comment by pmorie** [comment]
@arschles @krancour I think we can close this one out now, agree?

**Comment by krancour** [comment]
@pmorie let's discuss on Monday.

**Comment by krancour** [comment]
Closing since #693 was closed.

**Pull request closed without merging**
