### PR TITLE
Adding a glossary of commonly used terms

### PR DESCRIPTION
**Pull request by arschles**
The terms herein will be used in future documents that make progress toward completing https://github.com/kubernetes-incubator/service-catalog/issues/14

This patch partially replaces #13 

cc/ @pmorie @bgrant0607 @duglin @judkowitz @slack @MHBauer 

TODO: 

- [x] Rework this into the `README.md`

### CODE REVIEW

**Comment by pmorie** [comment]
I'm good with this, if @krancour's comment is addressed.

**Comment by duglin** [comment]
agree with @krancour's comments.
Should this be in the README or in the API docs?   I was reviewing https://github.com/kubernetes-incubator/service-catalog/pull/18/files and it defines some terms in there too.  Seems like we should merge them.

**Comment by krancour** [comment]
@pmorie, @arschles gave me write access to his fork while he's abroad. I've amended the PR to address the outdated diff we'd previously discussed. This is ready for re-review.

**Comment by duglin** [comment]
I think more CLAs are needed.

**Comment by krancour** [comment]
@arschles and I _should_ both be all set CLA-wise. Not sure what's going on here.

**Comment by bgrant0607** [comment]
@krancour I know Google's CLAbot didn't work on PRs with commits from multiple authors. Perhaps this is also the case with the LF CLAbot.

**Comment by arschles** [comment]
RE @krancour's earlier comment - I am also registered under the deis org's LF CLA, and all of my PRs have failed the CLA bot.

I'm guessing it's because the LF account page can't connect my GH account

**Comment by duglin** [comment]
geez I wish we would just use DCOs  :-)

**Comment by arschles** [comment]
Superseded by #25. Closing

**Pull request closed without merging**
