### PR TITLE
rename cmd/controller-manager/main.go to controller-manager.go

### PR DESCRIPTION
**Pull request by mdshuai**
Aligned with cmd/apiserver/apiserver.go

### CODE REVIEW

**Comment by pmorie** [comment]
Please hold until after rebase lands

**Comment by pmorie** [comment]
@mdshuai rebase needed

**Comment by arschles** [comment]
@mdshuai can you rebase this please?

**Comment by pmorie** [comment]
@mdshuai can you rebase this or close it?

**Comment by mdshuai** [comment]
@pmorie sorry late, rebased.

**Pull request merged**
