### PR TITLE
apiserver storage and resource

### PR DESCRIPTION
**Pull request by MHBauer**
next 'simplest change that achieves something'. I'm not sure valid this is as forward progress, and I don't really understand most of it. I was copying stuff from `kubernetes-discovery` and the `federation` servers.

if you go back one commit, you can see a different storageFactory. I don't understand the difference, but this final version is simpler/less code.

unfortunately it breaks all the kubectl communication. error is `error: server does not support API version "v1"`. Error even for `kubectl version`, which worked before.

It does look for etcd, so that has to be running. remember to have set your ` --etcd-servers` flag e.g.  `--etcd-servers http://localhost:2379` for the default etcd listener.

More stuff shows up in curl, which I took as progress. I do not know how to manipulate it if it can be manipulated.
```
#  curl --cacert /var/run/kubernetes/apiserver.crt https://localhost:6443/apis/servicecatalog.k8s.io/v1alpha1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "servicecatalog.k8s.io/v1alpha1",
  "resources": [
    {
      "name": "servicecatalog",
      "namespaced": true,
      "kind": "Broker",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ]
    }
  ]
}
```

I don't like that the smallest I can make this is a several hundred line change, but please help me to understand it more.

### CODE REVIEW

**Comment by arschles** [comment]
@MHBauer should we close https://github.com/kubernetes-incubator/service-catalog/pull/186 in favor of this? I'm totes cool with that if so

**Comment by MHBauer** [comment]
I think #186 probably has a better directory structure.

**Comment by pmorie** [comment]
The API bits in this PR are useful and needed (unfortunately, yes, we make List types for now).

**Comment by duglin** [comment]
@MHBauer is this ready to be merged? If so, can you fix the CI failure so people can LGTM it?

**Comment by pmorie** [comment]
@duglin @MHBauer #216 should probably incorporate the bits in this PR that aren't already in, it is a bit further along than this one

**Comment by MHBauer** [comment]
closing in lieu of #216 et al.

**Pull request closed without merging**
