### PR TITLE
Merge contents of hack dir into build dir

### PR DESCRIPTION
**Pull request by krancour**
Per conversation in #246, this PR merges the contents of the `hack/` directory into the `build/` directory since even upstream in k8s, the distinction between what goes in one directory vs the other does not seem clear.

cc @duglin @pmorie

### CODE REVIEW

**Comment by duglin** [comment]
Would anyone object to moving "run.sh" into "build" too?  Then all of our scripts are in one dir.

**Comment by duglin** [comment]
LGTM

**Comment by krancour** [comment]
@duglin, what does our `run.sh` do, precisely? My concern is that k8s has a `build/run.sh` that is a script for executing any arbitrary command in their build container. I'm not digging the idea of having a script with the same name and in the same location as k8s that does something totally different.

**Comment by duglin** [comment]
I think its just a wrapper to run some tests, but i'm not 100% sure.  Perhaps we could rename it to something more meaningful at the same time? or move it to "contrib/bin", which I'm kind of thinking of a good spot for generic scripts that aren't technically related to build but still useful for devs.

But it also looks pretty specific to one env (certainly not mine) so unless someone adds some docs on how to use it I also wouldn't mind just deleting it  :-)

**Comment by krancour** [comment]
@duglin... I agree with you... you and I have had our hands on the build a lot. There are lots of scripts and Jenkins related stuff to that seems non-essential... at the very least has nothing to do with our ability to build and test either locally or on our public CI (i.e. Travis). I'd like to see more non-essential things move into contrib.

**Comment by krancour** [comment]
@duglin I don't want the scope of this PR to creep too much. If we can just agree on a new name for `run.sh`, I will rename it and move it to `build/`. Though I am in favor of it, moving that and other pieces to somewhere in `contrib/` can be handled in a separate PR.

Thoughts on the right name for that one script? I welcome suggestions from others as well.

**Comment by duglin** [comment]
maybe "sniffTest" ??

**Comment by mkibbe1993** [comment]
@duglin Everything in `hack/` at the moment is 100% non-essential to build and run the service catalog. By the dev guide, it sounds like these files should all go in `contrib/`. Shall we do that instead of merge `hack/` into `build/`?

**Comment by duglin** [comment]
I'm ok with moving them to contrib/[something] - maybe contrib/bin.

**Comment by krancour** [comment]
I agree with @mkibbe1993 about not using `/contrib/bin/` to hold scripts. I'm not opposed to the notion @duglin has suggested that "bin" implicitly includes any sort of executable (whether actually binary or not), _buuuuut_... I feel there's a precedent set elsewhere in this very project (i.e. the top-level `bin/` dir that is _outside_ `contrib/` that "bin" is for binaries compiled from our own code. i.e. I view "bin" as == "build dest."

I'm going to take a guess that we can all get on board with the following:

_Instead_ of merging `hack/` into `build/`...

1. `hack/` moves to `contrib/hack/`
1. `hack/jenkins/` moves to `contrib/jenkins/`
1. All necessary paths adjusted as a result of the above

I don't think I am wildly off here, so I am going to close this PR and open a new one with what has been discussed above.

**Pull request closed without merging**
