### PR TITLE
Validate that a ServiceClass must have at least one plan

### LINKED ISSUE #867: Validate that each service class must have at least one plan
Otherwise, you will be unable to provision it.

### PR DESCRIPTION
**Pull request by pmorie**
Closes #867

### CODE REVIEW

**Comment by MHBauer** [comment]
https://travis-ci.org/kubernetes-incubator/service-catalog/builds/234060985
framework flake?

**Comment by MHBauer** [comment]
framework flake. very scary.

**Comment by pmorie** [comment]
If you think there is a flake, the right thing to do is to create an issue.

**Comment by MHBauer** [comment]
Oh wait, no jenkins. What's going on here?

**Comment by kibbles-n-bytes** [comment]
This PR seems to be causing an infinite hang in Jenkins when it's going through the integration tests, had to manually kill it twice. Once we get through the backlog, I'll restart it and see if I can get more info.

**Comment by kibbles-n-bytes** [comment]
There we go; everything's back to normal.

**Pull request merged**
