### PR TITLE
link to the final charter in kubernetes/community

### PR DESCRIPTION
**Pull request by MHBauer**
This PR is a 
 - Documentation

**What this PR does / why we need it**:
dead link to personal repo not caught by vlinker @duglin 

Please leave this checklist in the PR comment so that maintainers can ensure a good PR.

Merge Checklist:
 - [ ] Do we need this line at all?

We link to the sig directory, so I'm not sure people get to this line, but the current link 404's in a personal repo, so we should probably avoid that. I don't understand vlinker, so maybe @duglin can check why it's being missed. 

/assign @carolynvs 
for whose personal repo the link formerly went to

/assign @duglin 
for vlinker debugging

/cc @jboyd01 @jberkhahn

### CODE REVIEW

**Comment by duglin** [comment]
```
$ verify-links.sh README.md 
README.md: Can't load url: https://service-catalog-jenkins.appspot.com/buildStatus/icon?job=service-catalog-master-testing
```

Weird, not sure why our testing doesn't catch that.

**Comment by duglin** [comment]
```
Running href checker (Checking external hrefs):
./README.md: Can't load url: https://service-catalog-jenkins.appspot.com/buildStatus/icon?job=service-catalog-master-testing (tried 5 times)
./README.md: Can't load url: https://github.com/carolynvs/community/blob/sig-service-catalog-charter/sig-service-catalog/charter.md (tried 5 times)
./docs/code-standards.md: Can't load url: https://github.com/kubernetes/community/blob/master/contributors/devel/coding-conventions.md (tried 5 times)
./docs/contribute/docs.md: Can't load url: http://localhost:4000 (tried 5 times)
```
and I get a non-zero exit code. Not sure why the official builds don't stop on these

**Comment by duglin** [comment]
From the test output:
```
Running href checker (Skipping external hrefs):
```
When you ask to skip http links, you won't see errors on missing http links :-)

I objected when we added this, and I still think it's a mistake.

**Comment by MHBauer** [comment]
Isn't it on for releases? Do we have failing releases?

**Comment by jboyd01** [comment]
I'll open a new issue to track why we are skipping external links
/lgtm

**Pull request merged**
